import { createHash, randomUUID } from "node:crypto";
import { mkdir, open, readFile, readdir, rename, rm } from "node:fs/promises";
import { dirname, extname, join } from "node:path";
import { extensionFor, validateProductionArtifact, type ProductionArtifact, type ProductionFormat, type ProductionOptions } from "../domain/manuscript-production";
import {
  createProductionArtifactEvidence,
  validateProductionArtifactEvidence,
  type ProductionArtifactEvidence,
  type ProductionArtifactVerification,
} from "../domain/production-artifact-evidence";

export class FileProductionArtifactVault {
  constructor(private readonly rootDirectory: string) {}

  async save(artifact: ProductionArtifact, options: ProductionOptions, sourceSha256: string): Promise<ProductionArtifactEvidence> {
    const issues = validateProductionArtifact(artifact).filter((issue) => issue.severity === "error");
    if (issues.length) throw new Error(`Production artifact failed validation: ${issues.map((issue) => issue.message).join(" ")}`);
    const bytes = Buffer.from(artifact.contentBase64, "base64");
    const sha256 = createHash("sha256").update(bytes).digest("hex");
    if (bytes.length !== artifact.byteLength) throw new Error("Production artifact byte length changed before persistence.");
    if (sha256 !== artifact.sha256.toLowerCase()) throw new Error("Production artifact SHA-256 does not match its generated bytes.");

    const directory = this.productionDirectory(artifact.projectId);
    await mkdir(directory, { recursive: true });
    const extension = extensionFor(artifact.format);
    const instanceId = randomUUID();
    const storageFileName = `${safeId(artifact.id)}-${instanceId}${extension}`;
    const evidence = createProductionArtifactEvidence(artifact, storageFileName, options, sourceSha256);
    const artifactPath = join(directory, storageFileName);
    const manifestPath = this.manifestPath(artifact.projectId, storageFileName);

    await writeAtomically(artifactPath, bytes);
    try {
      await writeAtomically(manifestPath, `${JSON.stringify(evidence, null, 2)}\n`);
    } catch (error) {
      await rm(artifactPath, { force: true }).catch(() => undefined);
      throw error;
    }
    return evidence;
  }

  async list(projectId: string, options: { readonly bookId?: string; readonly formats?: readonly ProductionFormat[] } = {}): Promise<readonly ProductionArtifactEvidence[]> {
    const id = safeId(projectId);
    let entries;
    try {
      entries = await readdir(this.productionDirectory(id), { withFileTypes: true });
    } catch (error) {
      if (isMissing(error)) return [];
      throw error;
    }
    const formats = options.formats ? new Set(options.formats) : undefined;
    const records: ProductionArtifactEvidence[] = [];
    for (const entry of entries) {
      if (!entry.isFile() || !entry.name.endsWith(".manifest.json")) continue;
      const raw = await readFile(join(this.productionDirectory(id), entry.name), "utf8");
      const evidence = validateProductionArtifactEvidence(JSON.parse(raw));
      if (evidence.projectId !== id) throw new Error(`Production artifact manifest ${entry.name} belongs to another project.`);
      if (options.bookId && evidence.bookId !== options.bookId) continue;
      if (formats && !formats.has(evidence.format)) continue;
      records.push(evidence);
    }
    return records.sort((a, b) => b.generatedAt.localeCompare(a.generatedAt) || b.storageFileName.localeCompare(a.storageFileName));
  }

  async verify(evidence: ProductionArtifactEvidence): Promise<ProductionArtifactVerification> {
    const record = validateProductionArtifactEvidence(evidence);
    const issues: string[] = [];
    try {
      const bytes = await readFile(join(this.productionDirectory(record.projectId), record.storageFileName));
      if (bytes.length !== record.byteLength) issues.push("Stored production artifact byte length does not match its manifest.");
      const sha256 = createHash("sha256").update(bytes).digest("hex");
      if (sha256 !== record.sha256) issues.push("Stored production artifact SHA-256 does not match its manifest.");
      if (extname(record.storageFileName).toLowerCase() !== extensionFor(record.format)) issues.push("Stored production artifact extension does not match its format.");
    } catch (error) {
      if (isMissing(error)) issues.push("Stored production artifact file is missing.");
      else throw error;
    }
    return Object.freeze({ evidence: record, valid: issues.length === 0, issues: Object.freeze(issues) });
  }

  async latestVerified(projectId: string, bookId: string, formats: readonly ProductionFormat[]): Promise<ProductionArtifactVerification | undefined> {
    const records = await this.list(projectId, { bookId, formats });
    for (const record of records) {
      const verified = await this.verify(record);
      if (verified.valid) return verified;
    }
    return undefined;
  }

  private productionDirectory(projectId: string): string {
    return join(this.rootDirectory, "projects", safeId(projectId), "production");
  }
  private manifestPath(projectId: string, storageFileName: string): string {
    if (!/^[A-Za-z0-9_.-]+$/.test(storageFileName) || storageFileName.includes("..")) throw new Error("Production artifact storage filename is unsafe.");
    return join(this.productionDirectory(projectId), `${storageFileName}.manifest.json`);
  }
}

async function writeAtomically(path: string, content: string | Buffer): Promise<void> {
  const directory = dirname(path);
  await mkdir(directory, { recursive: true });
  const temporaryPath = `${path}.${process.pid}.${randomUUID()}.tmp`;
  let handle: Awaited<ReturnType<typeof open>> | undefined;
  try {
    handle = await open(temporaryPath, "wx", 0o600);
    await handle.writeFile(content);
    await handle.sync();
    await handle.close();
    handle = undefined;
    await rename(temporaryPath, path);
    await syncDirectory(directory);
  } catch (error) {
    if (handle) await handle.close().catch(() => undefined);
    await rm(temporaryPath, { force: true }).catch(() => undefined);
    throw error;
  }
}

async function syncDirectory(directory: string): Promise<void> {
  if (process.platform === "win32") return;
  const handle = await open(directory, "r");
  try { await handle.sync(); } finally { await handle.close(); }
}
function safeId(value: string): string {
  if (!value || value !== value.trim() || !/^[A-Za-z0-9_-]+$/.test(value)) throw new Error("Production artifact identifier contains unsupported path characters.");
  return value;
}
function isMissing(error: unknown): boolean {
  return typeof error === "object" && error !== null && "code" in error && (error as { code?: string }).code === "ENOENT";
}
