import test from 'node:test';
import assert from 'node:assert/strict';
import { AiModelBroker } from '../dist/application/ai-model-broker.js';

test('AI model broker selects a healthy capable resource', () => { const broker=new AiModelBroker(); broker.setResources([{provider:'expensive',model:'writer-pro',configured:true,healthy:true,capabilities:{contextWindow:200000,reasoning:true},estimatedInputCostPerMillion:10},{provider:'local',model:'writer-local',configured:true,healthy:true,capabilities:{contextWindow:128000,reasoning:true},estimatedInputCostPerMillion:0}]); assert.equal(broker.select({task:'writing',requiresReasoning:true}).resource.provider,'local'); });
test('AI model broker rejects unavailable capabilities', () => { const broker=new AiModelBroker(); broker.setResources([{provider:'text',model:'text-1',configured:true,healthy:true,capabilities:{contextWindow:32000}}]); assert.throws(()=>broker.select({task:'vision',requiresVision:true}),/No healthy configured AI model/); });
test('AI model broker enforces output, streaming, and cost constraints', () => { const broker=new AiModelBroker(); broker.setResources([{provider:'fast',model:'small',configured:true,healthy:true,capabilities:{contextWindow:64000,maxOutputTokens:4096,streaming:true},estimatedInputCostPerMillion:0},{provider:'pro',model:'large',configured:true,healthy:true,capabilities:{contextWindow:200000,maxOutputTokens:32000,streaming:true,reasoning:true},estimatedInputCostPerMillion:3}]); assert.equal(broker.select({task:'writing',minimumContextWindow:100000,minimumOutputTokens:16000,requiresStreaming:true,maxInputCostPerMillion:5}).resource.model,'large'); });
test('AI model broker honors explicit model preference', () => { const broker=new AiModelBroker(); broker.setResources([{provider:'gateway',model:'alpha',configured:true,healthy:true,capabilities:{contextWindow:128000}},{provider:'gateway',model:'beta',configured:true,healthy:true,capabilities:{contextWindow:128000}}]); assert.equal(broker.select({task:'editing',preferModel:'beta'}).resource.model,'beta'); });
test('AI model broker protects a safety reserve before a near-limit request', () => { const broker=new AiModelBroker(); broker.setResources([{provider:'nearly-full',model:'a',configured:true,healthy:true,capabilities:{contextWindow:128000},remainingQuota:1000,quotaLimit:10000},{provider:'available',model:'b',configured:true,healthy:true,capabilities:{contextWindow:128000},remainingQuota:9000,quotaLimit:10000}]); const selected=broker.select({task:'writing',estimatedInputTokens:850}); assert.equal(selected.resource.provider,'available'); assert.ok(selected.reasons.some(r=>r.includes('pre-exhaustion safety reserve'))); });
test('AI model broker avoids a provider in cooldown', () => { const broker=new AiModelBroker(); broker.setResources([{provider:'cooling',model:'a',configured:true,healthy:true,cooldownUntil:'2030-01-01T00:00:00Z',capabilities:{contextWindow:128000}},{provider:'ready',model:'b',configured:true,healthy:true,capabilities:{contextWindow:128000}}]); assert.equal(broker.select({task:'editing',now:'2029-01-01T00:00:00Z'}).resource.provider,'ready'); });
test('AI model broker penalizes repeated failures and high latency', () => { const broker=new AiModelBroker(); broker.setResources([{provider:'flaky',model:'a',configured:true,healthy:true,consecutiveFailures:3,latencyMs:3000,capabilities:{contextWindow:128000}},{provider:'stable',model:'b',configured:true,healthy:true,consecutiveFailures:0,latencyMs:100,capabilities:{contextWindow:128000}}]); assert.equal(broker.select({task:'editing'}).resource.provider,'stable'); });
