const assert = require("node:assert/strict");
const test = require("node:test");
const { createBookPositioningReport, validateBookPositioningReport, BOOK_POSITIONING_DISCLAIMER, StaticBookPositioningProvider, BookPositioningService } = require("../.forge-build");
const comparable = [{ title:"Comparable Novel", author:"A. Author", reason:"Same audience and shelf position." }];
const positioning = { audience:"Adult readers of atmospheric mystery", problemOrDesire:"A tense escape and emotionally resonant mystery", genre:"Mystery", shelf:"Cozy-adjacent atmospheric mystery", differentiation:"A distinctive setting and character-driven premise", comparableBooks:comparable, clickReason:"The premise creates immediate curiosity." };
const concepts = { titles:["The Last Signal","Where the Water Ends"], subtitles:["A Mystery at the Reservoir"], hooks:["One disappearance changes everything."], elevatorPitches:["An atmospheric mystery about a disappearance that exposes a buried secret."], backCoverCopy:"A complete back-cover pitch.", amazonDescription:"A complete Amazon description.", authorBio:"A complete author biography.", taglines:["Some secrets refuse to stay buried."], promotionalHooks:["Discover the mystery readers are talking about."] };

test("Mission 019 stores the complete positioning contract",()=>{const report=createBookPositioningReport({id:"positioning-1",projectId:"project-1",bookId:"book-1",positioning,concepts,evidence:["Market comparison evidence"],limitations:["Market response remains uncertain."],disclaimer:BOOK_POSITIONING_DISCLAIMER,createdAt:"2026-08-27T00:00:00.000Z"});assert.equal(report.positioning.audience,"Adult readers of atmospheric mystery");assert.equal(report.concepts.titles.length,2);assert.equal(report.disclaimer,BOOK_POSITIONING_DISCLAIMER);assert.deepEqual(validateBookPositioningReport(report),report);});

test("Mission 019 provider and service preserve positioning provenance",async()=>{const result={positioning,concepts,evidence:["Observed market evidence"],limitations:["Reader response is not guaranteed."]};const service=new BookPositioningService(new StaticBookPositioningProvider(result));const report=await service.create({id:"positioning-2",projectId:"project-1",bookId:"book-1",manuscriptContext:"A manuscript about a disappearance at a reservoir.",marketContext:"Atmospheric mystery readers.",comparableBooks:comparable});assert.equal(report.projectId,"project-1");assert.equal(report.positioning.genre,"Mystery");assert.equal(report.concepts.amazonDescription,"A complete Amazon description.");assert.match(report.disclaimer,/not a guarantee/i);});

test("Mission 019 rejects commercial guarantees",()=>assert.throws(()=>createBookPositioningReport({id:"bad",projectId:"p",positioning,concepts,evidence:[],limitations:[],disclaimer:"This book will sell 10000 copies."}),/non-guarantee disclaimer/));
