const assert = require("node:assert/strict");
const test = require("node:test");
const { createCharacter } = require("../.forge-build/domain/character-bible.js");
const { CharacterStateProposalService } = require("../.forge-build/application/character-state-proposals.js");
const { createCharacterStateProposal, reviewCharacterStateProposal } = require("../.forge-build/domain/character-state-proposal.js");
const { FileCharacterStateProposalStore } = require("../.forge-build/infrastructure/file-character-state-proposal-store.js");
function profile() { return { name:"Mara Voss", age:31, birthDate:"1995-04-12", physicalAppearance:"Weathered", height:"5 ft 7 in", build:"Lean", hair:"Dark", eyes:"Gray", skin:"Olive", clothing:"Jacket", voice:"Low", speechPatterns:["Short sentences"], personality:"Guarded", values:["Truth"], fears:["Failure"], secrets:["Withheld evidence"], goals:["Find witness"], motivations:["Protect others"], relationships:[], history:"Investigator", knowledge:["Reservoir roads"], skills:["Investigation"], weaknesses:["Distrust"], characterArc:"Learns trust", importantObjects:["Compass"], currentEmotionalState:"Watchful", currentLocation:"Shore", currentInjuries:[] }; }
test("character state proposals require evidence and never start accepted",()=>{ const character=createCharacter({id:"mara",projectId:"p",profile:profile()}); const proposal=createCharacterStateProposal({id:"cp-1",projectId:"p",characterId:"mara",sceneId:"s1",confidence:.91,changes:{currentLocation:"Watchtower"},changedFields:["currentLocation"],evidence:[{quote:"Mara climbed to the watchtower.",rationale:"Direct location evidence"}],rationale:"The scene explicitly relocates Mara.",sourceContentSha256:"a".repeat(64),createdAt:"2026-01-01T00:00:00.000Z"}); assert.equal(proposal.status,"pending"); assert.throws(()=>createCharacterStateProposal({id:"cp-2",projectId:"p",characterId:"mara",sceneId:"s1",confidence:1.2,changes:{currentLocation:"X"},changedFields:["currentLocation"],evidence:[{quote:"X",rationale:"X"}],rationale:"X",sourceContentSha256:"a".repeat(64),createdAt:"2026-01-01T00:00:00.000Z"}),/confidence/); assert.equal(character.profile.currentLocation,"Shore"); });
test("review is explicit and terminal",()=>{ const proposal=createCharacterStateProposal({id:"cp-1",projectId:"p",characterId:"mara",sceneId:"s1",confidence:.8,changes:{currentEmotionalState:"Frightened"},changedFields:["currentEmotionalState"],evidence:[{quote:"She trembled.",rationale:"Direct evidence"}],rationale:"Emotion changes",sourceContentSha256:"b".repeat(64),createdAt:"2026-01-01T00:00:00.000Z"}); const accepted=reviewCharacterStateProposal(proposal,"accepted",{reviewedAt:"2026-01-02T00:00:00.000Z",note:"Confirmed"}); assert.equal(accepted.status,"accepted"); assert.throws(()=>reviewCharacterStateProposal(accepted,"rejected"),/already been reviewed/); });
test("AI extraction accepts only supported evidence-grounded changes",async()=>{ const character=createCharacter({id:"mara",projectId:"p",profile:profile()}); const service=new CharacterStateProposalService(async()=>JSON.stringify({confidence:.88,rationale:"Scene directly changes location.",changes:{currentLocation:"Watchtower",unknownField:"ignore"},evidence:[{quote:"Mara reached the watchtower.",start:0,end:31,rationale:"Direct location statement"}]})); const proposal=await service.propose({projectId:"p",character,sceneId:"s1",sceneContent:"Mara reached the watchtower."}); assert.deepEqual(proposal.changedFields,["currentLocation"]); assert.equal(proposal.status,"pending"); assert.equal(proposal.evidence[0].quote,"Mara reached the watchtower."); });
test("durable proposal store isolates projects",async()=>{ const fs=require("node:fs/promises"); const os=require("node:os"); const path=require("node:path"); const root=await fs.mkdtemp(path.join(os.tmpdir(),"forge-csp-")); try{ const store=new FileCharacterStateProposalStore(root); const proposal=createCharacterStateProposal({id:"cp-1",projectId:"p1",characterId:"mara",sceneId:"s1",confidence:.9,changes:{currentLocation:"Tower"},changedFields:["currentLocation"],evidence:[{quote:"Tower",rationale:"Evidence"}],rationale:"Evidence",sourceContentSha256:"c".repeat(64),createdAt:"2026-01-01T00:00:00.000Z"}); await store.save(proposal); assert.equal((await store.list("p1")).length,1); assert.equal((await store.list("p2")).length,0); } finally { await fs.rm(root,{recursive:true,force:true}); } });
