const assert=require("node:assert/strict");
const test=require("node:test");
const forge=require("../dist");

test("Mission 029 exposes all collaboration modes and author approval",()=>{const service=new forge.CollaborationModeService("p1");assert.deepEqual(service.getModes(),["co-pilot","partner","director","autonomous","editor"]);for(const mode of service.getModes())assert.equal(service.resolve(mode).authorApprovalRequired,true);assert.equal(service.resolve("co-pilot").aiWorkShare,"low");assert.equal(service.resolve("director").aiWorkShare,"high");assert.equal(service.resolve("editor").editingFocus,true);});

test("Mission 030 creates a bounded project health dashboard",()=>{const health=new forge.ProjectHealthService("p1").build({bookCompletionPercent:64,chaptersComplete:18,chaptersTotal:28,wordCount:74821,wordTarget:110000,canonConflicts:{critical:0,minor:2},unresolvedPlotThreads:4,characters:23,locations:17,researchSources:84,illustrations:19,coverStatus:"Approved",marketingCompletionPercent:62,publishingReadinessPercent:91});assert.equal(health.projectId,"p1");assert.equal(health.chaptersComplete,18);assert.equal(health.publishingReadinessPercent,91);assert.throws(()=>forge.createProjectHealth({...health,bookCompletionPercent:101}),/Percentage/);});

test("Mission 031 preserves relationship-aware memory context",()=>{const service=new forge.RelationshipMemoryService("p1");const record=service.create({id:"m1",subject:"Sarah",predicate:"lives in",object:"Denver",context:"Established in Chapter 3; affects hospital access in Chapter 18.",sourceId:"chapter-3",sourceLocation:"Chapter 3",relevance:"hospital access in Chapter 18"});assert.equal(record.projectId,"p1");assert.equal(service.findRelated([record],"Sarah").length,1);assert.equal(service.findRelated([record],"Denver").length,1);assert.equal(service.findRelated([record],"Other").length,0);});

test("Mission 032 requires every delivery audit before author approval",()=>{const service=new forge.DeliveryAuditService("p1");const incomplete=service.audit([{kind:"canon",passed:true,critical:false,message:"ok"}]);assert.equal(incomplete.readyForAuthorApproval,false);const results=service.requiredKinds().map(kind=>({kind,passed:true,critical:false,message:"passed"}));const complete=service.audit(results);assert.equal(complete.readyForAuthorApproval,true);const failed=service.audit(results.map(r=>r.kind==="cover"?{...r,passed:false,message:"cover attention"}:r));assert.equal(failed.readyForAuthorApproval,false);assert.throws(()=>service.audit([...results,results[0]]),/Duplicate delivery audit kind/);});
