const assert=require("node:assert/strict");
const test=require("node:test");
const forge=require("../dist");

test("Missions 033-034 keep K.I.N.G.S. escalation and ownership boundaries explicit",async()=>{const calls=[];const gateway={research:async()=>calls.push("research"),plan:async()=>calls.push("plan"),build:async()=>calls.push("build"),test:async()=>calls.push("test"),verify:async()=>calls.push("verify")};const escalation=await new forge.KingsRelationshipService("p1",gateway).escalate({id:"gap-1",capability:"advanced illustration consistency",reason:"Forge lacks the required capability."});assert.equal(escalation.status,"completed");assert.deepEqual(calls,["research","plan","build","test","verify"]);const security=new forge.SecurityOwnershipService("p1");security.authorize("read");assert.throws(()=>security.authorize("research"),/Permission denied/);assert.equal(security.canUploadExternally(),false);const audit=security.record({id:"a1",actor:"author",action:"read",target:"manuscript",externalUpload:false,attributableTo:"p1"});assert.equal(audit.projectId,"p1");assert.equal(security.getAuditHistory().length,1);});

test("Mission 035 provides platform and accessibility contracts",()=>{const profile=forge.createAccessibilityProfile({keyboard:true,mouse:true,touch:true,voice:true,screenReader:true,largeText:true,highContrast:true});assert.equal(profile.voice,true);assert.deepEqual(forge.SUPPORTED_PLATFORMS,["android","ios","windows","macos","linux","web"]);assert.deepEqual(forge.ACCESS_INPUTS,["keyboard","mouse","touch","voice"]);});

test("Mission 036 preserves original voice transcription while deriving structured intent",()=>{const service=new forge.VoiceInputService("p1");const record=service.capture("voice-1","I want Chapter 14 to start with Marcus driving through Ogden in a snowstorm.");assert.equal(record.transcription,"I want Chapter 14 to start with Marcus driving through Ogden in a snowstorm.");assert.equal(record.intent.kind,"scene-direction");assert.equal(record.projectId,"p1");});

test("Mission 037 records content provenance and requires consent where applicable",()=>{const service=new forge.ContentProvenanceService("p1");assert.throws(()=>service.record({id:"upload-1",origin:"user-uploaded"}),/explicit consent/);const record=service.record({id:"upload-1",origin:"user-uploaded",consent:"granted",license:"author-owned"});assert.equal(record.origin,"user-uploaded");assert.equal(record.consent,"granted");const research=service.record({id:"r1",origin:"external-research",source:"https://example.test/source"});assert.equal(research.source,"https://example.test/source");});

test("Mission 040 Book Genome identifies downstream impact of a canon change",()=>{const service=new forge.BookGenomeService("p1");const genome=service.create({nodes:[{id:"canon-1",type:"canon",label:"Marcus location",data:{}},{id:"scene-14",type:"scenes",label:"Chapter 14",data:{}},{id:"art-14",type:"art",label:"Chapter 14 art",data:{}},{id:"book-2",type:"publishing-state",label:"Book 2",data:{}}],edges:[{from:"canon-1",to:"scene-14",relation:"affects"},{from:"scene-14",to:"art-14",relation:"depicts"},{from:"canon-1",to:"book-2",relation:"constrains"}]});const impact=service.impact(genome,"canon-1");assert.equal(impact.affectedNodeIds.length,3);assert.ok(impact.affectedComponents.includes("scenes"));assert.ok(impact.affectedComponents.includes("art"));assert.ok(impact.affectedComponents.includes("publishing-state"));});

test("Mission 041 blocks final readiness until every production stage is complete",()=>{const service=new forge.FinalProductService("p1");const incomplete=service.status(["concept","architecture"],"architecture");assert.equal(incomplete.ready,false);assert.match(incomplete.message,/NOT READY/);const complete=service.status(forge.FINAL_PRODUCT_STAGES,"archive");assert.equal(complete.ready,true);assert.equal(complete.message,"PROJECT READY FOR AUTHOR APPROVAL");});

test("Mission 042 final product stage list covers the complete publishing path",()=>{assert.deepEqual(forge.FINAL_PRODUCT_STAGES,["concept","architecture","canon","characters","timeline","research","manuscript","editing","illustrations","cover","formatting","metadata","positioning","marketing","publishing","archive"]);});
