const assert=require("node:assert/strict");const test=require("node:test");const {mkdtemp,rm}=require("node:fs/promises");const {tmpdir}=require("node:os");const {join}=require("node:path");const {ILLUSTRATION_MODES,ILLUSTRATION_TYPES,createIllustrationRequest,reviseIllustrationRequest,generateIllustrationBrief,createIllustrationStudioState,withIllustrationRequest,withIllustrationRevision,IllustrationStudioService,FileIllustrationStudioStore}=require("../.forge-build/index.js");
const refs=[{id:"face-1",uri:"assets/face.jpg",label:"Face",notes:"Canonical face",kind:"character-visual-identity"},{id:"place-1",uri:"assets/place.jpg",label:"Location",notes:"Environment reference",kind:"environment"}];
const continuity={characterIdentityIds:["visual-1"],environmentIdentityIds:["env-1"],seriesId:"series-1",bookId:"book-1",chapterId:"chapter-4",sceneId:"scene-2"};
function request(overrides={}){return createIllustrationRequest({id:"ill-1",projectId:"project-1",mode:"character-consistent",type:"scene",concept:"Mara stands at the old watchtower.",prompt:"Grounded cinematic composition",references:refs,continuity,era:"2021 winter",location:"Pineview Reservoir",storyOrder:27,now:"2026-01-01T00:00:00Z",...overrides});}
test("Mission 012 supports every illustration mode and artwork type",()=>{assert.deepEqual(ILLUSTRATION_MODES,["ai-only","assisted","collaborative","reference-driven","character-consistent","historical-era-aware","environment-consistent"]);assert.deepEqual(ILLUSTRATION_TYPES,["scene","character-portrait","map","object","environment"]);for(const mode of ILLUSTRATION_MODES)assert.equal(createIllustrationRequest({id:`${mode}-1`,projectId:"p",mode,type:"scene",concept:"Valid concept"}).mode,mode);for(const type of ILLUSTRATION_TYPES)assert.equal(createIllustrationRequest({id:`type-${type}`,projectId:"p",mode:"assisted",type,concept:"Valid concept"}).type,type)});
test("illustration requests retain references and continuity inputs",()=>{const x=request();assert.equal(x.references[0].kind,"character-visual-identity");assert.deepEqual(x.continuity.characterIdentityIds,["visual-1"]);assert.equal(x.era,"2021 winter");assert.equal(x.storyOrder,27);assert.equal(generateIllustrationBrief(x).includes("series-1"),true)});
test("collaborative revisions are immutable and auditable",()=>{const original=request();const result=reviseIllustrationRequest(original,{revisionId:"rev-1",concept:"Mara raises a lantern at the old watchtower.",actor:"author",reason:"Collaborative refinement",now:"2026-01-02T00:00:00Z"});assert.equal(original.concept,"Mara stands at the old watchtower.");assert.equal(result.request.concept,"Mara raises a lantern at the old watchtower.");assert.equal(result.revision.id,"rev-1");assert.equal(result.revision.actor,"author")});
test("studio state enforces project ownership and revision relationships",()=>{let s=createIllustrationStudioState("project-1");const x=request();s=withIllustrationRequest(s,x);const revised=reviseIllustrationRequest(x,{revisionId:"rev-1",concept:"Refined scene",reason:"Refinement"});s=withIllustrationRevision(s,revised.revision);assert.equal(s.requests.length,1);assert.equal(s.revisions.length,1);assert.throws(()=>withIllustrationRequest(s,{...x,id:"other",projectId:"project-2"}),/another project/);assert.throws(()=>withIllustrationRevision(s,{...revised.revision,id:"rev-2",requestId:"missing"}),/unknown request/)});
test("service supports reusable generation briefs and portable restoration",()=>{const service=new IllustrationStudioService();service.create(request());assert.equal(service.list({projectId:"project-1",mode:"character-consistent",type:"scene"}).length,1);assert.match(service.generateBrief("project-1","ill-1"),/Character identities: visual-1/);const portable=service.toPortableState("project-1");const restored=new IllustrationStudioService();restored.restoreProject("project-1",portable);assert.equal(restored.require("project-1","ill-1").continuity.seriesId,"series-1");assert.throws(()=>restored.restoreProject("project-2",portable),/another project/)});
test("file store persists illustration studio state atomically and reloads it",async()=>{const root=await mkdtemp(join(tmpdir(),"authors-forge-illustration-"));try{let s=createIllustrationStudioState("project-1");s=withIllustrationRequest(s,request());const store=new FileIllustrationStudioStore(root);await store.save("project-1",s);assert.equal(await store.exists("project-1"),true);const loaded=await store.load("project-1");assert.deepEqual(loaded,s);await assert.rejects(()=>store.save("project-2",s),/another project/)}finally{await rm(root,{recursive:true,force:true})}});
