const test = require("node:test");
const assert = require("node:assert/strict");
const { createIllustrationAsset, createCharacterDesignLock, resolveCharacterDesignLock, updateIllustrationAsset, validateIllustrationAssetLibraryState, IllustrationAssetLibraryService, withProjectIllustrationAssetLibrary, createProject } = require("../.forge-build");
function input(overrides = {}) { return { id: "asset-001", projectId: "project-001", bookId: "book-001", chapterId: "chapter-001", sceneId: "scene-001", characterId: "character-001", locationId: "location-001", prompt: "A rain-soaked detective outside the old theater", references: [{ id: "ref-001", uri: "file:///refs/detective.png", label: "Detective reference", kind: "character", notes: "Canonical face reference" }], style: "cinematic graphic novel", generationSettings: { model: "provider-model", width: 1536, height: 1024, steps: 30, guidance: 7.5 }, version: 1, date: "2026-08-27T10:00:00.000Z", approvalStatus: "approved", assetUri: "file:///art/asset-001.png", now: "2026-08-27T10:00:00.000Z", ...overrides }; }
test("Mission 014 stores the complete illustration asset contract", () => { const asset = createIllustrationAsset(input()); for (const field of ["projectId", "bookId", "chapterId", "sceneId", "characterId", "locationId", "prompt", "references", "style", "generationSettings", "version", "date", "approvalStatus"]) assert.ok(field in asset, field); assert.equal(asset.version, 1); assert.equal(asset.approvalStatus, "approved"); assert.equal(asset.references[0].label, "Canonical face reference"); });
test("asset revisions are immutable and preserve the original", () => { const original = createIllustrationAsset(input()); const revised = updateIllustrationAsset(original, { id: original.id, prompt: "Reframed rain-soaked detective outside the old theater", version: 2, now: "2026-08-27T11:00:00.000Z" }); assert.equal(original.version, 1); assert.notEqual(original.prompt, revised.prompt); assert.equal(revised.version, 2); });
test("assets can be reused as new library records without destroying the source", () => { const service = new IllustrationAssetLibraryService(); service.create(input()); const reused = service.reuse("asset-001", { id: "asset-002", projectId: "project-001", bookId: "book-002", chapterId: "chapter-010", sceneId: "scene-004" }); assert.equal(reused.reusedFromAssetId, "asset-001"); assert.equal(reused.assetUri, "file:///art/asset-001.png"); assert.equal(service.require("asset-001").version, 1); assert.equal(reused.version, 2); });
test("use this character design everywhere going forward is represented by a durable effective lock", () => { const asset = createIllustrationAsset(input()); const lock = createCharacterDesignLock({ id: "lock-001", projectId: "project-001", seriesId: "series-001", characterId: "character-001", assetId: asset.id, effectiveAt: "2026-08-27T12:00:00.000Z", reason: "Use this character design everywhere going forward", createdAt: "2026-08-27T12:00:00.000Z" }); const state = { formatVersion: 1, projectId: "project-001", assets: [asset], characterDesignLocks: [lock] }; assert.equal(resolveCharacterDesignLock(state, "character-001", "2026-08-27T11:59:59.000Z"), undefined); assert.equal(resolveCharacterDesignLock(state, "character-001", "2026-08-27T12:00:00.000Z").assetId, asset.id); });
test("library service resolves the canonical character design", () => { const service = new IllustrationAssetLibraryService(); service.create(input()); service.lockCharacterDesign({ id: "lock-001", projectId: "project-001", seriesId: "series-001", characterId: "character-001", assetId: "asset-001", effectiveAt: "2026-08-27T12:00:00.000Z", reason: "Canonical design" }); assert.equal(service.resolveCharacterDesign("project-001", "character-001", "2026-08-27T12:01:00.000Z").id, "asset-001"); assert.equal(service.resolveCharacterDesign("project-001", "character-001", "2026-08-27T11:59:00.000Z"), undefined); });
test("portable library state validates and attaches to the project boundary", () => { const asset = createIllustrationAsset(input()); const state = validateIllustrationAssetLibraryState({ formatVersion: 1, projectId: "project-001", assets: [asset], characterDesignLocks: [] }); const project = createProject({ id: "project-001", title: "Continuity Test", now: "2026-08-27T13:00:00.000Z" }); const updated = withProjectIllustrationAssetLibrary(project, state, "2026-08-27T13:01:00.000Z"); assert.equal(updated.illustrationAssetLibrary.assets[0].id, "asset-001"); assert.equal(updated.metadata.updatedAt, "2026-08-27T13:01:00.000Z"); assert.throws(() => withProjectIllustrationAssetLibrary(project, { ...state, projectId: "other-project" }, "2026-08-27T13:02:00.000Z"), /another project/i); });
