const test = require("node:test");
const assert = require("node:assert/strict");
const { generateWithKingsAi } = require("../.forge-build/infrastructure/kings-ai-bridge.js");

test("KINGS bridge sends the governed Responses-compatible contract", async () => {
  const originalFetch = global.fetch;
  let request;
  global.fetch = async (url, options) => {
    request = { url, options };
    return new Response(JSON.stringify({ id: "kings-1", output_text: "generated by KINGS" }), { status: 200, headers: { "content-type": "application/json" } });
  };
  try {
    const result = await generateWithKingsAi({ endpoint: "http://127.0.0.1:9999/v1/responses", model: "local-kings" }, { system: "system", user: "write" });
    assert.equal(result.provider, "kings");
    assert.equal(result.model, "local-kings");
    assert.equal(result.text, "generated by KINGS");
    assert.equal(request.url, "http://127.0.0.1:9999/v1/responses");
    const body = JSON.parse(request.options.body);
    assert.equal(body.model, "local-kings");
    assert.deepEqual(body.input, [{ role: "system", content: "system" }, { role: "user", content: "write" }]);
  } finally {
    global.fetch = originalFetch;
  }
});

test("KINGS bridge refuses an unconfigured model", async () => {
  await assert.rejects(() => generateWithKingsAi({ endpoint: "http://127.0.0.1:9999/v1/responses" }, { system: "system", user: "write" }), /KINGS_AI_MODEL is required/);
});
