const test = require("node:test");
const assert = require("node:assert/strict");
const { generateWithKingsAi } = require("../.forge-build/infrastructure/kings-ai-bridge.js");
const { discoverConfiguredAiModelResources } = require("../.forge-build/infrastructure/ai-model-resources.js");

test("KINGS bridge sends the governed Responses-compatible contract", async () => {
  const originalFetch = global.fetch;
  let request;
  global.fetch = async (url, options) => {
    request = { url, options };
    return new Response(JSON.stringify({ id: "kings-1", output_text: "generated by KINGS", usage: { input_tokens: 5, output_tokens: 4, total_tokens: 9 } }), { status: 200, headers: { "content-type": "application/json" } });
  };
  try {
    const result = await generateWithKingsAi({ endpoint: "http://127.0.0.1:9999/v1/responses", model: "local-kings" }, { system: "system", user: "write" });
    assert.equal(result.provider, "kings");
    assert.equal(result.model, "local-kings");
    assert.equal(result.text, "generated by KINGS");
    assert.equal(result.usage.totalTokens, 9);
    assert.equal(request.url, "http://127.0.0.1:9999/v1/responses");
    const body = JSON.parse(request.options.body);
    assert.equal(body.model, "local-kings");
    assert.deepEqual(body.input, [{ role: "system", content: "system" }, { role: "user", content: "write" }]);
  } finally {
    global.fetch = originalFetch;
  }
});

test("KINGS owner/coding-machine root is not falsely treated as a generic text provider", () => {
  const env = {
    KINGS_AI_ENDPOINT: "http://127.0.0.1:8787",
    KINGS_AI_MODEL: "auto",
  };
  const resources = discoverConfiguredAiModelResources(env);
  assert.equal(resources.some((resource) => resource.provider === "kings"), false);
  assert.equal(env.KINGS_AI_ENDPOINT, "http://127.0.0.1:8787");
});

test("explicit KINGS Responses endpoint creates a fail-closed text resource", () => {
  const env = {
    KINGS_AI_ENDPOINT: "http://127.0.0.1:8787",
    KINGS_AI_RESPONSES_URL: "http://127.0.0.1:9999/v1/responses",
    KINGS_AI_MODEL: "creative-route",
  };
  const resources = discoverConfiguredAiModelResources(env);
  const kings = resources.find((resource) => resource.provider === "kings");
  assert.equal(kings.model, "creative-route");
  assert.equal(kings.billingClass, "unknown", "KINGS cost must not be assumed local/free");
  assert.equal(env.KINGS_AI_ENDPOINT, "http://127.0.0.1:9999/v1/responses", "legacy bridge variable is rewritten only after a real Responses endpoint is explicit");
});

test("legacy KINGS_AI_ENDPOINT remains supported only when it is explicitly a Responses route", () => {
  const env = {
    KINGS_AI_ENDPOINT: "http://127.0.0.1:9999/v1/responses",
    KINGS_AI_MODEL: "legacy-route",
    KINGS_AI_BILLING_CLASS: "local",
  };
  const kings = discoverConfiguredAiModelResources(env).find((resource) => resource.provider === "kings");
  assert.equal(kings.model, "legacy-route");
  assert.equal(kings.billingClass, "local");
});

test("KINGS bridge refuses owner root and an unconfigured model", async () => {
  await assert.rejects(() => generateWithKingsAi({ endpoint: "http://127.0.0.1:8787", model: "local-kings" }, { system: "system", user: "write" }), /owner\/coding-machine root is not a generic text-generation API/);
  await assert.rejects(() => generateWithKingsAi({ endpoint: "http://127.0.0.1:9999/v1/responses" }, { system: "system", user: "write" }), /KINGS_AI_MODEL is required/);
});