const assert=require("node:assert/strict");
const {createAiCollaborationPolicy,createProjectHealthReport,createMemoryRelationship,createDeliveryAuditReport}=require("../.forge-build");

test("Mission 029 exposes all collaboration modes with explicit authority",()=>{for(const mode of ["co-pilot","partner","director","autonomous","editor"])assert.equal(createAiCollaborationPolicy(mode).mode,mode);assert.equal(createAiCollaborationPolicy("autonomous").authorApprovalRequiredForMajorDecisions,true);assert.throws(()=>createAiCollaborationPolicy("invalid"));});

test("Mission 030 creates a complete health report",()=>{const r=createProjectHealthReport({projectId:"p1",generatedAt:"2026-01-01T00:00:00.000Z",metrics:{bookCompletionPercent:64,chaptersComplete:18,chaptersTotal:28,wordCount:74821,wordCountTarget:110000,criticalCanonConflicts:0,minorCanonConflicts:2,unresolvedPlotThreads:4,characters:23,locations:17,researchSources:84,illustrations:19,coverStatus:"approved",marketingCompletionPercent:62,publishingReadinessPercent:91}});assert.equal(r.metrics.chaptersComplete,18);assert.equal(r.status,"attention");});

test("Mission 031 preserves relationship-aware memory context",()=>{const r=createMemoryRelationship({id:"rel1",projectId:"p1",sourceMemoryId:"m3",targetMemoryId:"m18",relation:"causes",context:"Sarah lives in Denver because Chapter 3 establishes her residence; this matters to her ability to reach the hospital in Chapter 18.",significance:"Continuity and plot logistics"});assert.equal(r.formatVersion,1);assert.equal(r.relation,"causes");assert.throws(()=>createMemoryRelationship({...r,sourceMemoryId:r.targetMemoryId,targetMemoryId:r.targetMemoryId}));});

test("Mission 032 only reaches author approval when every audit check passes",()=>{const ready=createDeliveryAuditReport({projectId:"p1",checks:["canon","continuity","timeline","character","pov","style","grammar","formatting","research","artwork","cover","metadata","publishing"].map(category=>({id:category,category,passed:true,severity:"critical",message:`${category} audit passed.`}))});assert.equal(ready.status,"ready-for-author-approval");assert.equal(ready.passedCount,13);const blocked=createDeliveryAuditReport({projectId:"p1",checks:[{id:"canon",category:"canon",passed:false,severity:"critical",message:"Canon conflict detected.",remediation:"Resolve the conflict before delivery."}]});assert.equal(blocked.status,"blocked");});
