const test=require('node:test');
const assert=require('node:assert/strict');
const {mkdtemp,rm}=require('node:fs/promises');
const {tmpdir}=require('node:os');
const {join}=require('node:path');
const {FileSpecializedCreationStore}=require('../dist/infrastructure/file-specialized-creation-store.js');
const {ProjectMemoryStore}=require('../dist/application/project-memory-store.js');
const {SpecializedCreationOfficeService}=require('../dist/application/specialized-creation-office-service.js');
const {SpecializedCreationTcgAiService}=require('../dist/application/specialized-creation-tcg-ai.js');
const {createTcgGameStarterData,tcgGameFramework}=require('../dist/application/specialized-creation-tcg-design.js');

async function fixture(response){const dir=await mkdtemp(join(tmpdir(),'forge-tcg-text-ai-')),store=new FileSpecializedCreationStore(join(dir,'specialized.json')),memory=new ProjectMemoryStore(),office=new SpecializedCreationOfficeService(store,memory,undefined,async()=>{throw new Error('generic AI not used')});let project=await office.create({id:'tcg',forgeProjectId:'forge',mode:'trading-card-game',title:'Forge Realms',brief:'Original progression card game'});project=await office.setModeData('forge','tcg',createTcgGameStarterData({gameTitle:'Forge Realms',setId:'FR1',setName:'Origins'}));const ai=new SpecializedCreationTcgAiService(store,memory,async()=>({text:JSON.stringify(response),provider:'fixture-provider',model:'fixture-model',requestId:'tcg-ai-request'}));return{dir,store,office,ai};}

const framework={premise:'Guardians restore a fractured world.',playerGoal:'Secure three keystone territories.',victoryConditions:['Control three keystones at end of turn.'],turnStructure:['Ready','Draw','Action','Conflict','End'],zones:['deck','hand','field','discard'],resources:['aether'],cardTypes:['character','territory','power'],keywords:[{id:'guard',name:'Guard',reminderText:'Protect an adjacent ally.',rulesText:'A Guard may intercept one eligible attack each turn.'}],factions:[{id:'dawn',name:'Dawn Wardens',description:'Protectors of restored territories.'}],characterLines:[],worldMaps:[],designNotes:['Begin with a small test set.']};

test('TCG AI framework remains proposed until explicit approval and preserves provider evidence',async()=>{const fx=await fixture({summary:'Structured original game foundation.',payload:framework});try{const proposed=await fx.ai.propose({forgeProjectId:'forge',specializedProjectId:'tcg',scope:'game-framework',instruction:'Create the first rules framework.'});assert.equal(proposed.proposal.status,'proposed');assert.equal(proposed.ai.provider,'fixture-provider');assert.equal(proposed.ai.requestId,'tcg-ai-request');let stored=await fx.store.get('forge','tcg');assert.equal(tcgGameFramework(stored.modeData).premise,'');stored=await fx.ai.approveAndApply({forgeProjectId:'forge',specializedProjectId:'tcg',proposalId:proposed.proposal.id});assert.equal(tcgGameFramework(stored.modeData).premise,framework.premise);assert.equal(stored.proposals[0].status,'approved');}finally{await rm(fx.dir,{recursive:true,force:true});}});

test('balance review is advisory and approval cannot mutate TCG canon',async()=>{const payload={findings:['Early curve is concentrated.'],risks:['Single strategy may dominate.'],counterplayQuestions:['Can territory control answer fast characters?'],outliers:['No measured outlier yet.'],playtestExperiments:['Run ten mirrored starter-deck games and record first-player win rate.']};const fx=await fixture({summary:'Playtest hypotheses only.',payload});try{const proposed=await fx.ai.propose({forgeProjectId:'forge',specializedProjectId:'tcg',scope:'balance-review',instruction:'Review this starter structure for playtest risks.'});const before=await fx.store.get('forge','tcg'),after=await fx.ai.approveAndApply({forgeProjectId:'forge',specializedProjectId:'tcg',proposalId:proposed.proposal.id});assert.deepEqual(after.modeData,before.modeData);assert.equal(after.proposals[0].status,'approved');}finally{await rm(fx.dir,{recursive:true,force:true});}});
