const test=require('node:test');
const assert=require('node:assert/strict');
const {mkdtemp,rm}=require('node:fs/promises');
const {tmpdir}=require('node:os');
const {join}=require('node:path');
const {createSpecializedOfficeProject}=require('../dist/domain/specialized-creation-office.js');
const {composeSpecializedProject}=require('../dist/application/specialized-creation-mode-composer.js');
const {setComicReadingDirection,reorderComicPanels,createFoldedCardImpositionDocument,foldedCardImpositionProfile,createTcgSheetDocument,tcgSheetProfile,versionProductionProfile}=require('../dist/application/specialized-creation-finishing.js');
const {FileSpecializedCreationStore}=require('../dist/infrastructure/file-specialized-creation-store.js');
const {SpecializedCreationScopedArtifactService}=require('../dist/application/specialized-creation-scoped-artifacts.js');

const comic={issueTitle:'Directional',pages:[{page:1,panels:[{id:'a',page:1,order:1,description:'A',dialogue:[],captions:[],sfx:[],assetIds:[]},{id:'b',page:1,order:2,description:'B',dialogue:[],captions:[],sfx:[],assetIds:[]}]}]};
test('comic reading direction and panel reordering stay structured and preserve stable IDs',()=>{const rtl=setComicReadingDirection(comic,'rtl');assert.equal(rtl.readingDirection,'rtl');const reordered=reorderComicPanels(rtl,1,['b','a']);assert.deepEqual(reordered.pages[0].panels.map(p=>p.id),['b','a']);assert.deepEqual(reordered.pages[0].panels.map(p=>p.order),[1,2]);assert.equal(reordered.readingDirection,'rtl');});

test('folded card imposition maps back/front and inside surfaces onto explicit flat sheets',()=>{let project=createSpecializedOfficeProject({id:'fold',forgeProjectId:'forge',mode:'greeting-card',title:'Fold',brief:'Fold proof'});project={...project,modeData:{occasion:'thanks',tone:'warm',message:'Thank you.'}};const source=composeSpecializedProject(project);const profile=foldedCardImpositionProfile(project.productionProfiles[0]);const imposed=createFoldedCardImpositionDocument(project,source,'2026-09-01T06:00:00.000Z');assert.equal(profile.widthInches,10);assert.equal(imposed.surfaces.length,2);assert.equal(imposed.surfaces[0].widthInches,10);assert.match(imposed.surfaces[0].label,/back \| front/);assert.ok(imposed.surfaces[0].elements.some(e=>e.role==='fold-guide'));});

test('TCG printable sheets create mirrored front/back pairs and profile records duplex rule',()=>{let project=createSpecializedOfficeProject({id:'tcg',forgeProjectId:'forge',mode:'trading-card-game',title:'TCG',brief:'Sheet'});project={...project,modeData:{gameTitle:'Forge Realms',setId:'FR1',setName:'Set',fields:[{key:'name',label:'Name',type:'text',required:true}],templates:[{id:'base',name:'Base',tokens:{}}],cards:Array.from({length:10},(_,i)=>({id:`c${i+1}`,collectorNumber:String(i+1).padStart(3,'0'),templateId:'base',fields:{name:`Card ${i+1}`}})),playtestSnapshots:[]}};const source=composeSpecializedProject(project),profile=tcgSheetProfile(project.productionProfiles[0],'long-edge'),sheet=createTcgSheetDocument(project,source,'long-edge','2026-09-01T06:00:00.000Z');assert.equal(profile.widthInches,8.5);assert.equal(profile.heightInches,11);assert.match(profile.notes.join(' '),/mirrors columns/);assert.equal(sheet.surfaces.length,4);assert.equal(sheet.surfaces[0].kind,'sheet');assert.equal(sheet.surfaces[1].kind,'sheet');assert.ok(sheet.surfaces[1].elements.some(e=>e.metadata.duplexBack===true));});

test('production profiles are versioned instead of silently overwriting physical requirements',()=>{const project=createSpecializedOfficeProject({id:'flyer',forgeProjectId:'forge',mode:'flyer',title:'Flyer',brief:'Profile'});const v2=versionProductionProfile(project.productionProfiles[0],{safeMarginInches:.4},2);assert.notEqual(v2.id,project.productionProfiles[0].id);assert.equal(v2.safeMarginInches,.4);assert.match(v2.notes.at(-1),/revision 2/);});

test('scoped artifacts contain only the approved production document and retain its revision/profile lineage',async()=>{const dir=await mkdtemp(join(tmpdir(),'forge-scoped-'));try{const store=new FileSpecializedCreationStore(join(dir,'specialized.json'));let project=createSpecializedOfficeProject({id:'fold-scope',forgeProjectId:'forge',mode:'greeting-card',title:'Fold Scope',brief:'Scoped artifact'});project={...project,modeData:{occasion:'thanks',tone:'warm',message:'Thank you.'}};const source=composeSpecializedProject(project),flatProfile=foldedCardImpositionProfile(project.productionProfiles[0]),imposed=createFoldedCardImpositionDocument(project,source,'2026-09-01T06:00:00.000Z');const now='2026-09-01T06:00:00.000Z';project={...project,documents:[source,imposed],productionProfiles:[...project.productionProfiles,flatProfile],revisions:[{id:`${source.id}:r1`,projectId:project.id,documentId:source.id,sequence:1,reason:'source',actor:'author',document:source,createdAt:now},{id:`${imposed.id}:r1`,projectId:project.id,documentId:imposed.id,sequence:1,reason:'imposition',actor:'author',document:imposed,createdAt:now}],updatedAt:now};await store.create(project);const service=new SpecializedCreationScopedArtifactService(store);const result=await service.render({forgeProjectId:'forge',specializedProjectId:'fold-scope',documentIds:[imposed.id],profileId:flatProfile.id,kind:'pdf',now:'2026-09-01T06:01:00.000Z'});assert.equal(result.artifact.pageCount,2);assert.deepEqual(result.artifact.sourceDocumentIds,[imposed.id]);assert.equal(Buffer.from(result.artifact.bytesBase64,'base64').subarray(0,5).toString(),'%PDF-');assert.equal(result.project.artifacts[0].profileId,flatProfile.id);assert.equal(result.project.artifacts[0].revisionId,`${imposed.id}:r1`);}finally{await rm(dir,{recursive:true,force:true});}});
