const test=require('node:test');
const assert=require('node:assert/strict');
const {mkdtemp,rm}=require('node:fs/promises');
const {tmpdir}=require('node:os');
const {join}=require('node:path');
const {FileSpecializedCreationStore}=require('../dist/infrastructure/file-specialized-creation-store.js');
const {ProjectMemoryStore}=require('../dist/application/project-memory-store.js');
const {SpecializedCreationOfficeService}=require('../dist/application/specialized-creation-office-service.js');
const {SpecializedCreationAiAssetService}=require('../dist/application/specialized-creation-ai-assets.js');
const {createTcgGameStarterData,upsertTcgCharacterEvolutionLine,upsertTcgWorldMap,tcgGameFramework}=require('../dist/application/specialized-creation-tcg-design.js');

const image=async request=>({provider:'openai',model:'gpt-image-2',mimeType:'image/png',bytesBase64:'iVBORw0KGgo=',dataUri:'data:image/png;base64,iVBORw0KGgo=',requestId:'req-image-059',size:request.size||'1024x1024',quality:request.quality||'medium'});
const line={id:'hero-line',name:'Nova',characterBibleId:'character-nova',speciesOrArchetype:'Star guardian',biography:'A guardian growing into cosmic power.',stages:[{id:'nova-birth',label:'Star Child',stageIndex:0,lifeStage:'birth',description:'A newborn star guardian.',appearance:'Small luminous child with silver eyes.',strengths:['curiosity'],weaknesses:['fragility'],magicalPowers:[{id:'glow',name:'Glow',kind:'magical',description:'Emits guiding light.',rank:1,tags:['light']}],physicalPowers:[{id:'step',name:'Quick Step',kind:'physical',description:'Moves quickly.',rank:1,tags:['speed']}],territoryIds:['nursery'],artworkAssetIds:[]},{id:'nova-final',label:'Astral Regent',stageIndex:1,lifeStage:'final-evolution',description:'The completed guardian.',appearance:'Tall armored guardian surrounded by a star halo.',strengths:['leadership'],weaknesses:['void'],magicalPowers:[{id:'nova',name:'Nova Crown',kind:'magical',description:'Creates a stellar shield.',rank:5,tags:['light','shield']}],physicalPowers:[{id:'strike',name:'Meteor Strike',kind:'physical',description:'Heavy impact attack.',rank:4,tags:['combat']}],territoryIds:['citadel'],artworkAssetIds:[]}]};
const map={id:'world',name:'Astral World',description:'A linked two-territory world.',territories:[{id:'nursery',name:'Star Nursery',description:'Birthplace.',biome:'nebula',tags:['birth'],center:{x:.2,y:.7},adjacentTerritoryIds:['citadel'],characterStageRefs:[{characterLineId:'hero-line',stageId:'nova-birth'}],resources:['stardust'],hazards:['flare']},{id:'citadel',name:'Astral Citadel',description:'Final stronghold.',biome:'orbital fortress',tags:['capital'],center:{x:.8,y:.2},adjacentTerritoryIds:['nursery'],characterStageRefs:[{characterLineId:'hero-line',stageId:'nova-final'}],resources:['core crystal'],hazards:['void rift']}]};

async function fixture(){const dir=await mkdtemp(join(tmpdir(),'forge-tcg-ai-'));const store=new FileSpecializedCreationStore(join(dir,'specialized.json'));const memory=new ProjectMemoryStore();const office=new SpecializedCreationOfficeService(store,memory,undefined,async()=>{throw new Error('text AI not used');});let project=await office.create({id:'tcg-ai',forgeProjectId:'forge',mode:'trading-card-game',title:'AI TCG',brief:'Build an original character progression game'});let data=createTcgGameStarterData({gameTitle:'Astral Forge',setId:'AF1',setName:'Origins'});data=upsertTcgCharacterEvolutionLine(data,line);data=upsertTcgWorldMap(data,map);project=await office.setModeData('forge','tcg-ai',data);const assets=new SpecializedCreationAiAssetService(store,memory,image);return{dir,store,memory,office,assets};}

test('generated TCG stage art is an unapproved candidate until author locks it',async()=>{const fx=await fixture();try{const generated=await fx.assets.generateTcgStageArtwork({forgeProjectId:'forge',specializedProjectId:'tcg-ai',lineId:'hero-line',stageId:'nova-final',styleDirection:'original painted fantasy card art'});assert.equal(generated.asset.approved,false);assert.equal(generated.asset.provider,'openai');assert.equal(generated.asset.model,'gpt-image-2');assert.equal(generated.asset.requestId,'req-image-059');let framework=tcgGameFramework(generated.project.modeData);let stage=framework.characterLines[0].stages.find(item=>item.id==='nova-final');assert.ok(stage.artworkAssetIds.includes(generated.asset.id));assert.equal(stage.approvedArtworkAssetId,undefined);const approved=await fx.assets.approveTcgStageArtwork({forgeProjectId:'forge',specializedProjectId:'tcg-ai',lineId:'hero-line',stageId:'nova-final',assetId:generated.asset.id});stage=tcgGameFramework(approved.modeData).characterLines[0].stages.find(item=>item.id==='nova-final');assert.equal(stage.approvedArtworkAssetId,generated.asset.id);assert.equal(approved.assets.find(item=>item.id===generated.asset.id).approved,true);}finally{await rm(fx.dir,{recursive:true,force:true});}});

test('AI map art remains separate from canonical territory topology until approval',async()=>{const fx=await fixture();try{const generated=await fx.assets.generateTcgWorldMapArtwork({forgeProjectId:'forge',specializedProjectId:'tcg-ai',mapId:'world'});assert.equal(generated.asset.approved,false);assert.equal(tcgGameFramework(generated.project.modeData).worldMaps[0].artworkAssetId,undefined);const approved=await fx.assets.approveTcgWorldMapArtwork({forgeProjectId:'forge',specializedProjectId:'tcg-ai',mapId:'world',assetId:generated.asset.id});const approvedMap=tcgGameFramework(approved.modeData).worldMaps[0];assert.equal(approvedMap.artworkAssetId,generated.asset.id);assert.deepEqual(approvedMap.territories.map(t=>t.id),['nursery','citadel']);}finally{await rm(fx.dir,{recursive:true,force:true});}});
