const test=require('node:test');
const assert=require('node:assert/strict');
const {createSpecializedOfficeProject}=require('../dist/domain/specialized-creation-office.js');
const {composeSpecializedProject}=require('../dist/application/specialized-creation-mode-composer.js');
const {SpecializedCreationProductionEngine}=require('../dist/application/specialized-creation-production-engine.js');
const {specializedProductionSafetyIssues,prepareSpecializedProjectForArtifact,normalizePdfText}=require('../dist/application/specialized-creation-production-safety.js');

function invitationProject(qrDestination){let project=createSpecializedOfficeProject({id:'invite-safe',forgeProjectId:'forge',mode:'invitation',title:'Invitation',brief:'Safety test'});project={...project,modeData:{eventType:'Launch',primaryNames:['Author’s Forge'],date:'2026-09-15',startTime:'18:00',venue:'Forge Hall',address:'100 Main Street',rsvpMethod:'example.test/rsvp',...(qrDestination?{qrDestination}: {})}};const doc=composeSpecializedProject(project);return {...project,documents:[doc]};}

test('valid QR production emits encoded modules while undersized QR fails closed',()=>{const project=invitationProject('https://example.test/rsvp'),profile=project.productionProfiles[0];const issues=specializedProductionSafetyIssues(project,'svg',profile);assert.equal(issues.some(issue=>issue.code==='QR_RENDERER_UNAVAILABLE'),false);assert.equal(issues.some(issue=>issue.code.startsWith('QR_')&&issue.severity==='error'),false);assert.doesNotThrow(()=>prepareSpecializedProjectForArtifact(project,'svg',profile));const artifact=new SpecializedCreationProductionEngine().render(project,profile,'svg');const svg=Buffer.from(artifact.bytesBase64,'base64').toString('utf8');assert.match(svg,/aria-label="QR code for https:\/\/example\.test\/rsvp"/);assert.ok((svg.match(/<rect/g)||[]).length>100,'QR SVG must contain encoded module geometry, not a decorative placeholder.');const document=project.documents[0],surface=document.surfaces[0],tinyElements=surface.elements.map(element=>element.kind==='qr'?{...element,box:{...element.box,width:0.15,height:0.15}}:element),tiny={...project,documents:[{...document,surfaces:[{...surface,elements:tinyElements},...document.surfaces.slice(1)]}]};const tinyIssues=specializedProductionSafetyIssues(tiny,'svg',profile);assert.ok(tinyIssues.some(issue=>issue.code==='QR_MODULE_TOO_SMALL'&&issue.severity==='error'));assert.throws(()=>prepareSpecializedProjectForArtifact(tiny,'svg',profile),/QR_MODULE_TOO_SMALL/);});

test('common typographic punctuation is normalized deterministically for the built-in PDF font',()=>{assert.equal(normalizePdfText('Author’s “Forge”—ready… © 2026'),'Author\'s "Forge"--ready... (c) 2026');const project=invitationProject();const prepared=prepareSpecializedProjectForArtifact(project,'pdf');const names=prepared.documents[0].surfaces[0].elements.find(e=>e.id==='invite-names');assert.equal(names.text,"Author's Forge");});

test('unsupported non-Latin PDF glyphs block rather than silently changing to question marks',()=>{let project=createSpecializedOfficeProject({id:'unicode',forgeProjectId:'forge',mode:'flyer',title:'Unicode',brief:'Glyph safety'});project={...project,modeData:{objective:'Announce',audience:'Readers',headline:'こんにちは',details:'Details',primaryCta:'Read',destination:'example.test',secondaryActions:[]}};project={...project,documents:[composeSpecializedProject(project)]};const issues=specializedProductionSafetyIssues(project,'pdf');assert.ok(issues.some(issue=>issue.code==='PDF_UNSUPPORTED_GLYPHS'&&issue.severity==='error'));assert.throws(()=>prepareSpecializedProjectForArtifact(project,'pdf'),/PDF_UNSUPPORTED_GLYPHS/);const svgPrepared=prepareSpecializedProjectForArtifact(project,'svg');assert.equal(svgPrepared.documents[0].surfaces[0].elements.find(e=>e.id==='flyer-headline').text,'こんにちは');});

test('TCG drafts may be incomplete but production blocks unresolved character-to-territory links',()=>{let project=createSpecializedOfficeProject({id:'tcg-world-safety',forgeProjectId:'forge',mode:'trading-card-game',title:'World Safety',brief:'Draft then validate'});project={...project,modeData:{gameTitle:'Forge Realms',setId:'FR1',setName:'First Spark',fields:[{key:'name',label:'Name',type:'text',required:true},{key:'type',label:'Type',type:'text',required:true},{key:'rules',label:'Rules',type:'text',required:true}],templates:[{id:'base',name:'Base',tokens:{frame:'plain'}}],cards:[],playtestSnapshots:[],gameFramework:{premise:'Draft world',playerGoal:'Build a realm',victoryConditions:[],turnStructure:[],zones:[],resources:[],cardTypes:[],keywords:[],factions:[],designNotes:[],worldMaps:[],characterLines:[{id:'hero',name:'Hero',biography:'Original guardian.',stages:[{id:'origin',label:'Origin',stageIndex:0,lifeStage:'birth',description:'Begins here.',appearance:'Small guardian.',strengths:[],weaknesses:[],magicalPowers:[],physicalPowers:[],territoryIds:['not-created-yet'],artworkAssetIds:[]}]}]}}};assert.doesNotThrow(()=>require('../dist/domain/specialized-creation-office.js').validateModeData('trading-card-game',project.modeData));const issues=specializedProductionSafetyIssues(project,'json',project.productionProfiles[0]);assert.ok(issues.some(issue=>issue.code==='TCG_WORLD_REFERENCES_UNRESOLVED'&&issue.severity==='error'));assert.throws(()=>prepareSpecializedProjectForArtifact(project,'json',project.productionProfiles[0]),/TCG_WORLD_REFERENCES_UNRESOLVED/);});
