const test=require('node:test');
const assert=require('node:assert/strict');
const {createSpecializedOfficeProject,defaultProductionProfile,validateModeData}=require('../dist/domain/specialized-creation-office.js');

test('comic standard profile advertises same-revision high-resolution PNG production',()=>{const profile=defaultProductionProfile('comic-book');assert.deepEqual(profile.artifactKinds,['pdf','cbz','svg','png']);assert.equal(profile.dpi,300);assert.equal(profile.widthInches,6.625);assert.equal(profile.heightInches,10.25);const empty=createSpecializedOfficeProject({id:'comic',forgeProjectId:'forge',mode:'comic-book',title:'Comic',brief:'Brief'});assert.equal(empty.modeData.readingDirection,'ltr');});

test('TCG field schema enforces runtime types and enum values',()=>{const base={gameTitle:'Forge Realms',setId:'FR1',setName:'First Spark',fields:[{key:'name',label:'Name',type:'text',required:true},{key:'cost',label:'Cost',type:'number',required:true},{key:'foil',label:'Foil',type:'boolean',required:true},{key:'rarity',label:'Rarity',type:'enum',required:true,values:['common','rare']}],templates:[{id:'base',name:'Base',tokens:{}}],cards:[{id:'c1',collectorNumber:'001',templateId:'base',fields:{name:'Smith',cost:2,foil:false,rarity:'rare'}}],playtestSnapshots:[]};assert.doesNotThrow(()=>validateModeData('trading-card-game',base));assert.throws(()=>validateModeData('trading-card-game',{...base,cards:[{...base.cards[0],fields:{...base.cards[0].fields,cost:'2'}}]}),/must be a finite number/);assert.throws(()=>validateModeData('trading-card-game',{...base,cards:[{...base.cards[0],fields:{...base.cards[0].fields,rarity:'mythic'}}]}),/must be one of/);});

test('TCG template inheritance rejects missing parents and cycles before production',()=>{const shell={gameTitle:'Forge Realms',setId:'FR1',setName:'First Spark',fields:[],cards:[],playtestSnapshots:[]};assert.throws(()=>validateModeData('trading-card-game',{...shell,templates:[{id:'child',name:'Child',parentId:'missing',tokens:{}}]}),/missing parent/);assert.throws(()=>validateModeData('trading-card-game',{...shell,templates:[{id:'a',name:'A',parentId:'b',tokens:{}},{id:'b',name:'B',parentId:'a',tokens:{}}]}),/inheritance cycle/);});
