const test=require("node:test");const assert=require("node:assert/strict");const f=require("../.forge-build");
const snap=(id,chapters,label="draft-1")=>f.createBookSnapshot({id,projectId:"p",bookId:"b",label,name:id,createdAt:"2026-08-27T00:00:00.000Z",manuscript:Object.values(chapters).join("\n"),chapters});
test("Mission 025 versions compare, restore, branch, and merge without mutating snapshots",()=>{const a=snap("a",{"4":"North shoreline","5":"Rain"}),b=snap("b",{"4":"Old watchtower","5":"Rain"},"final");const c=f.compareBookVersions(a,b);assert.equal(c.changedChapterCount,1);assert.equal(c.changes[0].chapterId,"4");assert.equal(f.rollbackVersion({projectId:"p",bookId:"b",versions:[a,b],branches:[]},"a").chapters["4"],"North shoreline");const h={projectId:"p",bookId:"b",versions:[a,b],branches:[]};const branch=f.branchVersion(h,{name:"experimental",baseVersionId:"b"});assert.equal(branch.headVersionId,"b");const merged=f.mergeVersions(b,snap("c",{"4":"Old watchtower","5":"Thunder"}),b);assert.equal(merged.chapters["5"],"Thunder");assert.equal(b.chapters["5"],"Rain");});
test("Mission 025 detects three-way merge conflicts",()=>{const base=snap("base",{"4":"A"}),target=snap("target",{"4":"B"}),source=snap("source",{"4":"C"});assert.throws(()=>f.mergeVersions(target,source,base),/Merge conflict in chapter/);});
test("Mission 026 author override and canon lock take precedence over AI states",()=>{const svc=new f.AuthorControlService("p");svc.suggest("chapter-4","AI version","Recommendation");svc.draft("chapter-4","AI draft","Draft");const override=svc.override("chapter-4","Author truth","Forget the recommendation. This is canon.");assert.equal(override.status,"author-override");assert.equal(svc.resolve("chapter-4").content,"Author truth");const lock=svc.lock("chapter-4","Locked truth");assert.equal(lock.status,"canon-locked");assert.equal(f.isCanonLocked(svc.history(),"p","chapter-4"),true);});
test("Mission 027 maintains shared series canon across books",()=>{let s=f.createSeries({id:"s",projectId:"p",name:"The Kingdom",bookIds:["b1"],sharedCharacters:["hero"],worldRules:["magic has a cost"],visualIdentityIds:["hero-visual"],locations:["Old City"],terminology:["The Veil"],history:["The founding war"],unresolvedThreads:["Who opened the gate?"]});s=f.addBookToSeries(s,"b2");s=f.addSeriesTimelineEvent(s,{id:"e1",bookId:"b2",date:"2028-01-01",description:"The gate opens"});assert.deepEqual(s.bookIds,["b1","b2"]);assert.equal(s.sharedCharacters[0],"hero");assert.equal(s.timeline[0].bookId,"b2");});
const sample=Array.from({length:80},(_,i)=>`The old road carried ${i} travelers through the quiet valley, and each evening the lanterns burned beside the river.`).join(" ");
test("Mission 028 analyzes a reusable author voice fingerprint and builds a provider-facing rewrite brief",()=>{const profile=f.createVoiceProfile({id:"voice-1",projectId:"p",authorId:"author-1",text:sample});assert.ok(profile.fingerprint.sentenceLengthMean>0);const comparison=f.compareVoiceToProfile(sample,profile.fingerprint);assert.equal(comparison.withinProfile,true);const brief=f.buildVoiceRewriteBrief({source:"Rewrite this passage.",instruction:"more-literary",profile:profile.fingerprint});assert.match(brief,/author's established voice fingerprint/);assert.match(brief,/more-literary/);});
test("Mission 028 rejects insufficient samples rather than inventing a voice",()=>{assert.throws(()=>f.analyzeVoice("Too short."),/At least 20 words/);});
