import type { VoiceFingerprint } from "./voice-preservation";
import { analyzeVoice, compareVoiceToProfile } from "./voice-preservation";

export const AUTHOR_VOICE_MEMORY_FORMAT_VERSION = 3 as const;
export interface VoiceMemorySample { readonly id:string; readonly label:string; readonly text:string; readonly fingerprint:VoiceFingerprint; readonly approved:boolean; readonly weight:number; readonly source:"author"|"approved-manuscript"; readonly genre?:string; readonly purpose?:"prose"|"dialogue"|"description"|"narration"|"other"; }
export interface VoiceDimensionScores { readonly sentenceRhythm:number; readonly vocabulary:number; readonly dialogue:number; readonly description:number; readonly emotionalIntensity:number; readonly narrativeDistance:number; }
export interface VoiceMemoryEvolutionEvent { readonly id:string; readonly at:string; readonly type:"sample-added"|"sample-removed"|"canonical-set"; readonly sampleIds:readonly string[]; readonly reason:string; }
export interface AuthorVoiceMemory { readonly formatVersion:typeof AUTHOR_VOICE_MEMORY_FORMAT_VERSION; readonly id:string; readonly projectId:string; readonly authorId:string; readonly samples:readonly VoiceMemorySample[]; readonly canonicalSampleIds:readonly string[]; readonly fingerprint:VoiceFingerprint; readonly dimensions:VoiceDimensionScores; readonly evolution:readonly VoiceMemoryEvolutionEvent[]; readonly createdAt:string; readonly updatedAt:string; }
export interface VoiceDriftReport { readonly distance:number; readonly withinProfile:boolean; readonly confidence:"low"|"medium"|"high"; readonly matchedSamples:readonly string[]; readonly warnings:readonly string[]; readonly dimensions:VoiceDimensionScores; readonly recommendations:readonly string[]; }
const numericKeys=["sentenceLengthMean","sentenceLengthMedian","punctuationRate","dialogueRatio","vocabularyRichness","paragraphLengthMean","descriptionDensity","metaphorDensity","pacing","emotionalIntensity"] as const;
const weightedAverage=(values:readonly{value:number;weight:number}[])=>{const total=values.reduce((s,x)=>s+x.weight,0);return total?values.reduce((s,x)=>s+x.value*x.weight,0)/total:0;};
function aggregate(samples:readonly VoiceMemorySample[]):VoiceFingerprint{const approved=samples.filter(s=>s.approved&&s.weight>0);if(!approved.length)throw new Error("At least one approved weighted voice sample is required.");const result=Object.fromEntries(numericKeys.map(k=>[k,weightedAverage(approved.map(s=>({value:s.fingerprint[k],weight:s.weight})))])) as Record<(typeof numericKeys)[number],number>;const distanceRank=[...approved].sort((a,b)=>b.weight-a.weight);return{...result,narrativeDistance:distanceRank[0].fingerprint.narrativeDistance,sampleWordCount:approved.reduce((s,x)=>s+x.fingerprint.sampleWordCount,0)};}
function dimensions(f:VoiceFingerprint):VoiceDimensionScores{return{sentenceRhythm:Math.min(1,f.sentenceLengthMean/40),vocabulary:Math.min(1,f.vocabularyRichness),dialogue:Math.min(1,f.dialogueRatio),description:Math.min(1,f.descriptionDensity),emotionalIntensity:Math.min(1,f.emotionalIntensity),narrativeDistance:f.narrativeDistance==="first-person"?0.2:f.narrativeDistance==="second-person"?0.4:f.narrativeDistance==="third-person"?0.8:0.6};}
const toSample=(s:{id:string;label:string;text:string;approved?:boolean;weight?:number;source?:"author"|"approved-manuscript";genre?:string;purpose?:VoiceMemorySample["purpose"]}):VoiceMemorySample=>({...s,fingerprint:analyzeVoice(s.text).profile,approved:s.approved??true,weight:s.weight??1,source:s.source??"author"});
const event=(type:VoiceMemoryEvolutionEvent["type"],sampleIds:readonly string[],reason:string):VoiceMemoryEvolutionEvent=>({id:`voice-event-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,at:new Date().toISOString(),type,sampleIds:[...sampleIds],reason});
function nextTimestamp(previous:string):string{const now=Date.now(),prior=Date.parse(previous);return new Date(Number.isFinite(prior)&&now<=prior?prior+1:now).toISOString();}
export function createAuthorVoiceMemory(input:{id?:string;projectId:string;authorId:string;samples:readonly{id:string;label:string;text:string;approved?:boolean;weight?:number;source?:"author"|"approved-manuscript";genre?:string;purpose?:VoiceMemorySample["purpose"]}[];canonicalSampleIds?:readonly string[];createdAt?:string;updatedAt?:string}):AuthorVoiceMemory{const samples=input.samples.map(toSample),fingerprint=aggregate(samples),canonicalSampleIds=[...(input.canonicalSampleIds??samples.filter(s=>s.approved).map(s=>s.id))].filter(id=>samples.some(s=>s.id===id));return{formatVersion:AUTHOR_VOICE_MEMORY_FORMAT_VERSION,id:input.id??`author-voice-${Date.now()}`,projectId:input.projectId,authorId:input.authorId,samples,canonicalSampleIds,fingerprint,dimensions:dimensions(fingerprint),evolution:[event("canonical-set",canonicalSampleIds,"Initial approved author voice corpus")],createdAt:input.createdAt??new Date().toISOString(),updatedAt:input.updatedAt??new Date().toISOString()};}
export function updateAuthorVoiceMemory(memory:AuthorVoiceMemory,input:{addSamples?:readonly{id:string;label:string;text:string;approved?:boolean;weight?:number;source?:"author"|"approved-manuscript";genre?:string;purpose?:VoiceMemorySample["purpose"]}[];removeSampleIds?:readonly string[];canonicalSampleIds?:readonly string[];reason?:string}):AuthorVoiceMemory{const removed=new Set(input.removeSampleIds??[]),additions=(input.addSamples??[]).filter(s=>!removed.has(s.id)).map(toSample),samples=[...memory.samples.filter(s=>!removed.has(s.id)&&!additions.some(a=>a.id===s.id)),...additions],fingerprint=aggregate(samples),canonicalSampleIds=[...(input.canonicalSampleIds??memory.canonicalSampleIds)].filter(id=>samples.some(s=>s.id===id)),reason=input.reason??"Author voice memory updated by explicit author-approved corpus change";const evolution=[...memory.evolution];if(additions.length)evolution.push(event("sample-added",additions.map(s=>s.id),reason));if(removed.size)evolution.push(event("sample-removed",[...removed],reason));if(input.canonicalSampleIds)evolution.push(event("canonical-set",canonicalSampleIds,reason));return{...memory,formatVersion:AUTHOR_VOICE_MEMORY_FORMAT_VERSION,samples,canonicalSampleIds,fingerprint,dimensions:dimensions(fingerprint),evolution,updatedAt:nextTimestamp(memory.updatedAt)};}
export function assessVoiceDrift(text:string,memory:AuthorVoiceMemory):VoiceDriftReport{const comparison=compareVoiceToProfile(text,memory.fingerprint),matchedSamples=memory.samples.filter(s=>s.approved).map(s=>({id:s.id,distance:compareVoiceToProfile(text,s.fingerprint).distance})).sort((a,b)=>a.distance-b.distance).slice(0,3).map(s=>s.id),analysisDimensions=dimensions(comparison.analysis.profile),warnings:string[]=[],recommendations:string[]=[];if(comparison.distance>0.35){warnings.push("Draft voice is materially outside the author's approved voice profile.");recommendations.push("Revise against the nearest approved voice samples before applying the draft.");}if(comparison.analysis.profile.narrativeDistance!==memory.fingerprint.narrativeDistance){warnings.push("Narrative distance differs from the canonical author voice profile.");recommendations.push("Check POV, narrative intimacy, and internal-thought density.");}if(comparison.analysis.profile.sentenceLengthMean>memory.fingerprint.sentenceLengthMean*1.35||comparison.analysis.profile.sentenceLengthMean<memory.fingerprint.sentenceLengthMean*0.65){warnings.push("Sentence rhythm materially differs from the author's reference corpus.");recommendations.push("Restore the author's established sentence rhythm where meaning permits.");}if(Math.abs(analysisDimensions.dialogue-memory.dimensions.dialogue)>0.3)recommendations.push("Check dialogue density against the author's approved corpus.");if(Math.abs(analysisDimensions.description-memory.dimensions.description)>0.3)recommendations.push("Check descriptive density against the author's approved corpus.");return{distance:comparison.distance,withinProfile:comparison.withinProfile,confidence:memory.fingerprint.sampleWordCount>=5000?"high":memory.fingerprint.sampleWordCount>=1000?"medium":"low",matchedSamples,warnings,dimensions:analysisDimensions,recommendations:[...new Set(recommendations)]};}
export function buildAuthorVoiceContext(memory:AuthorVoiceMemory):string{return["AUTHOR VOICE MEMORY — canonical reference corpus",`Approved samples: ${memory.samples.filter(s=>memory.canonicalSampleIds.includes(s.id)).length}; reference words: ${memory.fingerprint.sampleWordCount}.`,`Narrative distance: ${memory.fingerprint.narrativeDistance}. Sentence length mean: ${memory.fingerprint.sentenceLengthMean.toFixed(1)}.`,`Dialogue ratio: ${memory.fingerprint.dialogueRatio.toFixed(2)}. Vocabulary richness: ${memory.fingerprint.vocabularyRichness.toFixed(2)}.`,`Description density: ${memory.fingerprint.descriptionDensity.toFixed(2)}. Metaphor density: ${memory.fingerprint.metaphorDensity.toFixed(2)}.`,"Treat this as a preservation constraint, not an instruction to imitate another author. Draft in the author's established patterns while preserving canon, character state, continuity, meaning, and author intent."].join("\n");}
