export const AUTHOR_MARKETING_CALENDAR_FORMAT_VERSION=1 as const;
export const CAMPAIGN_PHASES=["preorder","release-day","post-launch","30-day","60-day","90-day"] as const;
export type CampaignPhase=typeof CAMPAIGN_PHASES[number];
export interface CalendarEntry {readonly id:string;readonly projectId:string;readonly phase:CampaignPhase;readonly date:string;readonly channel:string;readonly marketingAssetId:string;readonly purpose:string;readonly status:"planned"|"scheduled"|"completed";}
export interface AuthorMarketingCalendar {readonly formatVersion:typeof AUTHOR_MARKETING_CALENDAR_FORMAT_VERSION;readonly id:string;readonly projectId:string;readonly startDate:string;readonly entries:readonly CalendarEntry[];readonly createdAt:string;readonly updatedAt:string;}
export interface CreateCalendarInput {readonly id:string;readonly projectId:string;readonly startDate:string;readonly entries:readonly CalendarEntry[];readonly now?:string;}
const text=(v:string,label:string)=>{if(typeof v!=="string"||!v.trim())throw new Error(`${label} is required.`);return v.trim();};
const date=(v:string,label:string)=>{text(v,label);if(Number.isNaN(Date.parse(v)))throw new Error(`${label} must be an ISO date/time.`);return v;};
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
export function validateAuthorMarketingCalendar(c:AuthorMarketingCalendar):AuthorMarketingCalendar {if(c.formatVersion!==1)throw new Error("Unsupported marketing calendar format version.");text(c.id,"Calendar id");text(c.projectId,"Project id");date(c.startDate,"Start date");text(c.createdAt,"Created at");text(c.updatedAt,"Updated at");const ids=new Set<string>();for(const e of c.entries){text(e.id,"Calendar entry id");if(ids.has(e.id))throw new Error(`Duplicate calendar entry id \"${e.id}\`.`);ids.add(e.id);if(e.projectId!==c.projectId)throw new Error(`Calendar entry \"${e.id}\" belongs to another project.`);if(!(CAMPAIGN_PHASES as readonly string[]).includes(e.phase))throw new Error(`Unsupported campaign phase \"${e.phase}\`.`);date(e.date,"Entry date");text(e.channel,"Channel");text(e.marketingAssetId,"Marketing asset id");text(e.purpose,"Purpose");if(!["planned","scheduled","completed"].includes(e.status))throw new Error(`Unsupported calendar status \"${e.status}\`.`);}return clone(c);}
export function createAuthorMarketingCalendar(i:CreateCalendarInput):AuthorMarketingCalendar {const now=i.now??new Date().toISOString();return validateAuthorMarketingCalendar({formatVersion:1,id:text(i.id,"Calendar id"),projectId:text(i.projectId,"Project id"),startDate:date(i.startDate,"Start date"),entries:i.entries.map(e=>({...e})),createdAt:now,updatedAt:now});}
export function addCalendarEntries(c:AuthorMarketingCalendar,entries:readonly CalendarEntry[],now=new Date().toISOString()):AuthorMarketingCalendar{return validateAuthorMarketingCalendar({...c,entries:[...c.entries,...entries.map(e=>({...e}))],updatedAt:now});}
export function buildLaunchCalendar(projectId:string,id:string,startDate:string,assetIds:readonly string[],now=new Date().toISOString()):AuthorMarketingCalendar {text(projectId,"Project id");date(startDate,"Start date");if(!assetIds.length)throw new Error("At least one marketing asset is required.");const start=Date.parse(startDate);const phases:readonly [CampaignPhase,number][]=[["preorder",-14],["release-day",0],["post-launch",7],["30-day",30],["60-day",60],["90-day",90]];const entries=assetIds.map((assetId,i)=>{const [phase,offset]=phases[i%phases.length];return{id:`${id}-entry-${i+1}`,projectId,phase,date:new Date(start+offset*86400000).toISOString(),channel:"multi-channel",marketingAssetId:text(assetId,"Marketing asset id"),purpose:`${phase} promotional activity`,status:"planned" as const};});return createAuthorMarketingCalendar({id,projectId,startDate,entries,now});}