export const AUTHOR_CONTROL_FORMAT_VERSION = 1 as const;
export type AuthorDecisionStatus = "ai-suggestion"|"ai-draft"|"author-approved"|"canon-locked"|"author-override";
export interface AuthorDecision { readonly id:string; readonly projectId:string; readonly targetId:string; readonly status:AuthorDecisionStatus; readonly content:string; readonly reason:string; readonly createdAt:string; readonly supersedesId?:string; }
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
const req=(v:string,n:string)=>{if(typeof v!=="string"||!v.trim())throw new Error(`${n} is required.`);return v.trim();};
export function createAuthorDecision(input:Omit<AuthorDecision,"id">&{id?:string}):AuthorDecision{req(input.projectId,"Project id");req(input.targetId,"Target id");req(input.content,"Decision content");req(input.reason,"Decision reason");return clone({...input,id:input.id??`decision_${Date.now()}_${Math.random().toString(36).slice(2,9)}`});}
export function validateAuthorDecision(v:AuthorDecision):AuthorDecision{req(v.id,"Decision id");req(v.projectId,"Project id");req(v.targetId,"Target id");req(v.content,"Decision content");if(!["ai-suggestion","ai-draft","author-approved","canon-locked","author-override"].includes(v.status))throw new Error("Invalid author decision status.");return clone(v);}
export function applyAuthorOverride(decisions:readonly AuthorDecision[],input:{id?:string;projectId:string;targetId:string;content:string;reason:string;createdAt?:string}):AuthorDecision[]{const prior=decisions.filter(d=>d.projectId===input.projectId&&d.targetId===input.targetId);const latest=prior.at(-1);const next=createAuthorDecision({id:input.id,projectId:input.projectId,targetId:input.targetId,status:"author-override",content:input.content,reason:input.reason,createdAt:input.createdAt??new Date().toISOString(),supersedesId:latest?.id});return[...decisions.map(validateAuthorDecision),next];}
export function lockCanon(decisions:readonly AuthorDecision[],input:{id?:string;projectId:string;targetId:string;content:string;reason?:string;createdAt?:string}):AuthorDecision[]{const next=createAuthorDecision({id:input.id,projectId:input.projectId,targetId:input.targetId,status:"canon-locked",content:input.content,reason:input.reason??"Author locked this state as canon.",createdAt:input.createdAt??new Date().toISOString(),supersedesId:decisions.filter(d=>d.projectId===input.projectId&&d.targetId===input.targetId).at(-1)?.id});return[...decisions.map(validateAuthorDecision),next];}
export function resolveAuthorControl(decisions:readonly AuthorDecision[],projectId:string,targetId:string):AuthorDecision|undefined{return decisions.filter(d=>d.projectId===projectId&&d.targetId===targetId).map(validateAuthorDecision).at(-1);}
export function isCanonLocked(decisions:readonly AuthorDecision[],projectId:string,targetId:string):boolean{return resolveAuthorControl(decisions,projectId,targetId)?.status==="canon-locked";}
