export const BOOK_VERSION_CONTROL_FORMAT_VERSION = 1 as const;
export type BookVersionLabel = "draft-1" | "draft-2" | "draft-3" | "final" | "published" | "custom";
export interface BookSnapshot { readonly id:string; readonly projectId:string; readonly bookId:string; readonly label:BookVersionLabel; readonly name:string; readonly createdAt:string; readonly manuscript:string; readonly chapters:Readonly<Record<string,string>>; readonly parentId?:string; }
export interface VersionChange { readonly chapterId:string; readonly kind:"added"|"removed"|"changed"; readonly before?:string; readonly after?:string; }
export interface BookVersionComparison { readonly fromId:string; readonly toId:string; readonly changes:readonly VersionChange[]; readonly changedChapterCount:number; readonly identical:boolean; }
export interface BookVersionBranch { readonly id:string; readonly projectId:string; readonly bookId:string; readonly name:string; readonly baseVersionId:string; readonly headVersionId:string; readonly createdAt:string; }
export interface BookVersionHistory { readonly projectId:string; readonly bookId:string; readonly versions:readonly BookSnapshot[]; readonly branches:readonly BookVersionBranch[]; }
const req=(v:string,n:string)=>{if(typeof v!=="string"||!v.trim())throw new Error(`${n} is required.`);return v.trim();};
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
export function createBookSnapshot(input:Omit<BookSnapshot,"id">&{id?:string}):BookSnapshot{return clone({...input,id:input.id??cryptoId()});}
export function validateBookSnapshot(v:BookSnapshot):BookSnapshot{req(v.id,"Version id");req(v.projectId,"Project id");req(v.bookId,"Book id");req(v.name,"Version name");req(v.createdAt,"Version createdAt");if(!Array.isArray(v.chapters)&&typeof v.chapters!=="object")throw new Error("Version chapters are required.");return clone(v);}
export function compareBookVersions(from:BookSnapshot,to:BookSnapshot):BookVersionComparison{if(from.projectId!==to.projectId||from.bookId!==to.bookId)throw new Error("Versions must belong to the same project and book.");const keys=new Set([...Object.keys(from.chapters),...Object.keys(to.chapters)]);const changes:VersionChange[]=[];for(const chapterId of [...keys].sort()){const before=from.chapters[chapterId],after=to.chapters[chapterId];if(before===undefined)changes.push({chapterId,kind:"added",after});else if(after===undefined)changes.push({chapterId,kind:"removed",before});else if(before!==after)changes.push({chapterId,kind:"changed",before,after});}return{fromId:from.id,toId:to.id,changes,changedChapterCount:changes.length,identical:changes.length===0};}
export function rollbackVersion(history:BookVersionHistory,versionId:string):BookSnapshot{const v=history.versions.find(x=>x.id===versionId);if(!v)throw new Error(`Version "${versionId}" was not found.`);return clone(v);}
export function branchVersion(history:BookVersionHistory,input:{id?:string;name:string;baseVersionId:string;createdAt?:string}):BookVersionBranch{const base=history.versions.find(v=>v.id===input.baseVersionId);if(!base)throw new Error(`Base version "${input.baseVersionId}" was not found.`);if(history.branches.some(b=>b.name===input.name))throw new Error(`Version branch "${input.name}" already exists.`);return{id:input.id??cryptoId(),projectId:history.projectId,bookId:history.bookId,name:req(input.name,"Branch name"),baseVersionId:base.id,headVersionId:base.id,createdAt:input.createdAt??new Date().toISOString()};}
export function mergeVersions(target:BookSnapshot,source:BookSnapshot,base:BookSnapshot):BookSnapshot{if(target.projectId!==source.projectId||target.bookId!==source.bookId||base.projectId!==target.projectId||base.bookId!==target.bookId)throw new Error("Versions must share project and book.");const keys=new Set([...Object.keys(base.chapters),...Object.keys(target.chapters),...Object.keys(source.chapters)]);const chapters:Record<string,string>={};for(const k of [...keys].sort()){const b=base.chapters[k],t=target.chapters[k],s=source.chapters[k];if(t===s){if(t!==undefined)chapters[k]=t;continue;}if(t===b){if(s!==undefined)chapters[k]=s;continue;}if(s===b){if(t!==undefined)chapters[k]=t;continue;}throw new Error(`Merge conflict in chapter "${k}".`);}return createBookSnapshot({...target,id:undefined,label:"custom",name:`Merge of ${target.name} and ${source.name}`,createdAt:new Date().toISOString(),chapters,parentId:target.id});}
function cryptoId():string{return `ver_${Date.now()}_${Math.random().toString(36).slice(2,10)}`;}
