export const EDUCATIONAL_ASSESSMENT_FORMAT_VERSION = 1 as const;
export const EDUCATIONAL_RESPONSE_MODES = ["written", "oral", "drawing", "diagram", "model", "demonstration", "digital", "other"] as const;
export type EducationalResponseMode = typeof EDUCATIONAL_RESPONSE_MODES[number];
export const EDUCATIONAL_MASTERY_BANDS = ["emerging", "developing", "proficient", "advanced"] as const;
export type EducationalMasteryBand = typeof EDUCATIONAL_MASTERY_BANDS[number];
export interface EducationalRubricLevel { readonly id:string; readonly label:string; readonly score:number; readonly description:string; }
export interface EducationalRubricCriterion { readonly id:string; readonly name:string; readonly description:string; readonly weightPercent:number; readonly learningObjective:string; readonly evidenceGuidance:string; }
export interface EducationalRubric { readonly formatVersion:typeof EDUCATIONAL_ASSESSMENT_FORMAT_VERSION; readonly id:string; readonly projectId:string; readonly title:string; readonly description:string; readonly gradeBand:string; readonly standards:readonly string[]; readonly allowedResponseModes:readonly EducationalResponseMode[]; readonly criteria:readonly EducationalRubricCriterion[]; readonly levels:readonly EducationalRubricLevel[]; readonly createdAt:string; readonly updatedAt:string; }
export interface EducationalAssessmentScore { readonly criterionId:string; readonly levelId:string; readonly evidenceNote:string; }
export interface EducationalAssessmentRecord { readonly formatVersion:typeof EDUCATIONAL_ASSESSMENT_FORMAT_VERSION; readonly id:string; readonly projectId:string; readonly rubricId:string; readonly activityOrTaskId:string; readonly responseMode:EducationalResponseMode; readonly scores:readonly EducationalAssessmentScore[]; readonly weightedPercent:number; readonly masteryBand:EducationalMasteryBand; readonly feedback:string; readonly recordedAt:string; }
export function createEducationalRubric(input:{readonly id:string;readonly projectId:string;readonly title:string;readonly description?:string;readonly gradeBand:string;readonly standards?:readonly string[];readonly allowedResponseModes?:readonly EducationalResponseMode[];readonly criteria:readonly EducationalRubricCriterion[];readonly levels:readonly EducationalRubricLevel[];readonly now?:string;}):EducationalRubric{const now=iso(input.now??new Date().toISOString(),"Rubric timestamp"),criteria=input.criteria.map(validateCriterion),levels=input.levels.map(validateLevel).sort((a,b)=>a.score-b.score||a.id.localeCompare(b.id));if(criteria.length<1||criteria.length>20)throw new Error("Rubric requires 1 to 20 criteria.");if(levels.length<2||levels.length>8)throw new Error("Rubric requires 2 to 8 performance levels.");uniqueIds(criteria.map(i=>i.id),"rubric criterion");uniqueIds(levels.map(i=>i.id),"rubric level");const total=criteria.reduce((n,c)=>n+c.weightPercent,0);if(Math.abs(total-100)>0.001)throw new Error(`Rubric criterion weights must total 100%; received ${total}%.`);const modes=uniqueModes(input.allowedResponseModes?.length?input.allowedResponseModes:["written"]);return Object.freeze({formatVersion:1,id:required(input.id,"Rubric id"),projectId:required(input.projectId,"Project id"),title:required(input.title,"Rubric title"),description:optional(input.description),gradeBand:required(input.gradeBand,"Rubric grade band"),standards:Object.freeze(uniqueStrings(input.standards??[])),allowedResponseModes:Object.freeze(modes),criteria:Object.freeze(criteria),levels:Object.freeze(levels),createdAt:now,updatedAt:now});}
export function validateEducationalRubric(value:EducationalRubric):EducationalRubric{if(!value||typeof value!=="object"||value.formatVersion!==1)throw new Error("Invalid or unsupported educational rubric.");return createEducationalRubric({id:value.id,projectId:value.projectId,title:value.title,description:value.description,gradeBand:value.gradeBand,standards:value.standards,allowedResponseModes:value.allowedResponseModes,criteria:value.criteria,levels:value.levels,now:value.createdAt});}
export function scoreEducationalAssessment(input:{readonly id:string;readonly projectId:string;readonly rubric:EducationalRubric;readonly activityOrTaskId:string;readonly responseMode:EducationalResponseMode;readonly scores:readonly EducationalAssessmentScore[];readonly feedback?:string;readonly now?:string;}):EducationalAssessmentRecord{const rubric=validateEducationalRubric(input.rubric);if(rubric.projectId!==required(input.projectId,"Project id"))throw new Error("Assessment rubric belongs to another project.");if(!rubric.allowedResponseModes.includes(input.responseMode))throw new Error(`Response mode "${input.responseMode}" is not allowed by this rubric.`);if(!Array.isArray(input.scores)||input.scores.length!==rubric.criteria.length)throw new Error("Assessment requires exactly one score for every rubric criterion.");const map=new Map();for(const score of input.scores){if(!score||typeof score!=="object")throw new Error("Invalid rubric score.");const cid=required(score.criterionId,"Assessment criterion id");if(map.has(cid))throw new Error(`Duplicate score for criterion "${cid}".`);if(!rubric.criteria.some(c=>c.id===cid))throw new Error(`Unknown rubric criterion "${cid}".`);const lid=required(score.levelId,"Assessment level id");if(!rubric.levels.some(l=>l.id===lid))throw new Error(`Unknown rubric level "${lid}".`);map.set(cid,Object.freeze({criterionId:cid,levelId:lid,evidenceNote:optional(score.evidenceNote)}));}for(const c of rubric.criteria)if(!map.has(c.id))throw new Error(`Missing score for criterion "${c.id}".`);const min=Math.min(...rubric.levels.map(l=>l.score)),max=Math.max(...rubric.levels.map(l=>l.score));if(max<=min)throw new Error("Rubric performance levels must span more than one numeric score.");let weighted=0;for(const c of rubric.criteria){const s=map.get(c.id),l=rubric.levels.find(x=>x.id===s.levelId);weighted+=((l.score-min)/(max-min))*c.weightPercent;}const weightedPercent=Math.round(weighted*10)/10;return Object.freeze({formatVersion:1,id:required(input.id,"Assessment id"),projectId:rubric.projectId,rubricId:rubric.id,activityOrTaskId:required(input.activityOrTaskId,"Activity or task id"),responseMode:input.responseMode,scores:Object.freeze(rubric.criteria.map(c=>map.get(c.id))),weightedPercent,masteryBand:weightedPercent>=90?"advanced":weightedPercent>=70?"proficient":weightedPercent>=50?"developing":"emerging",feedback:optional(input.feedback),recordedAt:iso(input.now??new Date().toISOString(),"Assessment timestamp")});}
export function validateEducationalAssessmentRecord(value:EducationalAssessmentRecord,rubric:EducationalRubric):EducationalAssessmentRecord{const r=scoreEducationalAssessment({id:value.id,projectId:value.projectId,rubric,activityOrTaskId:value.activityOrTaskId,responseMode:value.responseMode,scores:value.scores,feedback:value.feedback,now:value.recordedAt});if(Math.abs(r.weightedPercent-value.weightedPercent)>0.001||r.masteryBand!==value.masteryBand)throw new Error("Stored assessment score does not match rubric calculation.");return r;}
function validateCriterion(v:EducationalRubricCriterion):EducationalRubricCriterion{const w=Number(v.weightPercent);if(!Number.isFinite(w)||w<=0||w>100)throw new Error("Rubric criterion weight must be greater than 0 and at most 100.");return Object.freeze({id:required(v.id,"Criterion id"),name:required(v.name,"Criterion name"),description:required(v.description,"Criterion description"),weightPercent:w,learningObjective:required(v.learningObjective,"Criterion learning objective"),evidenceGuidance:required(v.evidenceGuidance,"Criterion evidence guidance")});}
function validateLevel(v:EducationalRubricLevel):EducationalRubricLevel{const score=Number(v.score);if(!Number.isFinite(score))throw new Error("Rubric level score must be finite.");return Object.freeze({id:required(v.id,"Rubric level id"),label:required(v.label,"Rubric level label"),score,description:required(v.description,"Rubric level description")});}
function uniqueModes(v:readonly EducationalResponseMode[]):EducationalResponseMode[]{const r=[...new Set(v)];for(const m of r)if(!EDUCATIONAL_RESPONSE_MODES.includes(m))throw new Error(`Unsupported educational response mode "${m}".`);return r;}function uniqueIds(v:readonly string[],l:string){if(new Set(v).size!==v.length)throw new Error(`Duplicate ${l} id.`)}function uniqueStrings(v:readonly string[]):string[]{return[...new Set(v.map(x=>String(x).trim()).filter(Boolean))]}function required(v:string,l:string):string{if(typeof v!=="string"||!v.trim())throw new Error(`${l} is required.`);return v.trim()}function optional(v:unknown):string{return typeof v==="string"?v.trim():""}function iso(v:string,l:string):string{const d=new Date(v);if(!Number.isFinite(d.getTime()))throw new Error(`${l} must be a valid timestamp.`);return d.toISOString()}
