export const EXTERNAL_STORAGE_FORMAT_VERSION = 1 as const;
export type StorageProviderId="local"|"google-drive"|"onedrive"|"dropbox"|"icloud"|"download";
export interface StoredObject { readonly key:string; readonly size:number; readonly mediaType:string; readonly updatedAt:string; readonly etag?:string; }
export interface StorageProvider { readonly id:StorageProviderId; put(key:string,content:Uint8Array,mediaType:string):Promise<StoredObject>; get(key:string):Promise<Uint8Array>; delete(key:string):Promise<void>; list(prefix?:string):Promise<readonly StoredObject[]>; }
export interface ProjectStorageBinding { readonly formatVersion:typeof EXTERNAL_STORAGE_FORMAT_VERSION; readonly projectId:string; readonly providerId:StorageProviderId; readonly keyPrefix:string; readonly sourceOfTruth:"forge-project"; }
const text=(v:unknown,label:string)=>{if(typeof v!=="string"||!v.trim())throw new Error(`${label} is required.`);return v.trim();};
export function createProjectStorageBinding(input:{projectId:string;providerId:StorageProviderId;keyPrefix?:string}):ProjectStorageBinding{return{formatVersion:EXTERNAL_STORAGE_FORMAT_VERSION,projectId:text(input.projectId,"Project id"),providerId:input.providerId,keyPrefix:(input.keyPrefix??`projects/${input.projectId}`).replace(/^\/|\/$/g,""),sourceOfTruth:"forge-project"};}
export function validateProjectStorageBinding(binding:ProjectStorageBinding):ProjectStorageBinding{if(binding.formatVersion!==EXTERNAL_STORAGE_FORMAT_VERSION)throw new Error("Unsupported external storage binding version.");text(binding.projectId,"Project id");text(binding.keyPrefix,"Storage key prefix");if(binding.sourceOfTruth!=="forge-project")throw new Error("Forge project must remain the source of truth.");return{...binding};}
export function createDownloadableProjectPackageFilename(projectId:string):string{return`${text(projectId,"Project id")}.forge-project.json`;}
export class MemoryStorageProvider implements StorageProvider{readonly id="download" as const;private readonly objects=new Map<string,{bytes:Uint8Array;mediaType:string;updatedAt:string}>();async put(key:string,content:Uint8Array,mediaType:string){const value={bytes:new Uint8Array(content),mediaType:text(mediaType,"Media type"),updatedAt:new Date().toISOString()};this.objects.set(text(key,"Storage key"),value);return{key,size:value.bytes.byteLength,mediaType:value.mediaType,updatedAt:value.updatedAt};}async get(key:string){const value=this.objects.get(text(key,"Storage key"));if(!value)throw new Error(`Storage object "${key}" was not found.`);return new Uint8Array(value.bytes);}async delete(key:string){this.objects.delete(text(key,"Storage key"));}async list(prefix=""){return[...this.objects.entries()].filter(([key])=>key.startsWith(prefix)).map(([key,v])=>({key,size:v.bytes.byteLength,mediaType:v.mediaType,updatedAt:v.updatedAt}));}}
