export const FINAL_PRODUCT_FORMAT_VERSION=1 as const;
export const KINGS_CAPABILITY_FORMAT_VERSION=1 as const;
export type CapabilityGap=Readonly<{id:string;projectId:string;capability:string;reason:string;requestedAt:string}>;
export type CapabilityEscalation=Readonly<{gap:CapabilityGap;status:"requested"|"accepted"|"completed"|"rejected";requestedBy:"forge";authority:"kings";completedAt?:string}>;
export function createCapabilityGap(input:Omit<CapabilityGap,"requestedAt">&{requestedAt?:string}):CapabilityGap{for(const k of ["id","projectId","capability","reason"] as const)if(!input[k].trim())throw new Error(`Capability gap ${k} is required.`);return Object.freeze({...input,requestedAt:input.requestedAt??new Date().toISOString()});}
export function escalateCapability(gap:CapabilityGap):CapabilityEscalation{return Object.freeze({gap,status:"requested",requestedBy:"forge",authority:"kings"});}
export function completeCapabilityEscalation(e:CapabilityEscalation,completedAt=new Date().toISOString()):CapabilityEscalation{if(e.status!=="accepted")throw new Error("Only an accepted K.I.N.G.S. capability escalation can be completed.");return Object.freeze({...e,status:"completed",completedAt});}
export const SECURITY_FORMAT_VERSION=1 as const;
export type Permission="read"|"write"|"export"|"delete"|"research"|"image-process";
export type SecurityPolicy=Readonly<{projectId:string;localFirst:boolean;permissions:readonly Permission[];externalUploadAllowed:boolean;researchConsentRequired:boolean;imageProcessingConsentRequired:boolean;providerDisclosureRequired:boolean}>;
export type SecurityAuditEntry=Readonly<{id:string;projectId:string;actor:string;action:string;target:string;timestamp:string;externalUpload:boolean;attributableTo:string}>;
export function createSecurityPolicy(projectId:string,permissions:readonly Permission[]=["read","write","export","delete"]):SecurityPolicy{if(!projectId.trim())throw new Error("Security policy requires a project id.");return Object.freeze({projectId,localFirst:true,permissions:[...new Set(permissions)],externalUploadAllowed:false,researchConsentRequired:true,imageProcessingConsentRequired:true,providerDisclosureRequired:true});}
export function assertPermission(policy:SecurityPolicy,permission:Permission):void{if(!policy.permissions.includes(permission))throw new Error(`Permission denied: ${permission}.`);}
export function createSecurityAuditEntry(input:Omit<SecurityAuditEntry,"timestamp">&{timestamp?:string}):SecurityAuditEntry{for(const k of ["id","projectId","actor","action","target","attributableTo"] as const)if(!input[k].trim())throw new Error(`Security audit ${k} is required.`);return Object.freeze({...input,timestamp:input.timestamp??new Date().toISOString()});}
export const PLATFORM_FORMAT_VERSION=1 as const;
export const SUPPORTED_PLATFORMS=["android","ios","windows","macos","linux","web"] as const;
export const ACCESS_INPUTS=["keyboard","mouse","touch","voice"] as const;
export const ACCESS_OUTPUTS=["screen-reader","large-text","high-contrast"] as const;
export type Platform=typeof SUPPORTED_PLATFORMS[number];
export type AccessibilityProfile=Readonly<{keyboard:boolean;mouse:boolean;touch:boolean;voice:boolean;screenReader:boolean;largeText:boolean;highContrast:boolean}>;
export function createAccessibilityProfile(input:AccessibilityProfile):AccessibilityProfile{return Object.freeze({...input});}
export const VOICE_INPUT_FORMAT_VERSION=1 as const;
export type VoiceIntentKind="idea-capture"|"story-planning"|"editing-command"|"research-request"|"character-creation"|"scene-direction"|"revision-instruction";
export type VoiceIntent=Readonly<{kind:VoiceIntentKind;confidence:number;parameters:Readonly<Record<string,string>>}>;
export type VoiceInputRecord=Readonly<{id:string;projectId:string;transcription:string;intent:VoiceIntent;capturedAt:string}>;
const intentPatterns:readonly [VoiceIntentKind,RegExp][]=[["research-request",/\b(research|look up|find sources)\b/i],["editing-command",/\b(edit|rewrite|fix|revise|change)\b/i],["character-creation",/\b(character|protagonist|antagonist)\b/i],["scene-direction",/\b(scene|chapter|starts? with|set this)\b/i],["story-planning",/\b(plot|outline|story|arc)\b/i],["revision-instruction",/\b(make it|remove|add|increase|decrease)\b/i]];
export function classifyVoiceIntent(transcription:string):VoiceIntent{if(!transcription.trim())throw new Error("Voice transcription is required.");const match=intentPatterns.find(([,pattern])=>pattern.test(transcription));return Object.freeze({kind:match?.[0]??"idea-capture",confidence:match?0.9:0.55,parameters:{transcription}});}
export function createVoiceInputRecord(input:Omit<VoiceInputRecord,"intent"|"capturedAt">&{intent?:VoiceIntent;capturedAt?:string}):VoiceInputRecord{if(!input.transcription.trim())throw new Error("Original transcription is required.");return Object.freeze({...input,intent:input.intent??classifyVoiceIntent(input.transcription),capturedAt:input.capturedAt??new Date().toISOString()});}
export const IP_PROVENANCE_FORMAT_VERSION=1 as const;
export type ContentOrigin="author-owned"|"user-uploaded"|"generated"|"public-domain"|"external-research"|"third-party-reference"|"unknown";
export type ContentProvenance=Readonly<{id:string;projectId:string;origin:ContentOrigin;source?:string;license?:string;consent?:"granted"|"not-required"|"pending";notes?:string}>;
export function createContentProvenance(input:ContentProvenance):ContentProvenance{if(!input.id.trim()||!input.projectId.trim())throw new Error("Content provenance requires id and project id.");if((input.origin==="user-uploaded"||input.origin==="third-party-reference")&&input.consent!=="granted")throw new Error("Uploaded/reference content requires explicit consent before processing.");if(input.origin==="external-research"&&!input.source?.trim())throw new Error("External research must identify its source.");return Object.freeze({...input});}
export const BOOK_GENOME_FORMAT_VERSION=1 as const;
export const BOOK_GENOME_COMPONENTS=["premise","theme","genre","voice","characters","relationships","locations","timeline","events","scenes","objects","clues","reveals","conflicts","motivations","research","visual-identities","art","cover","metadata","publishing-state"] as const;
export type BookGenomeComponent=typeof BOOK_GENOME_COMPONENTS[number];
export type GenomeNode=Readonly<{id:string;type:BookGenomeComponent;label:string;data:Readonly<Record<string,unknown>>}>;
export type GenomeEdge=Readonly<{from:string;to:string;relation:string}>;
export type BookGenome=Readonly<{projectId:string;nodes:readonly GenomeNode[];edges:readonly GenomeEdge[];version:number}>;
export type GenomeImpact=Readonly<{changedNodeId:string;affectedNodeIds:readonly string[];affectedComponents:readonly BookGenomeComponent[]}>;
export function createBookGenome(projectId:string,nodes:readonly GenomeNode[]=[],edges:readonly GenomeEdge[]=[]):BookGenome{if(!projectId.trim())throw new Error("Book Genome requires a project id.");const ids=new Set<string>();for(const n of nodes){if(!BOOK_GENOME_COMPONENTS.includes(n.type))throw new Error(`Unsupported Book Genome component: ${n.type}.`);if(ids.has(n.id))throw new Error(`Duplicate Book Genome node: ${n.id}.`);ids.add(n.id);}for(const e of edges)if(!ids.has(e.from)||!ids.has(e.to))throw new Error("Book Genome edge references an unknown node.");return Object.freeze({projectId,nodes:[...nodes],edges:[...edges],version:1});}
export function analyzeGenomeImpact(genome:BookGenome,changedNodeId:string):GenomeImpact{if(!genome.nodes.some(n=>n.id===changedNodeId))throw new Error(`Unknown Book Genome node: ${changedNodeId}.`);const affected=new Set<string>(),queue=[changedNodeId];while(queue.length){const id=queue.shift()!;for(const e of genome.edges.filter(x=>x.from===id||x.to===id)){const next=e.from===id?e.to:e.from;if(next!==changedNodeId&&!affected.has(next)){affected.add(next);queue.push(next);}}}const types=[...new Set(genome.nodes.filter(n=>affected.has(n.id)).map(n=>n.type))];return Object.freeze({changedNodeId,affectedNodeIds:[...affected],affectedComponents:types});}
export type FinalProductStage="concept"|"architecture"|"canon"|"characters"|"timeline"|"research"|"manuscript"|"editing"|"illustrations"|"cover"|"formatting"|"metadata"|"positioning"|"marketing"|"publishing"|"archive";
export const FINAL_PRODUCT_STAGES:readonly FinalProductStage[]=["concept","architecture","canon","characters","timeline","research","manuscript","editing","illustrations","cover","formatting","metadata","positioning","marketing","publishing","archive"];
export type FinalProductStatus=Readonly<{projectId:string;completed:readonly FinalProductStage[];current:FinalProductStage;ready:boolean;message:string}>;
export function createFinalProductStatus(projectId:string,completed:readonly FinalProductStage[],current:FinalProductStage):FinalProductStatus{if(!projectId.trim())throw new Error("Final product status requires a project id.");const unique=[...new Set(completed)];if(unique.some(s=>!FINAL_PRODUCT_STAGES.includes(s)))throw new Error("Unknown final-product stage.");const ready=FINAL_PRODUCT_STAGES.every(s=>unique.includes(s));return Object.freeze({projectId,completed:unique,current,ready,message:ready?"PROJECT READY FOR AUTHOR APPROVAL":"PROJECT NOT READY — required production stages remain."});}
