export const MARKETING_CHANNELS = ["author-site", "email", "social", "reader-community", "ads", "press", "retailer"] as const;
export type MarketingChannel = typeof MARKETING_CHANNELS[number];
export type MarketingAssetStatus = "draft" | "approved" | "scheduled" | "published" | "rejected";
export interface MarketingEvidence { readonly source: string; readonly claim: string; readonly confidence: "known" | "source-supported" | "inference" | "creative"; }
export interface MarketingAsset { readonly id: string; readonly channel: MarketingChannel; readonly title: string; readonly body: string; readonly status: MarketingAssetStatus; readonly evidence: readonly MarketingEvidence[]; readonly scheduledFor?: string; }
export interface MarketingCampaign { readonly id: string; readonly projectId: string; readonly bookId: string; readonly objective: string; readonly audience: string; readonly readerPromise: string; readonly assets: readonly MarketingAsset[]; }
const required=(v:string,l:string)=>{if(!v.trim())throw new Error(`${l} is required.`)};
export function createMarketingCampaign(input:MarketingCampaign):MarketingCampaign{required(input.id,"Campaign id");required(input.projectId,"Project id");required(input.bookId,"Book id");required(input.objective,"Objective");required(input.audience,"Audience");required(input.readerPromise,"Reader promise");const ids=new Set<string>();for(const a of input.assets){required(a.id,"Asset id");required(a.title,"Asset title");required(a.body,"Asset body");if(ids.has(a.id))throw new Error(`Duplicate marketing asset id ${a.id}.`);ids.add(a.id);if(!MARKETING_CHANNELS.includes(a.channel))throw new Error(`Unsupported marketing channel ${a.channel}.`);if((a.status==="scheduled"||a.status==="published")&&a.evidence.some(e=>e.confidence==="inference"))throw new Error("Inference-only claims cannot be scheduled or published.");if(a.status==="scheduled"&&!a.scheduledFor)throw new Error("Scheduled assets require a schedule.");}return structuredClone(input)}
export function approveMarketingAsset(campaign:MarketingCampaign,id:string):MarketingCampaign{const asset=campaign.assets.find(a=>a.id===id);if(!asset)throw new Error(`Marketing asset ${id} not found.`);if(asset.status==="rejected")throw new Error("Rejected assets must be regenerated.");return {...campaign,assets:campaign.assets.map(a=>a.id===id?{...a,status:"approved"}:a)}}
export function scheduleMarketingAsset(campaign:MarketingCampaign,id:string,when:string):MarketingCampaign{const asset=campaign.assets.find(a=>a.id===id);if(!asset)throw new Error(`Marketing asset ${id} not found.`);if(asset.status!=="approved")throw new Error("Only approved assets may be scheduled.");const date=new Date(when);if(Number.isNaN(date.getTime()))throw new Error("Invalid marketing schedule time.");return {...campaign,assets:campaign.assets.map(a=>a.id===id?{...a,status:"scheduled",scheduledFor:date.toISOString()}:a)}}
