export const MARKETING_STUDIO_FORMAT_VERSION = 1 as const;
export const MARKETING_CHANNELS = ["facebook","instagram","tiktok","threads","x","pinterest","youtube"] as const;
export const MARKETING_ASSET_TYPES = ["social-post","video-script","flyer","bookmark","postcard","quote-card","launch-graphic","countdown-graphic","teaser-image","character-card","review-graphic","event-poster","email-campaign","ad-copy","ad-headline","ad-description","ad-creative-concept"] as const;
export type MarketingChannel=typeof MARKETING_CHANNELS[number];
export type MarketingAssetType=typeof MARKETING_ASSET_TYPES[number];
export interface MarketingAsset {readonly id:string;readonly projectId:string;readonly bookId?:string;readonly channel?:MarketingChannel;readonly type:MarketingAssetType;readonly title:string;readonly body:string;readonly variant:number;readonly scheduledAt?:string;readonly createdAt:string;}
export interface MarketingPackage {readonly formatVersion:typeof MARKETING_STUDIO_FORMAT_VERSION;readonly id:string;readonly projectId:string;readonly bookId?:string;readonly assets:readonly MarketingAsset[];readonly createdAt:string;readonly updatedAt:string;}
export interface CreateMarketingPackageInput {readonly id:string;readonly projectId:string;readonly bookId?:string;readonly assets:readonly Omit<MarketingAsset,"createdAt">[];readonly now?:string;}
const text=(v:string,label:string)=>{if(typeof v!=="string"||!v.trim())throw new Error(`${label} is required.`);return v.trim();};
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
export function validateMarketingPackage(p:MarketingPackage):MarketingPackage {if(p.formatVersion!==1)throw new Error("Unsupported marketing package format version.");text(p.id,"Marketing package id");text(p.projectId,"Project id");text(p.createdAt,"Created at");text(p.updatedAt,"Updated at");const ids=new Set<string>();for(const a of p.assets){text(a.id,"Marketing asset id");if(ids.has(a.id))throw new Error(`Duplicate marketing asset id \"${a.id}\".`);ids.add(a.id);text(a.projectId,"Marketing asset project id");if(a.projectId!==p.projectId)throw new Error(`Marketing asset \"${a.id}\" belongs to another project.`);if(!(MARKETING_ASSET_TYPES as readonly string[]).includes(a.type))throw new Error(`Unsupported marketing asset type \"${a.type}\".`);if(a.channel&&!((MARKETING_CHANNELS as readonly string[]).includes(a.channel)))throw new Error(`Unsupported marketing channel \"${a.channel}\`.`);text(a.title,"Marketing asset title");text(a.body,"Marketing asset body");if(!Number.isInteger(a.variant)||a.variant<1)throw new Error("Marketing asset variant must be a positive integer.");text(a.createdAt,"Marketing asset created at");if(a.scheduledAt)text(a.scheduledAt,"Scheduled at");}return clone(p);}
export function createMarketingPackage(i:CreateMarketingPackageInput):MarketingPackage {const now=i.now??new Date().toISOString();const p:MarketingPackage={formatVersion:1,id:text(i.id,"Marketing package id"),projectId:text(i.projectId,"Project id"),bookId:i.bookId,assets:i.assets.map(a=>({...a,createdAt:now})),createdAt:now,updatedAt:now};return validateMarketingPackage(p);}
export function addMarketingAssets(p:MarketingPackage,assets:readonly Omit<MarketingAsset,"createdAt">[],now=new Date().toISOString()):MarketingPackage {const next={...p,assets:[...p.assets,...assets.map(a=>({...a,createdAt:now}))],updatedAt:now};return validateMarketingPackage(next);}
export function scheduleMarketingAsset(p:MarketingPackage,assetId:string,scheduledAt:string,now=new Date().toISOString()):MarketingPackage {text(scheduledAt,"Scheduled at");const found=p.assets.some(a=>a.id===assetId);if(!found)throw new Error(`Marketing asset \"${assetId}\" does not exist.`);return validateMarketingPackage({...p,updatedAt:now,assets:p.assets.map(a=>a.id===assetId?{...a,scheduledAt}:a)});}
export function createMarketingVariants(base:Omit<MarketingAsset,"createdAt"|"variant">,count:number,now=new Date().toISOString()):readonly MarketingAsset[]{if(!Number.isInteger(count)||count<1||count>50)throw new Error("Variant count must be between 1 and 50.");return Array.from({length:count},(_,i)=>({...base,id:`${base.id}-v${i+1}`,variant:i+1,createdAt:now}));}