import type { CharacterRecord } from "./character-bible";
import { validateCharacterRecord } from "./character-bible";
import type { VisualCharacterIdentity } from "./character-visual-continuity";
import { validateVisualCharacterIdentity } from "./character-visual-continuity";
import type { IllustrationAssetLibraryState } from "./illustration-asset-library";
import { validateIllustrationAssetLibraryState } from "./illustration-asset-library";
import type { BookCoverPlan } from "./book-cover-studio";
import { calculateKdpCoverLayout, validatePublishingConfiguration } from "./book-cover-studio";
import type { PublishingReadinessReport } from "./publishing-readiness";
import { validatePublishingReadinessReport } from "./publishing-readiness";
import type { KdpMarketIntelligenceReport } from "./kdp-market-intelligence";
import { validateKdpMarketIntelligenceReport } from "./kdp-market-intelligence";
import type { BookPositioningReport } from "./book-positioning";
import { validateBookPositioningReport } from "./book-positioning";
import type { MemoryRecord } from "./memory";
import type { BookVersionHistory } from "./book-version-control";
import type { AuthorDecision } from "./author-control";
import type { SeriesState } from "./series";
import type { VoiceProfile } from "./voice-preservation";
import type { ProjectHealth, MemoryRelationship, DeliveryAuditReport } from "./collaboration-health-memory-delivery";
import type { BookGenome, ContentProvenance, VoiceInputRecord, SecurityAuditEntry, SecurityPolicy, FinalProductStatus } from "./final-product-systems";
export const PROJECT_FORMAT_VERSION=2 as const;
export type ProjectStatus="active"|"archived";
export interface ProjectMetadata{readonly id:string;readonly title:string;readonly createdAt:string;readonly updatedAt:string;readonly status:ProjectStatus;}
export interface ProjectState{readonly formatVersion:typeof PROJECT_FORMAT_VERSION;readonly metadata:ProjectMetadata;readonly memories:readonly MemoryRecord[];readonly characters?:readonly CharacterRecord[];readonly visualIdentities?:readonly VisualCharacterIdentity[];readonly illustrationAssetLibrary?:IllustrationAssetLibraryState;readonly bookCoverPlans?:readonly BookCoverPlan[];readonly publishingReadinessReports?:readonly PublishingReadinessReport[];readonly kdpMarketIntelligenceReports?:readonly KdpMarketIntelligenceReport[];readonly bookPositioningReports?:readonly BookPositioningReport[];readonly bookVersionHistories?:readonly BookVersionHistory[];readonly authorDecisions?:readonly AuthorDecision[];readonly series?:readonly SeriesState[];readonly voiceProfiles?:readonly VoiceProfile[];readonly collaborationMode?:import("./collaboration-health-memory-delivery").AiCollaborationMode;readonly projectHealth?:ProjectHealth;readonly relationshipMemories?:readonly MemoryRelationship[];readonly deliveryAudit?:DeliveryAuditReport;readonly bookGenome?:BookGenome;readonly contentProvenance?:readonly ContentProvenance[];readonly voiceInputs?:readonly VoiceInputRecord[];readonly securityPolicy?:SecurityPolicy;readonly securityAudit?:readonly SecurityAuditEntry[];readonly finalProductStatus?:FinalProductStatus;}
export function createProject(input:{id:string;title:string;now?:string}):ProjectState{if(!input.id.trim())throw new Error("Project id is required.");if(!input.title.trim())throw new Error("Project title is required.");const now=input.now??new Date().toISOString();return{formatVersion:PROJECT_FORMAT_VERSION,metadata:{id:input.id,title:input.title.trim(),createdAt:now,updatedAt:now,status:"active"},memories:[]};}
export function touchProject(project:ProjectState,now=new Date().toISOString()):ProjectState{return{...project,metadata:{...project.metadata,updatedAt:now}};}
export function withProjectMemories(project:ProjectState,memories:readonly MemoryRecord[],now=new Date().toISOString()):ProjectState{if(memories.some(m=>m.projectId!==project.metadata.id))throw new Error("Project memory state contains a memory from another project.");const ids=new Set<string>();for(const m of memories){if(ids.has(m.id))throw new Error(`Duplicate memory id \"${m.id}\" in project state.`);ids.add(m.id);}return{...project,metadata:{...project.metadata,updatedAt:now},memories:memories.map(cloneMemory)};}
export function withProjectCharacters(project:ProjectState,characters:readonly CharacterRecord[],now=new Date().toISOString()):ProjectState{if(characters.some(c=>c.projectId!==project.metadata.id))throw new Error("Project character state contains a character from another project.");const ids=new Set<string>();const validated=characters.map(validateCharacterRecord);for(const c of validated){if(ids.has(c.id))throw new Error(`Duplicate character id \"${c.id}\" in project state.`);ids.add(c.id);}return{...project,metadata:{...project.metadata,updatedAt:now},characters:validated.map(cloneCharacter)};}
export function withProjectVisualIdentities(project:ProjectState,v:readonly VisualCharacterIdentity[],now=new Date().toISOString()):ProjectState{if(v.some(i=>i.projectId!==project.metadata.id))throw new Error("Project visual identity state contains an identity from another project.");const ids=new Set<string>(),characters=new Set<string>();const validated=v.map(validateVisualCharacterIdentity);for(const i of validated){if(ids.has(i.id))throw new Error(`Duplicate visual identity id \"${i.id}\" in project state.`);ids.add(i.id);if(characters.has(i.characterId))throw new Error(`Duplicate visual identity for character \"${i.characterId}\" in project state.`);characters.add(i.characterId);}return{...project,metadata:{...project.metadata,updatedAt:now},visualIdentities:validated.map(i=>validateVisualCharacterIdentity(JSON.parse(JSON.stringify(i))))};}
export function withProjectIllustrationAssetLibrary(project:ProjectState,library:IllustrationAssetLibraryState,now=new Date().toISOString()):ProjectState{const v=validateIllustrationAssetLibraryState(library);if(v.projectId!==project.metadata.id)throw new Error("Project illustration asset library belongs to another project.");return{...project,metadata:{...project.metadata,updatedAt:now},illustrationAssetLibrary:validateIllustrationAssetLibraryState(JSON.parse(JSON.stringify(v)))};}
export function withProjectBookCoverPlans(project:ProjectState,plans:readonly BookCoverPlan[],now=new Date().toISOString()):ProjectState{const ids=new Set<string>();const validated=plans.map(p=>{if(p.projectId!==project.metadata.id)throw new Error("Project book cover plan belongs to another project.");if(ids.has(p.id))throw new Error(`Duplicate book cover plan id \"${p.id}\" in project state.`);ids.add(p.id);validatePublishingConfiguration(p.publishing);const e=calculateKdpCoverLayout(p.publishing);if(e.dimensions.widthInches!==p.dimensions.widthInches||e.dimensions.heightInches!==p.dimensions.heightInches)throw new Error(`Book cover plan \"${p.id}\" contains invalid calculated dimensions.`);return JSON.parse(JSON.stringify(p)) as BookCoverPlan;});return{...project,metadata:{...project.metadata,updatedAt:now},bookCoverPlans:validated};}
export function withProjectPublishingReadinessReports(project:ProjectState,reports:readonly PublishingReadinessReport[],now=new Date().toISOString()):ProjectState{const ids=new Set<string>(),validated=reports.map(validatePublishingReadinessReport);for(const r of validated){if(r.projectId!==project.metadata.id)throw new Error(`Project publishing readiness report \"${r.id}\" belongs to another project.`);if(ids.has(r.id))throw new Error(`Duplicate publishing readiness report id \"${r.id}\" in project state.`);ids.add(r.id);}return{...project,metadata:{...project.metadata,updatedAt:now},publishingReadinessReports:validated.map(r=>validatePublishingReadinessReport(JSON.parse(JSON.stringify(r))))};}
export function withProjectKdpMarketIntelligenceReports(project:ProjectState,reports:readonly KdpMarketIntelligenceReport[],now=new Date().toISOString()):ProjectState{const ids=new Set<string>(),validated=reports.map(validateKdpMarketIntelligenceReport);for(const r of validated){if(r.projectId!==project.metadata.id)throw new Error(`Project market intelligence report \"${r.id}\" belongs to another project.`);if(ids.has(r.id))throw new Error(`Duplicate market intelligence report id \"${r.id}\" in project state.`);ids.add(r.id);}return{...project,metadata:{...project.metadata,updatedAt:now},kdpMarketIntelligenceReports:validated.map(r=>validateKdpMarketIntelligenceReport(JSON.parse(JSON.stringify(r))))};}
export function withProjectBookPositioningReports(project:ProjectState,reports:readonly BookPositioningReport[],now=new Date().toISOString()):ProjectState{const ids=new Set<string>(),validated=reports.map(validateBookPositioningReport);for(const r of validated){if(r.projectId!==project.metadata.id)throw new Error(`Project book positioning report \"${r.id}\" belongs to another project.`);if(ids.has(r.id))throw new Error(`Duplicate book positioning report id \"${r.id}\" in project state.`);ids.add(r.id);}return{...project,metadata:{...project.metadata,updatedAt:now},bookPositioningReports:validated.map(r=>validateBookPositioningReport(JSON.parse(JSON.stringify(r))))};}
export function withProjectBookVersionHistories(project:ProjectState,histories:readonly BookVersionHistory[],now=new Date().toISOString()):ProjectState{const ids=new Set<string>();for(const h of histories){if(h.projectId!==project.metadata.id)throw new Error("Project version history belongs to another project.");if(ids.has(h.bookId))throw new Error(`Duplicate version history for book \"${h.bookId}\".`);ids.add(h.bookId);for(const v of h.versions)if(v.projectId!==project.metadata.id||v.bookId!==h.bookId)throw new Error("Version history contains an incorrectly scoped version.");}return{...project,metadata:{...project.metadata,updatedAt:now},bookVersionHistories:JSON.parse(JSON.stringify(histories))};}
export function withProjectAuthorDecisions(project:ProjectState,decisions:readonly AuthorDecision[],now=new Date().toISOString()):ProjectState{const ids=new Set<string>();for(const d of decisions){if(d.projectId!==project.metadata.id)throw new Error("Project author decision belongs to another project.");if(ids.has(d.id))throw new Error(`Duplicate author decision id \"${d.id}\".`);ids.add(d.id);}return{...project,metadata:{...project.metadata,updatedAt:now},authorDecisions:JSON.parse(JSON.stringify(decisions))};}
export function withProjectSeries(project:ProjectState,series:readonly SeriesState[],now=new Date().toISOString()):ProjectState{const ids=new Set<string>();for(const s of series){if(s.projectId!==project.metadata.id)throw new Error("Project series belongs to another project.");if(ids.has(s.id))throw new Error(`Duplicate series id \"${s.id}\".`);ids.add(s.id);}return{...project,metadata:{...project.metadata,updatedAt:now},series:JSON.parse(JSON.stringify(series))};}
export function withProjectVoiceProfiles(project:ProjectState,profiles:readonly VoiceProfile[],now=new Date().toISOString()):ProjectState{const ids=new Set<string>();for(const p of profiles){if(p.projectId!==project.metadata.id)throw new Error("Project voice profile belongs to another project.");if(ids.has(p.id))throw new Error(`Duplicate voice profile id \"${p.id}\".`);ids.add(p.id);}return{...project,metadata:{...project.metadata,updatedAt:now},voiceProfiles:JSON.parse(JSON.stringify(profiles))};}
export function withProjectCollaborationMode(project:ProjectState,mode:import("./collaboration-health-memory-delivery").AiCollaborationMode,now=new Date().toISOString()):ProjectState{return{...project,metadata:{...project.metadata,updatedAt:now},collaborationMode:mode};}
export function withProjectHealth(project:ProjectState,health:ProjectHealth,now=new Date().toISOString()):ProjectState{if(health.projectId!==project.metadata.id)throw new Error("Project health belongs to another project.");return{...project,metadata:{...project.metadata,updatedAt:now},projectHealth:JSON.parse(JSON.stringify(health))};}
export function withProjectRelationshipMemories(project:ProjectState,records:readonly MemoryRelationship[],now=new Date().toISOString()):ProjectState{const ids=new Set<string>();for(const r of records){if(r.projectId!==project.metadata.id)throw new Error("Relationship memory belongs to another project.");if(ids.has(r.id))throw new Error(`Duplicate relationship memory id \"${r.id}\".`);ids.add(r.id);}return{...project,metadata:{...project.metadata,updatedAt:now},relationshipMemories:JSON.parse(JSON.stringify(records))};}
export function withProjectDeliveryAudit(project:ProjectState,audit:DeliveryAuditReport,now=new Date().toISOString()):ProjectState{if(audit.projectId!==project.metadata.id)throw new Error("Delivery audit belongs to another project.");return{...project,metadata:{...project.metadata,updatedAt:now},deliveryAudit:JSON.parse(JSON.stringify(audit))};}
export function withProjectBookGenome(project:ProjectState,genome:BookGenome,now=new Date().toISOString()):ProjectState{if(genome.projectId!==project.metadata.id)throw new Error("Book Genome belongs to another project.");return{...project,metadata:{...project.metadata,updatedAt:now},bookGenome:JSON.parse(JSON.stringify(genome))};}
export function withProjectContentProvenance(project:ProjectState,records:readonly ContentProvenance[],now=new Date().toISOString()):ProjectState{const ids=new Set<string>();for(const r of records){if(r.projectId!==project.metadata.id)throw new Error("Content provenance belongs to another project.");if(ids.has(r.id))throw new Error(`Duplicate content provenance id \"${r.id}\".`);ids.add(r.id);}return{...project,metadata:{...project.metadata,updatedAt:now},contentProvenance:JSON.parse(JSON.stringify(records))};}
export function withProjectVoiceInputs(project:ProjectState,records:readonly VoiceInputRecord[],now=new Date().toISOString()):ProjectState{const ids=new Set<string>();for(const r of records){if(r.projectId!==project.metadata.id)throw new Error("Voice input belongs to another project.");if(ids.has(r.id))throw new Error(`Duplicate voice input id \"${r.id}\".`);ids.add(r.id);}return{...project,metadata:{...project.metadata,updatedAt:now},voiceInputs:JSON.parse(JSON.stringify(records))};}
export function withProjectSecurity(project:ProjectState,policy:SecurityPolicy,audit:readonly SecurityAuditEntry[]=[],now=new Date().toISOString()):ProjectState{if(policy.projectId!==project.metadata.id||audit.some(a=>a.projectId!==project.metadata.id))throw new Error("Security state belongs to another project.");return{...project,metadata:{...project.metadata,updatedAt:now},securityPolicy:JSON.parse(JSON.stringify(policy)),securityAudit:JSON.parse(JSON.stringify(audit))};}
export function withProjectFinalProductStatus(project:ProjectState,status:FinalProductStatus,now=new Date().toISOString()):ProjectState{if(status.projectId!==project.metadata.id)throw new Error("Project final-product status belongs to another project.");return{...project,metadata:{...project.metadata,updatedAt:now},finalProductStatus:JSON.parse(JSON.stringify(status))};}
function cloneMemory(m:MemoryRecord):MemoryRecord{return{...m,provenance:m.provenance.map(p=>({...p})),relatedMemoryIds:[...m.relatedMemoryIds],relevanceTags:[...m.relevanceTags]};}
function cloneCharacter(c:CharacterRecord):CharacterRecord{return validateCharacterRecord(JSON.parse(JSON.stringify(c)));}
