import type { CharacterRecord } from "./character-bible";
import { validateCharacterRecord } from "./character-bible";
import type { VisualCharacterIdentity } from "./character-visual-continuity";
import { validateVisualCharacterIdentity } from "./character-visual-continuity";
import type { IllustrationAssetLibraryState } from "./illustration-asset-library";
import { validateIllustrationAssetLibraryState } from "./illustration-asset-library";
import type { BookCoverPlan } from "./book-cover-studio";
import { calculateKdpCoverLayout, validatePublishingConfiguration } from "./book-cover-studio";
import type { PublishingReadinessReport } from "./publishing-readiness";
import { validatePublishingReadinessReport } from "./publishing-readiness";
import type { MemoryRecord } from "./memory";

export const PROJECT_FORMAT_VERSION = 2 as const;
export type ProjectStatus = "active" | "archived";
export interface ProjectMetadata { readonly id: string; readonly title: string; readonly createdAt: string; readonly updatedAt: string; readonly status: ProjectStatus; }
export interface ProjectState { readonly formatVersion: typeof PROJECT_FORMAT_VERSION; readonly metadata: ProjectMetadata; readonly memories: readonly MemoryRecord[]; readonly characters?: readonly CharacterRecord[]; readonly visualIdentities?: readonly VisualCharacterIdentity[]; readonly illustrationAssetLibrary?: IllustrationAssetLibraryState; readonly bookCoverPlans?: readonly BookCoverPlan[]; readonly publishingReadinessReports?: readonly PublishingReadinessReport[]; }
export function createProject(input: { id: string; title: string; now?: string }): ProjectState { if (!input.id.trim()) throw new Error("Project id is required."); if (!input.title.trim()) throw new Error("Project title is required."); const now = input.now ?? new Date().toISOString(); return { formatVersion: PROJECT_FORMAT_VERSION, metadata: { id: input.id, title: input.title.trim(), createdAt: now, updatedAt: now, status: "active" }, memories: [] }; }
export function touchProject(project: ProjectState, now = new Date().toISOString()): ProjectState { return { ...project, metadata: { ...project.metadata, updatedAt: now } }; }
export function withProjectMemories(project: ProjectState, memories: readonly MemoryRecord[], now = new Date().toISOString()): ProjectState { if (memories.some((memory) => memory.projectId !== project.metadata.id)) throw new Error("Project memory state contains a memory from another project."); const ids = new Set<string>(); for (const memory of memories) { if (ids.has(memory.id)) throw new Error(`Duplicate memory id \"${memory.id}\" in project state.`); ids.add(memory.id); } return { ...project, metadata: { ...project.metadata, updatedAt: now }, memories: memories.map(cloneMemory) }; }
export function withProjectCharacters(project: ProjectState, characters: readonly CharacterRecord[], now = new Date().toISOString()): ProjectState { if (characters.some((character) => character.projectId !== project.metadata.id)) throw new Error("Project character state contains a character from another project."); const ids = new Set<string>(); const validated = characters.map(validateCharacterRecord); for (const character of validated) { if (ids.has(character.id)) throw new Error(`Duplicate character id \"${character.id}\" in project state.`); ids.add(character.id); } return { ...project, metadata: { ...project.metadata, updatedAt: now }, characters: validated.map(cloneCharacter) }; }
export function withProjectVisualIdentities(project: ProjectState, visualIdentities: readonly VisualCharacterIdentity[], now = new Date().toISOString()): ProjectState { if (visualIdentities.some((identity) => identity.projectId !== project.metadata.id)) throw new Error("Project visual identity state contains an identity from another project."); const ids = new Set<string>(); const characters = new Set<string>(); const validated = visualIdentities.map(validateVisualCharacterIdentity); for (const identity of validated) { if (ids.has(identity.id)) throw new Error(`Duplicate visual identity id \"${identity.id}\" in project state.`); ids.add(identity.id); if (characters.has(identity.characterId)) throw new Error(`Duplicate visual identity for character \"${identity.characterId}\" in project state.`); characters.add(identity.characterId); } return { ...project, metadata: { ...project.metadata, updatedAt: now }, visualIdentities: validated.map(cloneVisualIdentity) }; }
export function withProjectIllustrationAssetLibrary(project: ProjectState, library: IllustrationAssetLibraryState, now = new Date().toISOString()): ProjectState { const validated = validateIllustrationAssetLibraryState(library); if (validated.projectId !== project.metadata.id) throw new Error("Project illustration asset library belongs to another project."); return { ...project, metadata: { ...project.metadata, updatedAt: now }, illustrationAssetLibrary: cloneIllustrationAssetLibrary(validated) }; }
export function withProjectBookCoverPlans(project: ProjectState, plans: readonly BookCoverPlan[], now = new Date().toISOString()): ProjectState { const ids = new Set<string>(); const validated = plans.map((plan) => { if (plan.projectId !== project.metadata.id) throw new Error("Project book cover plan belongs to another project."); if (ids.has(plan.id)) throw new Error(`Duplicate book cover plan id \"${plan.id}\" in project state.`); ids.add(plan.id); validatePublishingConfiguration(plan.publishing); const expected = calculateKdpCoverLayout(plan.publishing); if (expected.dimensions.widthInches !== plan.dimensions.widthInches || expected.dimensions.heightInches !== plan.dimensions.heightInches) throw new Error(`Book cover plan \"${plan.id}\" contains invalid calculated dimensions.`); return cloneBookCoverPlan(plan); }); return { ...project, metadata: { ...project.metadata, updatedAt: now }, bookCoverPlans: validated }; }
export function withProjectPublishingReadinessReports(project: ProjectState, reports: readonly PublishingReadinessReport[], now = new Date().toISOString()): ProjectState { const ids = new Set<string>(); const validated = reports.map(validatePublishingReadinessReport); for (const report of validated) { if (report.projectId !== project.metadata.id) throw new Error("Project publishing readiness report belongs to another project."); if (ids.has(report.id)) throw new Error(`Duplicate publishing readiness report id \"${report.id}\" in project state.`); ids.add(report.id); } return { ...project, metadata: { ...project.metadata, updatedAt: now }, publishingReadinessReports: validated.map(clonePublishingReadinessReport) }; }
function cloneMemory(memory: MemoryRecord): MemoryRecord { return { ...memory, provenance: memory.provenance.map((item) => ({ ...item })), relatedMemoryIds: [...memory.relatedMemoryIds], relevanceTags: [...memory.relevanceTags] }; }
function cloneCharacter(character: CharacterRecord): CharacterRecord { return validateCharacterRecord(JSON.parse(JSON.stringify(character))); }
function cloneVisualIdentity(identity: VisualCharacterIdentity): VisualCharacterIdentity { return validateVisualCharacterIdentity(JSON.parse(JSON.stringify(identity))); }
function cloneIllustrationAssetLibrary(library: IllustrationAssetLibraryState): IllustrationAssetLibraryState { return validateIllustrationAssetLibraryState(JSON.parse(JSON.stringify(library))); }
function cloneBookCoverPlan(plan: BookCoverPlan): BookCoverPlan { return JSON.parse(JSON.stringify(plan)) as BookCoverPlan; }
function clonePublishingReadinessReport(report: PublishingReadinessReport): PublishingReadinessReport { return validatePublishingReadinessReport(JSON.parse(JSON.stringify(report))); }
