export const PROJECT_PACKAGE_FORMAT_VERSION = 1 as const;
export const PROJECT_PACKAGE_NAME = "AUTHOR'S FORGE PROJECT" as const;
export interface ProjectPackageManifest { readonly formatVersion:typeof PROJECT_PACKAGE_FORMAT_VERSION; readonly packageName:typeof PROJECT_PACKAGE_NAME; readonly projectId:string; readonly exportedAt:string; readonly paths:readonly string[]; }
export interface ForgeProjectPackage { readonly manifest:ProjectPackageManifest; readonly projectState:unknown; readonly files:readonly ProjectPackageFile[]; }
export interface ProjectPackageFile { readonly path:string; readonly content:string; readonly mediaType:string; readonly sha256:string; }
const text=(v:unknown,label:string)=>{if(typeof v!=="string"||!v.trim())throw new Error(`${label} is required.`);return v.trim();};
export function createProjectPackage(input:{projectId:string;projectState:unknown;files?:readonly ProjectPackageFile[];exportedAt?:string}):ForgeProjectPackage{const projectId=text(input.projectId,"Project id");const files=(input.files??[]).map(validatePackageFile);const seen=new Set<string>();for(const f of files){if(seen.has(f.path))throw new Error(`Duplicate package path "${f.path}".`);seen.add(f.path);}return{manifest:{formatVersion:PROJECT_PACKAGE_FORMAT_VERSION,packageName:PROJECT_PACKAGE_NAME,projectId,exportedAt:input.exportedAt??new Date().toISOString(),paths:files.map(f=>f.path)},projectState:JSON.parse(JSON.stringify(input.projectState)),files:files.map(f=>({...f}))};}
export function validateProjectPackage(pkg:ForgeProjectPackage):ForgeProjectPackage{if(pkg.manifest.formatVersion!==PROJECT_PACKAGE_FORMAT_VERSION)throw new Error("Unsupported project package format version.");text(pkg.manifest.projectId,"Package project id");if(!Number.isFinite(Date.parse(pkg.manifest.exportedAt)))throw new Error("Package exportedAt must be an ISO timestamp.");if(!Array.isArray(pkg.manifest.paths)||!Array.isArray(pkg.files))throw new Error("Project package manifest and files must be arrays.");const validated=pkg.files.map(validatePackageFile);const paths=validated.map(f=>f.path);if(JSON.stringify(paths)!==JSON.stringify(pkg.manifest.paths))throw new Error("Package manifest paths do not match package files.");return JSON.parse(JSON.stringify({...pkg,manifest:{...pkg.manifest,paths:[...paths]},files:validated})) as ForgeProjectPackage;}
function validatePackageFile(file:ProjectPackageFile):ProjectPackageFile{const path=text(file.path,"Package file path");if(path.startsWith("/")||path.includes(".."))throw new Error("Package file paths must be relative and traversal-safe.");return{path,content:text(file.content,"Package file content"),mediaType:text(file.mediaType,"Package media type"),sha256:text(file.sha256,"Package file sha256")};}
export function serializeProjectPackage(pkg:ForgeProjectPackage):string{return JSON.stringify(validateProjectPackage(pkg),null,2);}
export function deserializeProjectPackage(serialized:string):ForgeProjectPackage{try{return validateProjectPackage(JSON.parse(serialized) as ForgeProjectPackage);}catch(error){throw new Error(`Invalid Forge project package: ${error instanceof Error?error.message:"unknown error"}`);}}
