export const SERIES_FORMAT_VERSION = 1 as const;
export interface SeriesState { readonly id:string; readonly projectId:string; readonly name:string; readonly bookIds:readonly string[]; readonly sharedCharacters:readonly string[]; readonly worldRules:readonly string[]; readonly visualIdentityIds:readonly string[]; readonly locations:readonly string[]; readonly terminology:readonly string[]; readonly history:readonly string[]; readonly unresolvedThreads:readonly string[]; readonly timeline:readonly SeriesTimelineEvent[]; }
export interface SeriesTimelineEvent { readonly id:string; readonly date:string; readonly bookId:string; readonly description:string; }
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
const req=(v:string,n:string)=>{if(typeof v!=="string"||!v.trim())throw new Error(`${n} is required.`);return v.trim();};
const unique=(xs:readonly string[],n:string)=>{const out=[...new Set(xs.map(x=>req(x,n)))];if(out.length!==xs.length)throw new Error(`Duplicate ${n.toLowerCase()} in series state.`);return out;};
export function createSeries(input:{id?:string;projectId:string;name:string;bookIds?:readonly string[];sharedCharacters?:readonly string[];worldRules?:readonly string[];visualIdentityIds?:readonly string[];locations?:readonly string[];terminology?:readonly string[];history?:readonly string[];unresolvedThreads?:readonly string[];timeline?:readonly SeriesTimelineEvent[]}):SeriesState{return clone({id:input.id??`series_${Date.now()}_${Math.random().toString(36).slice(2,9)}`,projectId:req(input.projectId,"Project id"),name:req(input.name,"Series name"),bookIds:unique(input.bookIds??[],"book id"),sharedCharacters:unique(input.sharedCharacters??[],"character id"),worldRules:unique(input.worldRules??[],"world rule"),visualIdentityIds:unique(input.visualIdentityIds??[],"visual identity id"),locations:unique(input.locations??[],"location"),terminology:unique(input.terminology??[],"term"),history:unique(input.history??[],"history item"),unresolvedThreads:unique(input.unresolvedThreads??[],"unresolved thread"),timeline:[...(input.timeline??[]) ]});}
export function validateSeriesState(v:SeriesState):SeriesState{req(v.id,"Series id");req(v.projectId,"Project id");req(v.name,"Series name");unique(v.bookIds,"book id");unique(v.sharedCharacters,"character id");unique(v.worldRules,"world rule");unique(v.visualIdentityIds,"visual identity id");unique(v.locations,"location");unique(v.terminology,"term");unique(v.history,"history item");unique(v.unresolvedThreads,"unresolved thread");for(const e of v.timeline){req(e.id,"Timeline event id");req(e.bookId,"Timeline book id");req(e.date,"Timeline date");req(e.description,"Timeline description");}return clone(v);}
export function addBookToSeries(series:SeriesState,bookId:string):SeriesState{req(bookId,"Book id");if(series.bookIds.includes(bookId))throw new Error(`Book "${bookId}" is already in the series.`);return validateSeriesState({...series,bookIds:[...series.bookIds,bookId]});}
export function addSeriesTimelineEvent(series:SeriesState,event:SeriesTimelineEvent):SeriesState{if(series.timeline.some(e=>e.id===event.id))throw new Error(`Timeline event "${event.id}" already exists.`);if(!series.bookIds.includes(event.bookId))throw new Error(`Timeline event references book "${event.bookId}" outside the series.`);return validateSeriesState({...series,timeline:[...series.timeline,event]});}
