export const VISUAL_CONTINUITY_VERSION = 1 as const;
export const VISUAL_STYLE_MODES = ['storybook','watercolor','gouache','digital-painting','graphic-novel','comic','anime','cinematic','photoreal','ink','pencil','linocut','collage','3d-render','custom'] as const;
export type VisualStyleMode = typeof VISUAL_STYLE_MODES[number];
export type VisualAssetRole = 'character-master'|'character-angle'|'expression-sheet'|'style-master'|'location-master'|'prop-master'|'scene-art'|'cover-art';
export interface VisualReferenceAsset { readonly id:string; readonly role:VisualAssetRole; readonly uri:string; readonly characterId?:string; readonly sceneId?:string; readonly styleId?:string; readonly tags:readonly string[]; readonly approved:boolean; readonly createdAt:string; }
export interface CharacterVisualLock { readonly characterId:string; readonly name:string; readonly immutableTraits:readonly string[]; readonly signatureItems:readonly string[]; readonly referenceAssetIds:readonly string[]; readonly allowedStyleModes:readonly VisualStyleMode[]; }
export interface VisualStyleLock { readonly id:string; readonly mode:VisualStyleMode; readonly description:string; readonly palette:readonly string[]; readonly lighting:string; readonly cameraLanguage:string; readonly negativePrompt?:string; readonly referenceAssetIds:readonly string[]; }
export interface VisualSceneBrief { readonly sceneId:string; readonly characterIds:readonly string[]; readonly locationId?:string; readonly action:string; readonly composition:string; readonly mood:string; readonly aspectRatio:string; readonly textElements:readonly string[]; }
export interface VisualGenerationPlan { readonly version:typeof VISUAL_CONTINUITY_VERSION; readonly scene:VisualSceneBrief; readonly characterLocks:readonly CharacterVisualLock[]; readonly styleLock:VisualStyleLock; readonly references:readonly VisualReferenceAsset[]; readonly prompt:string; readonly negativePrompt:string; readonly consistencyRules:readonly string[]; }
export function buildVisualGenerationPlan(input:{scene:VisualSceneBrief;characters:readonly CharacterVisualLock[];style:VisualStyleLock;references:readonly VisualReferenceAsset[]}):VisualGenerationPlan {
 const characterLocks=input.characters.filter(c=>input.scene.characterIds.includes(c.characterId));
 const references=input.references.filter(r=>r.approved&&(r.styleId===input.style.id||(r.characterId!==undefined&&input.scene.characterIds.includes(r.characterId))||r.sceneId===input.scene.sceneId));
 const identity=characterLocks.map(c=>`${c.name}: ${c.immutableTraits.join(', ')}${c.signatureItems.length?`; signature items: ${c.signatureItems.join(', ')}`:''}`).join(' | ');
 const prompt=[identity,`Action: ${input.scene.action}`,`Composition: ${input.scene.composition}`,`Mood: ${input.scene.mood}`,`Style: ${input.style.description}`,`Palette: ${input.style.palette.join(', ')}`,`Lighting: ${input.style.lighting}`,`Camera: ${input.style.cameraLanguage}`,input.scene.textElements.length?`Readable text: ${input.scene.textElements.join('; ')}`:''].filter(Boolean).join('\n');
 const negativePrompt=[input.style.negativePrompt,'character identity drift, changed hair, changed eye color, missing signature item, merged faces, duplicate limbs, extra fingers, inconsistent costume, accidental text, watermark, logo'].filter(Boolean).join(', ');
 const consistencyRules=['Character references define identity; scene text defines action.','Style reference defines visual language; canonical character traits are immutable constraints.','Use approved master references rather than chaining from an unapproved generation.','Generate exact cover typography as editable layout text when possible.','Reject output when identity, wardrobe, style, composition, or artifact checks fail.'];
 return Object.freeze({version:VISUAL_CONTINUITY_VERSION,scene:input.scene,characterLocks,styleLock:input.style,references,prompt,negativePrompt,consistencyRules});
}
export function scoreVisualContinuity(input:{expectedCharacterTraits:readonly string[];observedCharacterTraits:readonly string[];expectedStyleTags:readonly string[];observedStyleTags:readonly string[];requiredSignatureItems?:readonly string[];observedSignatureItems?:readonly string[]}):{score:number;passed:boolean;failures:readonly string[]} {
 const failures:string[]=[]; const traits=new Set(input.observedCharacterTraits.map(normalize)); const styles=new Set(input.observedStyleTags.map(normalize)); const items=new Set((input.observedSignatureItems??[]).map(normalize));
 const traitHits=input.expectedCharacterTraits.filter(x=>traits.has(normalize(x))).length; const styleHits=input.expectedStyleTags.filter(x=>styles.has(normalize(x))).length; const required=input.requiredSignatureItems??[]; const itemHits=required.filter(x=>items.has(normalize(x))).length;
 if(traitHits<input.expectedCharacterTraits.length) failures.push('character traits drifted'); if(styleHits<input.expectedStyleTags.length) failures.push('style drifted'); if(itemHits<required.length) failures.push('signature item drifted');
 const total=input.expectedCharacterTraits.length+input.expectedStyleTags.length+required.length; return {score:total?Math.round(((traitHits+styleHits+itemHits)/total)*100):0,passed:failures.length===0,failures};
}
function normalize(value:string):string{return value.trim().toLowerCase().replace(/\s+/g,' ');}
