export const VISUAL_CONTINUITY_VERSION = 2 as const;
export const VISUAL_STYLE_MODES = ['storybook','watercolor','gouache','digital-painting','graphic-novel','comic','comic-book-artist','manga','anime','cinematic','photoreal','ink','pencil','linocut','collage','3d-render','custom'] as const;
export type VisualStyleMode = typeof VISUAL_STYLE_MODES[number];
export type VisualAssetRole = 'character-master'|'character-turnaround'|'character-angle'|'expression-sheet'|'costume-sheet'|'style-master'|'location-master'|'prop-master'|'storyboard'|'panel-art'|'page-art'|'scene-art'|'cover-art';

export interface VisualReferenceAsset { readonly id:string; readonly role:VisualAssetRole; readonly uri:string; readonly characterId?:string; readonly sceneId?:string; readonly styleId?:string; readonly pageId?:string; readonly tags:readonly string[]; readonly approved:boolean; readonly createdAt:string; }
export interface CharacterVisualLock { readonly characterId:string; readonly name:string; readonly immutableTraits:readonly string[]; readonly signatureItems:readonly string[]; readonly costumeRules:readonly string[]; readonly referenceAssetIds:readonly string[]; readonly allowedStyleModes:readonly VisualStyleMode[]; }
export interface VisualStyleLock { readonly id:string; readonly mode:VisualStyleMode; readonly description:string; readonly palette:readonly string[]; readonly lighting:string; readonly cameraLanguage:string; readonly linework?:string; readonly rendering?:string; readonly negativePrompt?:string; readonly referenceAssetIds:readonly string[]; }
export interface VisualSceneBrief { readonly sceneId:string; readonly characterIds:readonly string[]; readonly locationId?:string; readonly action:string; readonly composition:string; readonly mood:string; readonly aspectRatio:string; readonly textElements:readonly string[]; readonly panelCount?:number; }
export interface VisualGenerationPlan { readonly version:typeof VISUAL_CONTINUITY_VERSION; readonly scene:VisualSceneBrief; readonly characterLocks:readonly CharacterVisualLock[]; readonly styleLock:VisualStyleLock; readonly references:readonly VisualReferenceAsset[]; readonly prompt:string; readonly negativePrompt:string; readonly consistencyRules:readonly string[]; }

export function buildVisualGenerationPlan(input:{scene:VisualSceneBrief;characters:readonly CharacterVisualLock[];style:VisualStyleLock;references:readonly VisualReferenceAsset[]}):VisualGenerationPlan {
 const characterLocks=input.characters.filter(c=>input.scene.characterIds.includes(c.characterId));
 const references=input.references.filter(r=>r.approved&&(r.styleId===input.style.id||(r.characterId!==undefined&&input.scene.characterIds.includes(r.characterId))||r.sceneId===input.scene.sceneId));
 const identity=characterLocks.map(c=>`${c.name}: ${c.immutableTraits.join(', ')}${c.signatureItems.length?`; signature items: ${c.signatureItems.join(', ')}`:''}${c.costumeRules.length?`; costume rules: ${c.costumeRules.join(', ')}`:''}`).join(' | ');
 const comicDirection=input.style.mode==='comic-book-artist'?'Comic-book production: sequential visual storytelling, readable silhouettes, intentional panel composition, expressive faces and poses, controlled inking, stable character proportions, production-ready linework.':'';
 const prompt=[identity,`Action: ${input.scene.action}`,`Composition: ${input.scene.composition}`,`Mood: ${input.scene.mood}`,`Style: ${input.style.description}`,`Palette: ${input.style.palette.join(', ')}`,`Lighting: ${input.style.lighting}`,`Camera: ${input.style.cameraLanguage}`,input.style.linework?`Linework: ${input.style.linework}`:'',input.style.rendering?`Rendering: ${input.style.rendering}`:'',comicDirection,input.scene.panelCount?`Panels: ${input.scene.panelCount}`:'',input.scene.textElements.length?`Editable text elements: ${input.scene.textElements.join('; ')}`:''].filter(Boolean).join('\n');
 const negativePrompt=[input.style.negativePrompt,'character identity drift, changed hair, changed eye color, missing signature item, merged faces, duplicate limbs, extra fingers, inconsistent costume, inconsistent proportions, accidental text, watermark, logo'].filter(Boolean).join(', ');
 const consistencyRules=['Character references define identity; scene text defines action.','Canonical character traits, signature items, costume rules, and approved proportions are immutable generation constraints.','Style references define visual language; do not replace them with unrelated per-scene style synonyms.','Use approved master/turnaround references rather than chaining from an unapproved generation.','Keep exact cover and comic lettering as editable layout elements whenever typography accuracy matters.','For sequential art, preserve character identity, costume, props, camera geography, lighting logic, and visual style across adjacent panels.','Reject or revise output when identity, wardrobe, anatomy, style, composition, text, or production-quality checks fail.'];
 return Object.freeze({version:VISUAL_CONTINUITY_VERSION,scene:input.scene,characterLocks,styleLock:input.style,references,prompt,negativePrompt,consistencyRules});
}

export function scoreVisualContinuity(input:{expectedCharacterTraits:readonly string[];observedCharacterTraits:readonly string[];expectedStyleTags:readonly string[];observedStyleTags:readonly string[];requiredSignatureItems?:readonly string[];observedSignatureItems?:readonly string[];expectedCostumeRules?:readonly string[];observedCostumeRules?:readonly string[]}):{score:number;passed:boolean;failures:readonly string[]} {
 const failures:string[]=[]; const traits=new Set(input.observedCharacterTraits.map(normalize)); const styles=new Set(input.observedStyleTags.map(normalize)); const items=new Set((input.observedSignatureItems??[]).map(normalize)); const costumes=new Set((input.observedCostumeRules??[]).map(normalize));
 const traitHits=input.expectedCharacterTraits.filter(x=>traits.has(normalize(x))).length; const styleHits=input.expectedStyleTags.filter(x=>styles.has(normalize(x))).length; const required=input.requiredSignatureItems??[]; const itemHits=required.filter(x=>items.has(normalize(x))).length; const costume=input.expectedCostumeRules??[]; const costumeHits=costume.filter(x=>costumes.has(normalize(x))).length;
 if(traitHits<input.expectedCharacterTraits.length) failures.push('character traits drifted'); if(styleHits<input.expectedStyleTags.length) failures.push('style drifted'); if(itemHits<required.length) failures.push('signature item drifted'); if(costumeHits<costume.length) failures.push('costume rules drifted');
 const total=input.expectedCharacterTraits.length+input.expectedStyleTags.length+required.length+costume.length; return {score:total?Math.round(((traitHits+styleHits+itemHits+costumeHits)/total)*100):0,passed:failures.length===0,failures};
}
function normalize(value:string):string{return value.trim().toLowerCase().replace(/\s+/g,' ');}
