export type AiTask = 'writing' | 'editing' | 'research' | 'vision' | 'cover' | 'marketing' | 'tool-use' | 'voice-preservation' | 'continuity';
export interface AiModelCapabilities { readonly contextWindow?: number; readonly maxOutputTokens?: number; readonly reasoning?: boolean; readonly vision?: boolean; readonly streaming?: boolean; readonly toolCalls?: boolean; readonly creativeWriting?: boolean; readonly instructionFollowing?: boolean; readonly longContext?: boolean; }
export interface AiModelResource { readonly provider: string; readonly model: string; readonly capabilities: AiModelCapabilities; readonly configured: boolean; readonly healthy?: boolean; readonly estimatedInputCostPerMillion?: number; readonly estimatedOutputCostPerMillion?: number; readonly remainingQuota?: number; readonly usedTokens?: number; readonly quotaLimit?: number; readonly quotaResetAt?: string; readonly cooldownUntil?: string; readonly consecutiveFailures?: number; readonly latencyMs?: number; }
export interface AiModelSelectionRequest { readonly task: AiTask; readonly minimumContextWindow?: number; readonly minimumOutputTokens?: number; readonly requiresReasoning?: boolean; readonly requiresVision?: boolean; readonly requiresToolCalls?: boolean; readonly requiresStreaming?: boolean; readonly requiresCreativeWriting?: boolean; readonly requiresInstructionFollowing?: boolean; readonly preferProvider?: string; readonly preferModel?: string; readonly preferredProviders?: readonly string[]; readonly maxInputCostPerMillion?: number; readonly maxOutputCostPerMillion?: number; readonly estimatedInputTokens?: number; readonly estimatedOutputTokens?: number; readonly quotaSafetyFraction?: number; readonly now?: string; }
export interface AiModelSelection { readonly resource: AiModelResource; readonly score: number; readonly reasons: readonly string[]; }
export interface AiRoutingTelemetry { readonly provider:string; readonly model:string; readonly consecutiveFailures:number; readonly totalTokens:number; readonly lastLatencyMs?:number; readonly cooldownUntil?:string; }

export class AiModelBroker {
 private resources: AiModelResource[]=[];
 setResources(resources:readonly AiModelResource[]):void { this.resources=resources.filter(r=>r.configured); }
 applyRoutingTelemetry(telemetry:readonly AiRoutingTelemetry[]):void { const byKey=new Map(telemetry.map(t=>[`${t.provider}::${t.model}`,t])); this.resources=this.resources.map(r=>{const t=byKey.get(`${r.provider}::${r.model}`);return t?{...r,consecutiveFailures:t.consecutiveFailures,usedTokens:Math.max(r.usedTokens??0,t.totalTokens),latencyMs:t.lastLatencyMs,cooldownUntil:t.cooldownUntil}:r;}); }
 listResources():AiModelResource[]{ return this.resources.map(r=>({...r,capabilities:{...r.capabilities}})); }
 select(request:AiModelSelectionRequest):AiModelSelection { return this.rank(request)[0] ?? (()=>{throw new Error(`No healthy configured AI model satisfies the ${request.task} requirements.`);})(); }
 rank(request:AiModelSelectionRequest):AiModelSelection[]{
  const safety=Math.min(.99,Math.max(0,request.quotaSafetyFraction??.1)); const estimated=Math.max(0,request.estimatedInputTokens??0)+Math.max(0,request.estimatedOutputTokens??0); const now=Date.parse(request.now??new Date().toISOString());
  const preferredOrder=(request.preferredProviders??[]).map(value=>value.trim().toLowerCase()).filter(Boolean);
  const candidates=this.resources.filter(r=>{ const c=r.capabilities; if(r.healthy===false)return false; if(r.cooldownUntil&&Number.isFinite(now)&&Date.parse(r.cooldownUntil)>now)return false; if(request.minimumContextWindow!==undefined&&(c.contextWindow??0)<request.minimumContextWindow)return false; if(request.minimumOutputTokens!==undefined&&(c.maxOutputTokens??0)<request.minimumOutputTokens)return false; if(request.requiresReasoning&&!c.reasoning)return false; if(request.requiresVision&&!c.vision)return false; if(request.requiresToolCalls&&!c.toolCalls)return false; if(request.requiresStreaming&&!c.streaming)return false; if(request.requiresCreativeWriting&&!c.creativeWriting)return false; if(request.requiresInstructionFollowing&&!c.instructionFollowing)return false; if(request.maxInputCostPerMillion!==undefined&&r.estimatedInputCostPerMillion!==undefined&&r.estimatedInputCostPerMillion>request.maxInputCostPerMillion)return false; if(request.maxOutputCostPerMillion!==undefined&&r.estimatedOutputCostPerMillion!==undefined&&r.estimatedOutputCostPerMillion>request.maxOutputCostPerMillion)return false; const remaining=this.remainingQuota(r); if(remaining!==undefined&&remaining<=0)return false; if(remaining!==undefined&&estimated>0){const reserve=Math.max(estimated,Math.ceil((r.quotaLimit??remaining)*safety)); if(remaining-estimated<reserve)return false;} return true; });
  return candidates.map(r=>{let score=0;const reasons:string[]=[];const c=r.capabilities;const remaining=this.remainingQuota(r);if(r.provider===request.preferProvider){score+=100;reasons.push('preferred provider');}if(r.model===request.preferModel){score+=75;reasons.push('preferred model');}const orderIndex=preferredOrder.indexOf(r.provider.toLowerCase());if(orderIndex>=0){const bonus=Math.max(2,24-orderIndex*4);score+=bonus;reasons.push(`provider order ${orderIndex+1}`);}if(r.healthy===true){score+=25;reasons.push('healthy');}if(r.consecutiveFailures){score-=Math.min(40,r.consecutiveFailures*10);reasons.push(`failure penalty (${r.consecutiveFailures})`);}if(r.latencyMs!==undefined){score+=Math.max(-15,15-Math.floor(r.latencyMs/500));reasons.push(`latency ${r.latencyMs}ms`);}if(remaining!==undefined){score+=10;reasons.push(`quota available (${remaining.toLocaleString()} tokens)`);if(estimated>0)reasons.push('input + output quota reserve protected');if(r.quotaLimit&&r.quotaLimit>0)score+=Math.min(30,Math.round(remaining/r.quotaLimit*30));}if(r.estimatedInputCostPerMillion!==undefined)score+=Math.max(0,20-Math.min(20,r.estimatedInputCostPerMillion));if(request.task==='vision'&&c.vision){score+=30;reasons.push('vision capable');}if((request.task==='tool-use'||request.requiresToolCalls)&&c.toolCalls){score+=30;reasons.push('tool-call capable');}if((request.task==='writing'||request.task==='voice-preservation')&&c.creativeWriting){score+=35;reasons.push('creative-writing capable');}if((request.task==='voice-preservation'||request.requiresInstructionFollowing)&&c.instructionFollowing){score+=25;reasons.push('instruction-following capable');}if(request.task==='continuity'&&c.longContext){score+=35;reasons.push('long-context capable');}if(request.requiresReasoning&&c.reasoning){score+=30;reasons.push('reasoning capable');}if(request.requiresStreaming&&c.streaming){score+=15;reasons.push('streaming capable');}if(c.contextWindow)score+=Math.min(20,Math.floor(c.contextWindow/100000));if(c.maxOutputTokens)score+=Math.min(10,Math.floor(c.maxOutputTokens/10000));return{resource:r,score,reasons};}).sort((a,b)=>b.score-a.score||a.resource.provider.localeCompare(b.resource.provider)||a.resource.model.localeCompare(b.resource.model));
 }
 private remainingQuota(r:AiModelResource):number|undefined{if(r.remainingQuota!==undefined)return Math.max(0,r.remainingQuota);if(r.quotaLimit!==undefined&&r.usedTokens!==undefined)return Math.max(0,r.quotaLimit-r.usedTokens);return undefined;}
}
