import { createBookPositioningReport, type BookPositioningReport, type PositioningComparable, type PositioningAnswer, type PositioningConcepts } from "../domain/book-positioning";
export interface BookPositioningRequest { readonly id:string; readonly projectId:string; readonly bookId?:string; readonly manuscriptContext:string; readonly marketContext?:string; readonly comparableBooks?:readonly PositioningComparable[]; }
export interface BookPositioningProviderRequest { readonly projectId:string; readonly bookId?:string; readonly manuscriptContext:string; readonly marketContext?:string; readonly comparableBooks:readonly PositioningComparable[]; }
export interface BookPositioningProviderResult { readonly positioning:PositioningAnswer; readonly concepts:PositioningConcepts; readonly evidence?:readonly string[]; readonly limitations?:readonly string[]; }
export interface BookPositioningProvider { position(request:BookPositioningProviderRequest):Promise<BookPositioningProviderResult>; }
export class BookPositioningService {
 constructor(private readonly provider:BookPositioningProvider){}
 async create(request:BookPositioningRequest):Promise<BookPositioningReport>{ validate(request); const result=await this.provider.position({...request,projectId:request.projectId.trim(),manuscriptContext:request.manuscriptContext.trim(),comparableBooks:request.comparableBooks??[]}); return createBookPositioningReport({id:request.id,projectId:request.projectId,bookId:request.bookId,positioning:result.positioning,concepts:result.concepts,evidence:result.evidence??[],limitations:result.limitations??[],disclaimer:"Positioning is a strategic interpretation of supplied manuscript and market evidence. It is not a guarantee of reader response, clicks, rankings, sales, revenue, or commercial performance."}); }
}
export class StaticBookPositioningProvider implements BookPositioningProvider { constructor(private readonly result:BookPositioningProviderResult){} async position(_request:BookPositioningProviderRequest):Promise<BookPositioningProviderResult>{return JSON.parse(JSON.stringify(this.result)) as BookPositioningProviderResult;} }
function validate(r:BookPositioningRequest):void{for(const [v,l] of [[r.id,"Positioning id"],[r.projectId,"Positioning project id"],[r.manuscriptContext,"Manuscript context"]] as const)if(typeof v!=="string"||!v.trim())throw new Error(`${l} is required.`);}
