import type { IncomingMessage, ServerResponse } from "node:http";
import { dirname, join } from "node:path";
import { EducationalWorkbookDifferentiationService } from "./educational-workbook-differentiation";
import { EducationalWorkbookDifferentiationProductionService } from "./educational-workbook-differentiation-production";
import { createEducationalAssessmentRoutes } from "./educational-assessment-routes";
import type { EducationalWorkbookOfficeService } from "./educational-workbook-office";
import { WORKBOOK_GRADE_BANDS, WORKBOOK_SUBJECTS, type WorkbookGradeBand, type WorkbookSubject } from "../domain/educational-workbook";
import { FileEducationalWorkbookDifferentiationStore } from "../infrastructure/file-educational-workbook-differentiation-store";
export type EducationalWorkbookDifferentiationRouteHandler=(req:IncomingMessage,res:ServerResponse,url:URL,projectId:string)=>Promise<boolean>;
export function createEducationalWorkbookDifferentiationRoutes(input:{readonly office:EducationalWorkbookOfficeService;readonly storePath:string}):EducationalWorkbookDifferentiationRouteHandler{const storePath=required(input.storePath,"Differentiation store path"),differentiation=new EducationalWorkbookDifferentiationService(input.office,new FileEducationalWorkbookDifferentiationStore(storePath)),production=new EducationalWorkbookDifferentiationProductionService(),assessmentRoutes=createEducationalAssessmentRoutes(join(dirname(storePath),"educational-assessments.json"));return async(req,res,url,projectId)=>{if(await assessmentRoutes(req,res,url,projectId))return true;const base=`/api/projects/${projectId}/workbooks/differentiation`;if(url.pathname===`${base}/readiness`&&req.method==="GET"){json(res,200,await differentiation.readiness({projectId,gradeBand:gradeBand(url.searchParams.get("gradeBand")),activityCountPerVariant:integer(url.searchParams.get("activityCountPerVariant"),10),subjects:subjects(url.searchParams.get("subjects")),standards:strings(url.searchParams.get("standards")),tags:strings(url.searchParams.get("tags"))}));return true}if(url.pathname===`${base}/packs`&&req.method==="GET"){json(res,200,{packs:await differentiation.list(projectId)});return true}if(url.pathname===`${base}/packs`&&req.method==="POST"){const p=await body(req);json(res,201,await differentiation.createPack({id:required(p.id,"Differentiation pack id"),projectId,title:required(p.title,"Differentiation pack title"),gradeBand:gradeBand(p.gradeBand),seed:required(p.seed,"Differentiation seed"),activityCountPerVariant:integer(p.activityCountPerVariant,0),learningObjectives:strings(p.learningObjectives),directions:strings(p.directions),standards:strings(p.standards),tags:strings(p.tags),subjects:subjects(p.subjects),includeAnswerKey:p.includeAnswerKey!==false}));return true}const gm=url.pathname.match(new RegExp(`^${escapeRegExp(base)}/packs/([^/]+)/teacher-guide$`));if(gm&&req.method==="POST"){const pack=await differentiation.get(projectId,decodeURIComponent(gm[1]));if(!pack){json(res,404,{error:"Educational differentiation pack not found."});return true}const p=await body(req);json(res,201,production.renderTeacherGuide({pack,bookId:required(p.bookId,"Teacher guide book id"),author:required(p.author,"Teacher guide author")}));return true}const pm=url.pathname.match(new RegExp(`^${escapeRegExp(base)}/packs/([^/]+)$`));if(pm&&req.method==="GET"){const pack=await differentiation.get(projectId,decodeURIComponent(pm[1]));json(res,pack?200:404,pack??{error:"Educational differentiation pack not found."});return true}return false}}
function json(res:ServerResponse,status:number,value:unknown){res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"});res.end(JSON.stringify(value))}async function body(req:IncomingMessage){let raw="";for await(const chunk of req){raw+=String(chunk);if(raw.length>2*1024*1024)throw new Error("Differentiation request body exceeds 2 MiB limit.")}if(!raw.trim())return{};const p=JSON.parse(raw);if(!p||typeof p!=="object"||Array.isArray(p))throw new Error("JSON object body required.");return p as Record<string,unknown>}function strings(v:unknown):string[]{return Array.isArray(v)?[...new Set(v.filter((i):i is string=>typeof i==="string").map(i=>i.trim()).filter(Boolean))]:typeof v==="string"?[...new Set(v.split(/[\n,]/).map(i=>i.trim()).filter(Boolean))]:[]}function subjects(v:unknown):WorkbookSubject[]{return strings(v).map(i=>{if(!WORKBOOK_SUBJECTS.includes(i as WorkbookSubject))throw new Error(`Unsupported workbook subject "${i}".`);return i as WorkbookSubject})}function gradeBand(v:unknown):WorkbookGradeBand{if(typeof v!=="string"||!WORKBOOK_GRADE_BANDS.includes(v as WorkbookGradeBand))throw new Error("Invalid workbook grade band.");return v as WorkbookGradeBand}function integer(v:unknown,f:number){const n=Number(v);return Number.isInteger(n)?n:f}function required(v:unknown,l:string):string{if(typeof v!=="string"||!v.trim())throw new Error(`${l} is required.`);return v.trim()}function escapeRegExp(v:string):string{return v.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
