import { createCharacterDesignLock, createIllustrationAsset, resolveCharacterDesignLock, reuseIllustrationAsset, updateIllustrationAsset, validateIllustrationAssetLibraryState, type CharacterDesignLock, type CreateCharacterDesignLockInput, type CreateIllustrationAssetInput, type IllustrationAsset, type IllustrationAssetLibraryState, type IllustrationGenerationSettingValue, type UpdateIllustrationAssetInput } from "../domain/illustration-asset-library";

export interface IllustrationAssetQuery { readonly projectId?: string; readonly bookId?: string; readonly chapterId?: string; readonly sceneId?: string; readonly characterId?: string; readonly locationId?: string; readonly approvalStatus?: IllustrationAsset["approvalStatus"]; }

export class IllustrationAssetLibraryService {
  private readonly assets = new Map<string, IllustrationAsset>();
  private readonly locks = new Map<string, CharacterDesignLock>();

  create(input: CreateIllustrationAssetInput): IllustrationAsset { const asset = createIllustrationAsset(input); if (this.assets.has(asset.id)) throw new Error(`Duplicate illustration asset id \"${asset.id}\".`); this.assertProjectAssetUniqueness(asset); this.assets.set(asset.id, asset); return cloneAsset(asset); }
  get(id: string): IllustrationAsset | undefined { const asset = this.assets.get(id); return asset ? cloneAsset(asset) : undefined; }
  require(id: string): IllustrationAsset { const asset = this.assets.get(id); if (!asset) throw new Error(`Illustration asset \"${id}\" not found.`); return cloneAsset(asset); }
  update(input: UpdateIllustrationAssetInput): IllustrationAsset { const existing = this.assets.get(input.id); if (!existing) throw new Error(`Illustration asset \"${input.id}\" not found.`); const updated = updateIllustrationAsset(existing, input); this.assets.set(updated.id, updated); return cloneAsset(updated); }
  reuse(sourceAssetId: string, input: Omit<CreateIllustrationAssetInput, "characterId" | "locationId" | "prompt" | "references" | "style" | "generationSettings" | "version" | "approvalStatus" | "assetUri" | "reusedFromAssetId">): IllustrationAsset { const source = this.require(sourceAssetId); const asset = reuseIllustrationAsset(source, input); if (this.assets.has(asset.id)) throw new Error(`Duplicate illustration asset id \"${asset.id}\".`); this.assertProjectAssetUniqueness(asset); this.assets.set(asset.id, asset); return cloneAsset(asset); }
  list(query: IllustrationAssetQuery = {}): IllustrationAsset[] { return [...this.assets.values()].filter((asset) => (query.projectId === undefined || asset.projectId === query.projectId) && (query.bookId === undefined || asset.bookId === query.bookId) && (query.chapterId === undefined || asset.chapterId === query.chapterId) && (query.sceneId === undefined || asset.sceneId === query.sceneId) && (query.characterId === undefined || asset.characterId === query.characterId) && (query.locationId === undefined || asset.locationId === query.locationId) && (query.approvalStatus === undefined || asset.approvalStatus === query.approvalStatus)).sort((a, b) => a.id.localeCompare(b.id)).map(cloneAsset); }
  lockCharacterDesign(input: CreateCharacterDesignLockInput): CharacterDesignLock { const lock = createCharacterDesignLock(input); if (!this.assets.has(lock.assetId)) throw new Error(`Character design lock references missing asset \"${lock.assetId}\".`); const asset = this.assets.get(lock.assetId)!; if (asset.projectId !== lock.projectId || asset.characterId !== lock.characterId) throw new Error("Character design lock must reference an asset for the same project and character."); if (this.locks.has(lock.id)) throw new Error(`Duplicate character design lock id \"${lock.id}\".`); this.locks.set(lock.id, lock); return cloneLock(lock); }
  resolveCharacterDesign(projectId: string, characterId: string, at?: string): IllustrationAsset | undefined { const lock = resolveCharacterDesignLock(this.state(projectId), characterId, at); return lock ? this.get(lock.assetId) : undefined; }
  listCharacterDesignLocks(projectId?: string): CharacterDesignLock[] { return [...this.locks.values()].filter((lock) => projectId === undefined || lock.projectId === projectId).sort((a, b) => a.effectiveAt.localeCompare(b.effectiveAt) || a.id.localeCompare(b.id)).map(cloneLock); }
  restore(state: IllustrationAssetLibraryState): void { const validated = validateIllustrationAssetLibraryState(state); this.assets.clear(); this.locks.clear(); for (const asset of validated.assets) this.assets.set(asset.id, cloneAsset(asset)); for (const lock of validated.characterDesignLocks) this.locks.set(lock.id, cloneLock(lock)); }
  toPortableState(projectId: string): IllustrationAssetLibraryState { return this.state(projectId); }
  private state(projectId: string): IllustrationAssetLibraryState { const assets = this.list({ projectId }); const characterDesignLocks = this.listCharacterDesignLocks(projectId); return validateIllustrationAssetLibraryState({ formatVersion: 1, projectId, assets, characterDesignLocks }); }
  private assertProjectAssetUniqueness(asset: IllustrationAsset): void { if ([...this.assets.values()].some((existing) => existing.projectId === asset.projectId && existing.assetUri === asset.assetUri && existing.version === asset.version)) throw new Error(`Illustration asset version ${asset.version} already exists for URI \"${asset.assetUri}\".`); }
}
function cloneAsset(asset: IllustrationAsset): IllustrationAsset { return { ...asset, references: asset.references.map((ref) => ({ ...ref })), generationSettings: { ...asset.generationSettings } }; }
function cloneLock(lock: CharacterDesignLock): CharacterDesignLock { return { ...lock }; }
