import { randomUUID } from "node:crypto";
import type { FileSpecializedCreationStore } from "../infrastructure/file-specialized-creation-store";
import type { ProjectMemoryStore } from "./project-memory-store";
import { generateProjectImage,type ImageGenerationResult,type ImageReferenceInput,type ProjectImageGenerationRequest } from "../infrastructure/image-provider";
import type { SpecializedAsset,SpecializedOfficeProject,TcgData } from "../domain/specialized-creation-office";
import { addTcgEvolutionArtworkCandidate,lockTcgEvolutionArtwork,setTcgWorldMapArtwork,tcgGameFramework } from "./specialized-creation-tcg-design";

export type SpecializedImageGenerator=(request:ProjectImageGenerationRequest)=>Promise<ImageGenerationResult>;
export interface SpecializedGeneratedAssetResult { readonly project:SpecializedOfficeProject; readonly asset:SpecializedAsset; readonly image:Pick<ImageGenerationResult,"provider"|"model"|"requestId"|"size"|"quality">; }

export class SpecializedCreationAiAssetService {
  constructor(private readonly store:FileSpecializedCreationStore,private readonly memory:ProjectMemoryStore,private readonly image:SpecializedImageGenerator=generateProjectImage){}

  async generateAsset(input:{forgeProjectId:string;specializedProjectId:string;name:string;prompt:string;kind?:SpecializedAsset["kind"];focus?:string;size?:ProjectImageGenerationRequest["size"];quality?:ProjectImageGenerationRequest["quality"];referenceImages?:readonly ImageReferenceInput[];now?:string}):Promise<SpecializedGeneratedAssetResult>{
    const project=await this.require(input.forgeProjectId,input.specializedProjectId),now=input.now??new Date().toISOString();
    const result=await this.image({memory:this.memory,context:{projectId:input.forgeProjectId,taskMemoryClasses:["author-memory","project-memory","style-memory","visual-identity","research-memory","decision-memory","production-memory"],relevanceTags:["specialized-creation",project.mode,"visual-identity"],queryTerms:[project.title,project.brief,input.focus??input.name],includeWorkingState:true,limit:50},prompt:[`Specialized mode: ${project.mode}`,`Project: ${project.title}`,`Brief: ${project.brief}`,`Asset purpose: ${input.name}`,input.prompt].join("\n"),size:input.size,quality:input.quality,referenceImages:input.referenceImages});
    const dimensions=parseDimensions(result.size),asset:SpecializedAsset=Object.freeze({id:`asset-${randomUUID()}`,projectId:project.id,kind:input.kind??"artwork",name:required(input.name,"Generated asset name"),uri:result.dataUri,mimeType:result.mimeType,...dimensions,source:"generated",sourceReference:required(input.prompt,"Generated asset prompt"),provider:result.provider,model:result.model,...(result.requestId?{requestId:result.requestId}:{}),approved:false,createdAt:now});
    const saved=await this.store.save({...project,assets:[...project.assets,asset],updatedAt:now});return {project:saved,asset,image:{provider:result.provider,model:result.model,...(result.requestId?{requestId:result.requestId}:{}),size:result.size,quality:result.quality}};
  }

  async generateTcgStageArtwork(input:{forgeProjectId:string;specializedProjectId:string;lineId:string;stageId:string;styleDirection?:string;referenceImages?:readonly ImageReferenceInput[];size?:ProjectImageGenerationRequest["size"];quality?:ProjectImageGenerationRequest["quality"];now?:string}):Promise<SpecializedGeneratedAssetResult>{
    const project=await this.requireTcg(input.forgeProjectId,input.specializedProjectId),framework=tcgGameFramework(project.modeData as TcgData),line=framework.characterLines.find(item=>item.id===input.lineId);if(!line)throw new Error(`TCG character line "${input.lineId}" not found.`);const stage=line.stages.find(item=>item.id===input.stageId);if(!stage)throw new Error(`TCG evolution stage "${input.stageId}" not found.`);
    const powers=[...stage.magicalPowers,...stage.physicalPowers].map(power=>`${power.name} (${power.kind}): ${power.description}`).join("; "),prompt=[`Create original trading-card character artwork for ${line.name}, evolution stage ${stage.label}.`,`Life stage: ${stage.lifeStage}${stage.ageLabel?` (${stage.ageLabel})`:""}.`,`Canonical appearance: ${stage.appearance}.`,`Stage description: ${stage.description}.`,`Strengths: ${stage.strengths.join(", ")||"none specified"}.`,`Weaknesses: ${stage.weaknesses.join(", ")||"none specified"}.`,`Powers: ${powers||"none specified"}.`,`Canonical territories: ${stage.territoryIds.join(", ")||"none specified"}.`,line.characterBibleId?`Shared Character Bible id: ${line.characterBibleId}. Preserve approved identity traits from Forge context.`:"",input.referenceImages?.length?"An author-approved character design image is attached as visual continuity reference. Preserve stable facial, silhouette, palette, markings, and identity traits unless this evolution stage explicitly changes them.":"",input.styleDirection?`Art direction: ${input.styleDirection}.`:"","Character art only. No card frame, rules text, title, logo, watermark or collector number."].filter(Boolean).join("\n");
    const generated=await this.generateAsset({forgeProjectId:input.forgeProjectId,specializedProjectId:input.specializedProjectId,name:`${line.name} — ${stage.label} candidate`,prompt,kind:"artwork",focus:line.characterBibleId??line.name,referenceImages:input.referenceImages,size:input.size??"1024x1536",quality:input.quality??"medium",now:input.now});
    const modeData=addTcgEvolutionArtworkCandidate(generated.project.modeData as TcgData,{lineId:line.id,stageId:stage.id,assetId:generated.asset.id});const saved=await this.store.save({...generated.project,modeData,updatedAt:input.now??new Date().toISOString()});return {...generated,project:saved};
  }

  async approveTcgStageArtwork(input:{forgeProjectId:string;specializedProjectId:string;lineId:string;stageId:string;assetId:string;now?:string}):Promise<SpecializedOfficeProject>{
    const project=await this.requireTcg(input.forgeProjectId,input.specializedProjectId),asset=project.assets.find(item=>item.id===input.assetId);if(!asset)throw new Error(`Specialized asset "${input.assetId}" not found.`);if(asset.kind!=="artwork")throw new Error("TCG character design lock requires artwork.");const modeData=lockTcgEvolutionArtwork(project.modeData as TcgData,{lineId:input.lineId,stageId:input.stageId,assetId:input.assetId}),now=input.now??new Date().toISOString(),assets=project.assets.map(item=>item.id===asset.id?{...item,approved:true}:item);return this.store.save({...project,modeData,assets,updatedAt:now});
  }

  async generateTcgWorldMapArtwork(input:{forgeProjectId:string;specializedProjectId:string;mapId:string;styleDirection?:string;size?:ProjectImageGenerationRequest["size"];quality?:ProjectImageGenerationRequest["quality"];now?:string}):Promise<SpecializedGeneratedAssetResult>{
    const project=await this.requireTcg(input.forgeProjectId,input.specializedProjectId),framework=tcgGameFramework(project.modeData as TcgData),map=framework.worldMaps.find(item=>item.id===input.mapId);if(!map)throw new Error(`TCG world map "${input.mapId}" not found.`);const territories=map.territories.map(t=>`${t.name} (${t.biome}) at normalized position ${t.center.x},${t.center.y}; adjacent to ${t.adjacentTerritoryIds.join(", ")||"none"}; resources ${t.resources.join(", ")||"none"}; hazards ${t.hazards.join(", ")||"none"}`).join("\n");const prompt=[`Create original fantasy/science-fiction world-map artwork for the trading card game map "${map.name}".`,`World description: ${map.description}.`,`Respect this canonical territory topology and relative placement:`,territories,input.styleDirection?`Art direction: ${input.styleDirection}.`:"","Map artwork only. Do not invent labels as raster text; Forge overlays editable territory names/markers separately."].filter(Boolean).join("\n");return this.generateAsset({forgeProjectId:input.forgeProjectId,specializedProjectId:input.specializedProjectId,name:`${map.name} map candidate`,prompt,kind:"artwork",focus:map.name,size:input.size??"1536x1024",quality:input.quality??"medium",now:input.now});
  }

  async approveTcgWorldMapArtwork(input:{forgeProjectId:string;specializedProjectId:string;mapId:string;assetId:string;now?:string}):Promise<SpecializedOfficeProject>{const project=await this.requireTcg(input.forgeProjectId,input.specializedProjectId),asset=project.assets.find(item=>item.id===input.assetId);if(!asset)throw new Error(`Specialized asset "${input.assetId}" not found.`);const modeData=setTcgWorldMapArtwork(project.modeData as TcgData,{mapId:input.mapId,assetId:asset.id}),now=input.now??new Date().toISOString(),assets=project.assets.map(item=>item.id===asset.id?{...item,approved:true}:item);return this.store.save({...project,modeData,assets,updatedAt:now});}

  async setAssetApproval(input:{forgeProjectId:string;specializedProjectId:string;assetId:string;approved:boolean;now?:string}):Promise<SpecializedOfficeProject>{const project=await this.require(input.forgeProjectId,input.specializedProjectId);if(!project.assets.some(item=>item.id===input.assetId))throw new Error(`Specialized asset "${input.assetId}" not found.`);const now=input.now??new Date().toISOString();return this.store.save({...project,assets:project.assets.map(item=>item.id===input.assetId?{...item,approved:input.approved}:item),updatedAt:now});}
  private async require(forgeProjectId:string,id:string):Promise<SpecializedOfficeProject>{const project=await this.store.get(forgeProjectId,id);if(!project)throw new Error(`Specialized project "${id}" not found.`);return project;}
  private async requireTcg(forgeProjectId:string,id:string):Promise<SpecializedOfficeProject>{const project=await this.require(forgeProjectId,id);if(project.mode!=="trading-card-game")throw new Error("TCG artwork operation requires trading-card-game mode.");return project;}
}
function parseDimensions(size:ProjectImageGenerationRequest["size"]):{pixelWidth?:number;pixelHeight?:number}{if(!size||size==="auto")return{};const match=size.match(/^(\d+)x(\d+)$/);return match?{pixelWidth:Number(match[1]),pixelHeight:Number(match[2])}:{};}
function required(value:string,label:string):string{if(typeof value!=="string"||!value.trim())throw new Error(`${label} is required.`);return value.trim();}
