import { createHash } from "node:crypto";
import { deflateSync, inflateSync } from "node:zlib";
import type { SpecializedRenderedArtifact } from "./specialized-creation-production-engine";
import type { SpecializedDocument, SpecializedElement, SpecializedOfficeProject, SpecializedSurface } from "../domain/specialized-creation-office";

export function renderEmbeddedSvg(project:SpecializedOfficeProject):SpecializedRenderedArtifact {
  const document=project.documents[0];if(!document||!document.surfaces[0])throw new Error("SVG rendering requires a document surface.");
  const surface=document.surfaces[0],scale=96,w=surface.widthInches*scale,h=surface.heightInches*scale;
  const body=[...surface.elements].sort((a,b)=>a.zIndex-b.zIndex).filter(e=>e.metadata.hidden!==true).map(element=>svgElement(element,project,scale)).join("\n");
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-label="${xml(document.title)}"><rect width="100%" height="100%" fill="white"/>${body}</svg>`;
  return artifact("svg",`${safeName(project.title)}.svg`,"image/svg+xml",Buffer.from(svg,"utf8"),[document.id],1);
}

export function renderEmbeddedPdf(project:SpecializedOfficeProject):SpecializedRenderedArtifact {
  const surfaces=project.documents.flatMap(d=>d.surfaces);if(!surfaces.length)throw new Error("PDF rendering requires surfaces.");
  const builder=new PdfBuilder();const fontId=builder.addText("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");const pageIds:number[]=[];
  for(const surface of surfaces){const imageResources=new Map<string,{name:string;objectId:number}>();let imageIndex=0;
    for(const element of surface.elements.filter(e=>e.kind==="image"&&e.assetId&&e.metadata.hidden!==true)){const asset=project.assets.find(a=>a.id===element.assetId);if(!asset)throw new Error(`Image element ${element.id} references missing asset.`);const key=asset.id;if(imageResources.has(key))continue;const image=decodeImageDataUri(asset.uri);const name=`Im${++imageIndex}`;let objectId:number;if(image.kind==="jpeg"){objectId=builder.addStream(`<< /Type /XObject /Subtype /Image /Width ${image.width} /Height ${image.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${image.data.length} >>`,image.data);}else{let smaskId:number|undefined;if(image.alpha){const alpha=deflateSync(image.alpha);smaskId=builder.addStream(`<< /Type /XObject /Subtype /Image /Width ${image.width} /Height ${image.height} /ColorSpace /DeviceGray /BitsPerComponent 8 /Filter /FlateDecode /Length ${alpha.length} >>`,alpha);}const compressed=deflateSync(image.rgb);objectId=builder.addStream(`<< /Type /XObject /Subtype /Image /Width ${image.width} /Height ${image.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /FlateDecode${smaskId?` /SMask ${smaskId} 0 R`:""} /Length ${compressed.length} >>`,compressed);}imageResources.set(key,{name,objectId});}
    const content=pdfSurface(surface,project,imageResources);const contentId=builder.addStream(`<< /Length ${Buffer.byteLength(content,"binary")} >>`,Buffer.from(content,"binary"));const xobjects=[...imageResources.values()].map(item=>`/${item.name} ${item.objectId} 0 R`).join(" ");const resources=`<< /Font << /F1 ${fontId} 0 R >>${xobjects?` /XObject << ${xobjects} >>`:""} >>`;const pageId=builder.reserve();pageIds.push(pageId);builder.setText(pageId,`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${(surface.widthInches*72).toFixed(2)} ${(surface.heightInches*72).toFixed(2)}] /Resources ${resources} /Contents ${contentId} 0 R >>`);}
  builder.setText(1,"<< /Type /Catalog /Pages 2 0 R >>");builder.setText(2,`<< /Type /Pages /Count ${pageIds.length} /Kids [${pageIds.map(id=>`${id} 0 R`).join(" ")}] >>`);
  const bytes=builder.build(1);return artifact("pdf",`${safeName(project.title)}.pdf`,"application/pdf",bytes,project.documents.map(d=>d.id),surfaces.length);
}

export function embeddedAssetIssues(project:SpecializedOfficeProject):{code:string;message:string;documentId:string;surfaceId:string;elementId:string}[]{const issues=[];for(const document of project.documents)for(const surface of document.surfaces)for(const element of surface.elements){if(element.kind!=="image"||!element.assetId||element.metadata.hidden===true)continue;const asset=project.assets.find(a=>a.id===element.assetId);if(!asset){issues.push({code:"MISSING_ASSET",message:`Image element ${element.id} references missing asset ${element.assetId}.`,documentId:document.id,surfaceId:surface.id,elementId:element.id});continue;}if(!/^data:image\/(?:png|jpeg|jpg);base64,/i.test(asset.uri))issues.push({code:"IMAGE_NOT_EMBEDDED",message:`Asset ${asset.name} must be embedded as a PNG/JPEG data URI before portable production output.`,documentId:document.id,surfaceId:surface.id,elementId:element.id});}return issues;}

function svgElement(element:SpecializedElement,project:SpecializedOfficeProject,scale:number):string {const {x,y,width,height}=element.box,tx=x*scale,ty=y*scale,w=width*scale,h=height*scale,fill=element.style.fill??(element.kind==="shape"?"#dddddd":"#111111");if(element.kind==="text")return `<text x="${tx}" y="${ty+(element.style.fontSizePt??12)*1.3}" font-family="${xml(element.style.fontFamily??"sans-serif")}" font-size="${(element.style.fontSizePt??12)*96/72}" font-weight="${element.style.fontWeight??"normal"}" fill="${xml(fill)}">${xml(element.text??"")}</text>`;if(element.kind==="image"){const asset=project.assets.find(a=>a.id===element.assetId);if(!asset)throw new Error(`Missing image asset ${element.assetId}.`);return `<image x="${tx}" y="${ty}" width="${w}" height="${h}" preserveAspectRatio="xMidYMid meet" href="${xml(asset.uri)}"/>`;}return `<rect x="${tx}" y="${ty}" width="${w}" height="${h}" fill="${xml(fill)}" stroke="${xml(element.style.stroke??"none")}" opacity="${element.style.opacity??1}"/>`;}
function pdfSurface(surface:SpecializedSurface,project:SpecializedOfficeProject,images:Map<string,{name:string;objectId:number}>):string {const H=surface.heightInches*72,commands=["q","1 1 1 rg",`0 0 ${(surface.widthInches*72).toFixed(2)} ${H.toFixed(2)} re f`];for(const e of [...surface.elements].sort((a,b)=>a.zIndex-b.zIndex).filter(e=>e.metadata.hidden!==true)){const x=e.box.x*72,y=H-(e.box.y+e.box.height)*72,w=e.box.width*72,h=e.box.height*72;if(e.kind==="text"){const size=e.style.fontSizePt??12;commands.push("0 0 0 rg","BT",`/F1 ${size} Tf`,`${x.toFixed(2)} ${(y+h-size*1.2).toFixed(2)} Td`,`(${pdfText(e.text??"")}) Tj`,`ET`);}else if(e.kind==="image"&&e.assetId){const image=images.get(e.assetId);if(!image)throw new Error(`Image resource ${e.assetId} unavailable.`);commands.push("q",`${w.toFixed(2)} 0 0 ${h.toFixed(2)} ${x.toFixed(2)} ${y.toFixed(2)} cm`,`/${image.name} Do`,`Q`);}else{commands.push("0.92 0.92 0.92 rg",`${x.toFixed(2)} ${y.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re f`,`0 0 0 RG`,`${x.toFixed(2)} ${y.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re S`);}}commands.push("Q");return commands.join("\n");}

type DecodedImage={kind:"jpeg";width:number;height:number;data:Buffer}|{kind:"png";width:number;height:number;rgb:Buffer;alpha?:Buffer};
function decodeImageDataUri(uri:string):DecodedImage {const match=uri.match(/^data:image\/(png|jpeg|jpg);base64,(.+)$/is);if(!match)throw new Error("Production image must be an embedded PNG/JPEG data URI.");const data=Buffer.from(match[2],"base64");return match[1].toLowerCase()==="png"?decodePng(data):decodeJpeg(data);}
function decodeJpeg(data:Buffer):DecodedImage {if(data[0]!==0xff||data[1]!==0xd8)throw new Error("Invalid JPEG asset.");let offset=2;while(offset+4<data.length){if(data[offset]!==0xff){offset++;continue;}const marker=data[offset+1];offset+=2;if(marker===0xd9||marker===0xda)break;const length=data.readUInt16BE(offset);if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker)){const height=data.readUInt16BE(offset+3),width=data.readUInt16BE(offset+5),components=data[offset+7];if(components!==3)throw new Error("Only RGB JPEG assets are supported for PDF embedding.");return{kind:"jpeg",width,height,data};}offset+=length;}throw new Error("JPEG dimensions could not be read.");}
function decodePng(data:Buffer):DecodedImage {const sig=Buffer.from([137,80,78,71,13,10,26,10]);if(!data.subarray(0,8).equals(sig))throw new Error("Invalid PNG asset.");let offset=8,width=0,height=0,bitDepth=0,colorType=0,interlace=0;const idat=[];while(offset+12<=data.length){const len=data.readUInt32BE(offset),type=data.subarray(offset+4,offset+8).toString("ascii"),chunk=data.subarray(offset+8,offset+8+len);offset+=12+len;if(type==="IHDR"){width=chunk.readUInt32BE(0);height=chunk.readUInt32BE(4);bitDepth=chunk[8];colorType=chunk[9];interlace=chunk[12];}else if(type==="IDAT")idat.push(chunk);else if(type==="IEND")break;}if(!width||!height||bitDepth!==8||![2,6].includes(colorType)||interlace!==0)throw new Error("PNG PDF embedding supports non-interlaced 8-bit RGB/RGBA images.");const channels=colorType===6?4:3,rowBytes=width*channels,raw=inflateSync(Buffer.concat(idat)),decoded=Buffer.alloc(rowBytes*height);let src=0;for(let y=0;y<height;y++){const filter=raw[src++],row=decoded.subarray(y*rowBytes,(y+1)*rowBytes),prev=y?decoded.subarray((y-1)*rowBytes,y*rowBytes):undefined;for(let x=0;x<rowBytes;x++){const val=raw[src++],a=x>=channels?row[x-channels]:0,b=prev?prev[x]:0,c=prev&&x>=channels?prev[x-channels]:0;row[x]=(val+pngFilter(filter,a,b,c))&255;}}const rgb=Buffer.alloc(width*height*3),alpha=colorType===6?Buffer.alloc(width*height):undefined;for(let i=0,p=0;i<width*height;i++){rgb[i*3]=decoded[p++];rgb[i*3+1]=decoded[p++];rgb[i*3+2]=decoded[p++];if(alpha)alpha[i]=decoded[p++];}return{kind:"png",width,height,rgb,...(alpha?{alpha}: {})};}
function pngFilter(filter:number,a:number,b:number,c:number):number {if(filter===0)return 0;if(filter===1)return a;if(filter===2)return b;if(filter===3)return Math.floor((a+b)/2);if(filter===4){const p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);return pa<=pb&&pa<=pc?a:pb<=pc?b:c;}throw new Error(`Unsupported PNG filter ${filter}.`);}

class PdfBuilder {private objects:(Buffer|undefined)[]=[undefined,undefined];reserve():number{this.objects.push(undefined);return this.objects.length;}addText(value:string):number{this.objects.push(Buffer.from(value,"binary"));return this.objects.length;}addStream(dict:string,data:Buffer):number{this.objects.push(Buffer.concat([Buffer.from(`${dict}\nstream\n`,"binary"),data,Buffer.from("\nendstream","binary")]));return this.objects.length;}setText(id:number,value:string):void{this.objects[id-1]=Buffer.from(value,"binary");}build(rootId:number):Buffer{const chunks=[Buffer.from("%PDF-1.4\n%\xE2\xE3\xCF\xD3\n","binary")],offsets=[0];let length=chunks[0].length;for(let i=0;i<this.objects.length;i++){const obj=this.objects[i]??Buffer.from("<<>>","binary"),prefix=Buffer.from(`${i+1} 0 obj\n`,`binary`),suffix=Buffer.from("\nendobj\n","binary");offsets[i+1]=length;chunks.push(prefix,obj,suffix);length+=prefix.length+obj.length+suffix.length;}const xrefOffset=length;let xref=`xref\n0 ${this.objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=this.objects.length;i++)xref+=`${String(offsets[i]).padStart(10,"0")} 00000 n \n`;xref+=`trailer\n<< /Size ${this.objects.length+1} /Root ${rootId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;chunks.push(Buffer.from(xref,"binary"));return Buffer.concat(chunks);}}
function artifact(kind:"svg"|"pdf",fileName:string,mimeType:string,bytes:Buffer,sourceDocumentIds:readonly string[],pageCount?:number):SpecializedRenderedArtifact{return Object.freeze({kind,fileName,mimeType,bytesBase64:bytes.toString("base64"),byteLength:bytes.length,sha256:createHash("sha256").update(bytes).digest("hex"),...(pageCount?{pageCount}:{}),sourceDocumentIds:Object.freeze([...sourceDocumentIds])});}
function xml(value:string):string{return value.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]!));}function pdfText(value:string):string{return value.replace(/([\\()])/g,"\\$1");}function safeName(value:string):string{return value.trim().replace(/[^A-Za-z0-9._-]+/g,"-").replace(/^-+|-+$/g,"")||"specialized-creation";}
