import { randomUUID } from "node:crypto";
import type { FileSpecializedCreationStore } from "../infrastructure/file-specialized-creation-store";
import { generateProjectText,type AiGenerationResult,type ProjectAiGenerationRequest } from "../infrastructure/ai-provider";
import type { ProjectMemoryStore } from "./project-memory-store";
import type { SpecializedOfficeProject,SpecializedProposal,TcgData } from "../domain/specialized-creation-office";
import { validateTcgGameFramework,withTcgCharacterLine,withTcgWorldMap,type TcgCharacterEvolutionLine,type TcgGameFramework,type TcgWorldMap } from "../domain/specialized-creation-tcg-world";
import { setTcgGameFramework,tcgGameFramework,upsertTcgCharacterEvolutionLine,upsertTcgWorldMap } from "./specialized-creation-tcg-design";

export type TcgAiProposalScope="game-framework"|"character-line"|"world-map"|"balance-review";
export type TcgAiTextGenerator=(request:ProjectAiGenerationRequest)=>Promise<AiGenerationResult>;
export interface TcgAiProposalResult {readonly proposal:SpecializedProposal;readonly ai:Pick<AiGenerationResult,"provider"|"model"|"requestId"|"attempts"|"optimization">;}

export class SpecializedCreationTcgAiService {
  constructor(private readonly store:FileSpecializedCreationStore,private readonly memory:ProjectMemoryStore,private readonly ai:TcgAiTextGenerator=generateProjectText){}

  async propose(input:{forgeProjectId:string;specializedProjectId:string;scope:TcgAiProposalScope;instruction:string;focusId?:string;now?:string}):Promise<TcgAiProposalResult>{
    const project=await this.requireTcg(input.forgeProjectId,input.specializedProjectId),data=project.modeData as TcgData,framework=tcgGameFramework(data),now=input.now??new Date().toISOString(),system=systemPrompt(input.scope),user=proposalPrompt(input.scope,project,data,framework,input.instruction,input.focusId);
    const result=await this.ai({memory:this.memory,context:{projectId:input.forgeProjectId,taskMemoryClasses:["author-memory","project-memory","style-memory","character-memory","research-memory","decision-memory","production-memory"],relevanceTags:["specialized-creation","trading-card-game","tcg-game-design",input.scope],queryTerms:[project.title,project.brief,input.focusId??input.scope],includeWorkingState:true,limit:60},system,user,temperature:input.scope==="balance-review"?0.35:0.65,maxOutputTokens:8000});
    const parsed=parseObject(result.text),summary=required(parsed.summary,"TCG AI proposal summary"),payload=validatePayload(input.scope,parsed.payload,framework,input.focusId),proposal:SpecializedProposal=Object.freeze({id:`proposal-${randomUUID()}`,projectId:project.id,kind:"revision",status:"proposed",summary,payload:Object.freeze({tcgScope:input.scope,value:clone(payload)}),provider:result.provider,model:result.model,...(result.requestId?{requestId:result.requestId}:{}),createdAt:now});
    await this.store.save({...project,proposals:[...project.proposals,proposal],updatedAt:now});return{proposal,ai:evidence(result)};
  }

  async approveAndApply(input:{forgeProjectId:string;specializedProjectId:string;proposalId:string;now?:string}):Promise<SpecializedOfficeProject>{
    const project=await this.requireTcg(input.forgeProjectId,input.specializedProjectId),proposal=project.proposals.find(item=>item.id===input.proposalId);if(!proposal)throw new Error(`TCG AI proposal "${input.proposalId}" not found.`);if(proposal.status!=="proposed")throw new Error("Only proposed TCG AI work can be approved.");const envelope=proposal.payload as Record<string,unknown>,scope=envelope.tcgScope as TcgAiProposalScope,value=envelope.value,data=project.modeData as TcgData;let modeData:TcgData=data;
    if(scope==="game-framework"){validateTcgGameFramework(value as TcgGameFramework,false);modeData=setTcgGameFramework(data,value as TcgGameFramework);}
    else if(scope==="character-line")modeData=upsertTcgCharacterEvolutionLine(data,value as TcgCharacterEvolutionLine);
    else if(scope==="world-map")modeData=upsertTcgWorldMap(data,value as TcgWorldMap);
    else if(scope!=="balance-review")throw new Error("Unsupported TCG AI proposal scope.");
    const now=input.now??new Date().toISOString(),proposals=project.proposals.map(item=>item.id===proposal.id?{...item,status:"approved" as const,reviewedAt:now}:item);return this.store.save({...project,modeData,proposals,stage:project.stage==="brief"?"plan":project.stage,updatedAt:now});
  }

  async reject(input:{forgeProjectId:string;specializedProjectId:string;proposalId:string;now?:string}):Promise<SpecializedOfficeProject>{const project=await this.requireTcg(input.forgeProjectId,input.specializedProjectId);if(!project.proposals.some(item=>item.id===input.proposalId))throw new Error(`TCG AI proposal "${input.proposalId}" not found.`);const now=input.now??new Date().toISOString();return this.store.save({...project,proposals:project.proposals.map(item=>item.id===input.proposalId?{...item,status:"rejected" as const,reviewedAt:now}:item),updatedAt:now});}
  private async requireTcg(forgeProjectId:string,id:string):Promise<SpecializedOfficeProject>{const project=await this.store.get(forgeProjectId,id);if(!project)throw new Error(`Specialized project "${id}" not found.`);if(project.mode!=="trading-card-game")throw new Error("TCG AI design requires trading-card-game mode.");return project;}
}

function systemPrompt(scope:TcgAiProposalScope):string{return ["You are the governed TCG design assistant inside Author's Forge.","Use Project Brain canon and the author's original intellectual property. Do not imitate or reproduce protected commercial card frames, logos, named proprietary characters, or copyrighted art.","Never claim mathematical game balance. For balance work, identify risks, hypotheses, counters and playtest experiments.","Return JSON only, exactly shaped as {\"summary\":\"...\",\"payload\":...}.",scope==="game-framework"?"payload must be a complete TcgGameFramework object with premise, playerGoal, victoryConditions, turnStructure, zones, resources, cardTypes, keywords, factions, characterLines, worldMaps, designNotes.":scope==="character-line"?"payload must be one complete TcgCharacterEvolutionLine with stable ids, ordered stages, strengths, weaknesses, magicalPowers, physicalPowers, territoryIds and artworkAssetIds. Do not invent an artwork asset id.":scope==="world-map"?"payload must be one complete TcgWorldMap with stable territories, normalized center coordinates from 0 to 1, adjacency, resources, hazards and characterStageRefs. Do not invent an artwork asset id.":"payload must be an object containing findings, risks, counterplayQuestions, outliers and playtestExperiments. Do not mutate canon."].join("\n");}
function proposalPrompt(scope:TcgAiProposalScope,project:SpecializedOfficeProject,data:TcgData,framework:TcgGameFramework,instruction:string,focusId?:string):string{return [`Project: ${project.title}`,`Brief: ${project.brief}`,project.audience?`Audience: ${project.audience}`:"",`Game: ${data.gameTitle} / set ${data.setId} ${data.setName}`,`Scope: ${scope}`,focusId?`Focused id: ${focusId}`:"",`Author instruction: ${required(instruction,"TCG AI instruction")}`,`Current game framework: ${JSON.stringify(framework)}`,`Current card schema: ${JSON.stringify(data.fields)}`,`Current cards: ${JSON.stringify(data.cards)}`].filter(Boolean).join("\n");}
function validatePayload(scope:TcgAiProposalScope,value:unknown,framework:TcgGameFramework,focusId?:string):unknown {if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("TCG AI proposal payload must be an object.");if(scope==="game-framework"){validateTcgGameFramework(value as TcgGameFramework,false);return value;}if(scope==="character-line"){const line=value as TcgCharacterEvolutionLine;if(focusId&&line.id!==focusId)throw new Error("TCG AI character proposal changed the focused character-line id.");withTcgCharacterLine(framework,line);return line;}if(scope==="world-map"){const map=value as TcgWorldMap;if(focusId&&map.id!==focusId)throw new Error("TCG AI map proposal changed the focused world-map id.");withTcgWorldMap(framework,map);return map;}const review=value as Record<string,unknown>;for(const key of ["findings","risks","counterplayQuestions","outliers","playtestExperiments"])if(!Array.isArray(review[key]))throw new Error(`TCG balance review requires ${key} array.`);return review;}
function parseObject(text:string):Record<string,unknown>{try{const value=JSON.parse(text.trim());if(!value||typeof value!=="object"||Array.isArray(value))throw new Error();return value as Record<string,unknown>;}catch{throw new Error("AI TCG design response was not valid JSON.");}}
function required(value:unknown,label:string):string{if(typeof value!=="string"||!value.trim())throw new Error(`${label} is required.`);return value.trim();}
function clone<T>(value:T):T{return JSON.parse(JSON.stringify(value)) as T;}
function evidence(result:AiGenerationResult):Pick<AiGenerationResult,"provider"|"model"|"requestId"|"attempts"|"optimization">{return{provider:result.provider,model:result.model,...(result.requestId?{requestId:result.requestId}:{}),...(result.attempts?{attempts:result.attempts}:{}),...(result.optimization?{optimization:result.optimization}:{})};}
