export type { MemoryClass, MemoryAuthority, MemoryProvenance, MemoryRecord, MemoryQuery } from "./domain/memory";
export { createMemoryRecord, MEMORY_FORMAT_VERSION } from "./domain/memory";
export { ProjectMemoryStore } from "./application/project-memory-store";
export type { MemoryPromotionDecision, ProjectMemorySnapshot } from "./application/project-memory-store";
export { assembleProjectBrainContext } from "./application/project-brain";
export type { ProjectBrainQuery, ProjectBrainContext } from "./application/project-brain";
export { createProject, touchProject, withProjectMemories, withProjectCharacters, withProjectVisualIdentities, PROJECT_FORMAT_VERSION } from "./domain/project";
export type { ProjectMetadata, ProjectState, ProjectStatus } from "./domain/project";
export { FileProjectStore } from "./infrastructure/file-project-store";
export { MANUSCRIPT_FORMAT_VERSION, createManuscriptState, createBook, createChapter, createScene, addBook, addChapter, addScene, insertChapter, insertScene, validateManuscriptState } from "./domain/manuscript";
export type { BookLifecycle, ChapterLifecycle, SceneLifecycle, BookRecord, ChapterRecord, SceneRecord, ManuscriptState } from "./domain/manuscript";
export { MANUSCRIPT_PLAN_FORMAT_VERSION, createManuscriptPlanningState, createManuscriptPlan, addManuscriptPlan, replaceManuscriptPlan, getCurrentManuscriptPlan, validateManuscriptPlanningState } from "./domain/manuscript-planning";
export type { ManuscriptPlan, ManuscriptPlanningState, PlanLifecycle, PlanTargetType } from "./domain/manuscript-planning";
export { ManuscriptPlanningService } from "./application/manuscript-planning";
export { EDITING_FORMAT_VERSION, EDITOR_ROLES, FINDING_KINDS, createEditingDocument, createEditorialFinding, createEditorialReport, validateEditorialReport } from "./domain/intelligent-editing";
export type { EditorRole, FindingSeverity, FindingKind, EditingTarget, EditingDocument, EditorialFinding, EditorialReport } from "./domain/intelligent-editing";
export { IntelligentEditingService } from "./application/intelligent-editing";
export type { EditingRequest } from "./application/intelligent-editing";
export { RESEARCH_FORMAT_VERSION, RESEARCH_DOMAINS, createResearchClaim, createResearchRecord } from "./domain/research";
export type { ResearchDomain, ResearchConfidence, ResearchRelevance, ResearchSource, ResearchClaim, ResearchRecord } from "./domain/research";
export { ResearchEngine, StaticResearchProvider } from "./application/research-engine";
export type { ResearchRequest, ResearchProvider, ResearchProviderRequest, ResearchProviderResult, ResearchSearchResult } from "./application/research-engine";
export { RESEARCH_HONESTY_FORMAT_VERSION, RESEARCH_HONESTY_CLASSES, createResearchHonestyRecord, isResearchHonest, assertResearchHonest } from "./domain/research-honesty";
export type { ResearchHonestyClass, EvidenceStrength, ResearchHonestyAssessment, ResearchHonestyRecord, ResearchHonestyInput } from "./domain/research-honesty";
export { ResearchHonestyService } from "./application/research-honesty";
export type { ResearchHonestyQuery, ResearchHonestySummary } from "./application/research-honesty";
export { CHARACTER_BIBLE_FORMAT_VERSION, CHARACTER_FIELDS, createCharacter, updateCharacter, getCharacterAt, getCharacterFieldHistory, getCharacterChanges, validateCharacterRecord } from "./domain/character-bible";
export type { CharacterField, CharacterRelationship, CharacterProfile, CharacterFieldValue, CharacterFieldVersion, CharacterChange, CharacterRecord, CharacterProfileUpdate, CharacterUpdateInput } from "./domain/character-bible";
export { CharacterBibleService } from "./application/character-bible";
export type { CharacterQuery, CharacterHistoryQuery } from "./application/character-bible";
export { VISUAL_IDENTITY_FORMAT_VERSION, VISUAL_REFERENCE_KINDS, createVisualCharacterIdentity, updateVisualCharacterIdentity, resolveVisualCharacterIdentity, generateVisualCharacterIdentityPackage, validateVisualCharacterIdentity } from "./domain/character-visual-continuity";
export type { VisualReferenceKind, VisualReference, VisualIdentityState, VisualIdentitySnapshot, VisualCharacterIdentity, VisualIdentityUpdateInput, VisualIdentityPackage } from "./domain/character-visual-continuity";
export { CharacterVisualContinuityService } from "./application/character-visual-continuity";
export type { VisualIdentityQuery } from "./application/character-visual-continuity";
