export type { MemoryClass, MemoryAuthority, MemoryProvenance, MemoryRecord, MemoryQuery } from "./domain/memory";
export { createMemoryRecord, MEMORY_FORMAT_VERSION } from "./domain/memory";
export { ProjectMemoryStore } from "./application/project-memory-store";
export type { MemoryPromotionDecision, ProjectMemorySnapshot } from "./application/project-memory-store";
export { assembleProjectBrainContext } from "./application/project-brain";
export type { ProjectBrainQuery, ProjectBrainContext } from "./application/project-brain";
export { assembleWritingContext, CONTEXT_ASSEMBLY_FORMAT_VERSION, CONTEXT_INCLUSION_MODES } from "./domain/context-assembly";
export type { ContextInclusionMode, ContextSectionPolicy, ContextAssemblyRequest, ContextSection, AssembledWritingContext } from "./domain/context-assembly";
export { createProductionContextEngineRegistry, CONTEXT_ENGINE_CAPABILITIES } from "./application/context-engine-stack";
export type { ContextEngineCapability } from "./application/context-engine-stack";
export { compressToolResult } from "./application/tool-result-compressor";
export type { ToolResultCompressionInput, ToolResultCompressionResult } from "./application/tool-result-compressor";
export { InMemoryContextOptimizationLedger } from "./application/context-optimization-ledger";
export type { ContextOptimizationLedger, ContextOptimizationLedgerEntry, ContextOptimizationLedgerSummary } from "./application/context-optimization-ledger";
export { createCostGuardedAiGateway, estimateAiRequestCost, AiCostGuardError } from "./application/ai-cost-guard";
export type { AiCostPolicy, AiCostEstimate } from "./application/ai-cost-guard";
export { AiProposalStore } from "./application/ai-proposal-store";
export type { AiProposal, AiProposalKind, AiProposalStatus, ProposalReviewDecision } from "./application/ai-proposal-store";
export { createMarketingCampaign, approveMarketingAsset, scheduleMarketingAsset, MARKETING_CHANNELS } from "./domain/marketing-campaign";
export type { MarketingCampaign, MarketingAsset, MarketingEvidence, MarketingChannel, MarketingAssetStatus } from "./domain/marketing-campaign";
export { createReleaseGateReport, validateReleaseGateReport, RELEASE_GATE_FORMAT_VERSION } from "./domain/release-gate";
export type { ReleaseGateReport, ReleaseGateInput, ReleaseGateBlocker, ReleaseGateStatus, ReleaseBlockerKind } from "./domain/release-gate";
export { createWorkflowGateReport, canAdvanceWorkflow, validateWorkflowGateReport, FORGE_WORKFLOW_STAGES, WORKFLOW_GATE_FORMAT_VERSION } from "./domain/workflow-gate";
export type { WorkflowGateReport, WorkflowGateInput, WorkflowGateCheck, WorkflowStageGate, WorkflowGateStatus, ForgeWorkflowStage } from "./domain/workflow-gate";