export type { MemoryClass, MemoryAuthority, MemoryProvenance, MemoryRecord, MemoryQuery } from "./domain/memory";
export { createMemoryRecord, MEMORY_FORMAT_VERSION } from "./domain/memory";
export { ProjectMemoryStore } from "./application/project-memory-store";
export type { MemoryPromotionDecision, ProjectMemorySnapshot } from "./application/project-memory-store";
export { assembleProjectBrainContext } from "./application/project-brain";
export type { ProjectBrainQuery, ProjectBrainContext } from "./application/project-brain";
export { assembleWritingContext, CONTEXT_ASSEMBLY_FORMAT_VERSION, CONTEXT_INCLUSION_MODES } from "./domain/context-assembly";
export type { ContextInclusionMode, ContextSectionPolicy, ContextAssemblyRequest, ContextSection, AssembledWritingContext } from "./domain/context-assembly";
export { createProductionContextEngineRegistry, CONTEXT_ENGINE_CAPABILITIES } from "./application/context-engine-stack";
export type { ContextEngineCapability } from "./application/context-engine-stack";
export { compressToolResult } from "./application/tool-result-compressor";
export type { ToolResultCompressionInput, ToolResultCompressionResult } from "./application/tool-result-compressor";
export { InMemoryContextOptimizationLedger } from "./application/context-optimization-ledger";
export type { ContextOptimizationLedger, ContextOptimizationLedgerEntry, ContextOptimizationLedgerSummary } from "./application/context-optimization-ledger";
export { createCostGuardedAiGateway, estimateAiRequestCost, AiCostGuardError } from "./application/ai-cost-guard";
export type { AiCostPolicy, AiCostEstimate } from "./application/ai-cost-guard";
export { AiProposalStore } from "./application/ai-proposal-store";
export type { AiProposal, AiProposalKind, AiProposalStatus, ProposalReviewDecision } from "./application/ai-proposal-store";
export { FileAiProposalStore, AI_PROPOSAL_STORE_FORMAT_VERSION } from "./infrastructure/file-ai-proposal-store";
export { AiModelBroker } from "./application/ai-model-broker";
export type { AiTask, AiModelCapabilities, AiModelResource, AiModelSelectionRequest, AiModelSelection } from "./application/ai-model-broker";
export { AiWritingService, AI_WRITING_FORMAT_VERSION } from "./application/ai-writing";
export type { AiWritingTask, AiWritingRequest, AiWritingProviderRequest, AiWritingProvider, AiWritingResult } from "./application/ai-writing";
export { AiWritingCoordinator } from "./application/ai-writing-coordinator";
export type { AiWritingGenerator } from "./application/ai-writing-coordinator";
export { AiWritingStudioService, sha256 as sha256AiWritingContent } from "./application/ai-writing-studio";
export type { StudioAiProjectState } from "./application/ai-writing-studio";
export { AiEditingProposalService, sha256EditingContent } from "./application/ai-editing-proposals";
export type { AiEditingProposalRequest } from "./application/ai-editing-proposals";
export { createAiProposalDiff, AI_PROPOSAL_DIFF_FORMAT_VERSION } from "./application/ai-proposal-diff";
export type { AiProposalDiff, AiProposalDiffLine, AiProposalDiffLineKind } from "./application/ai-proposal-diff";
export { createMarketingCampaign, approveMarketingAsset, scheduleMarketingAsset, MARKETING_CHANNELS } from "./domain/marketing-campaign";
export type { MarketingCampaign, MarketingAsset, MarketingEvidence, MarketingChannel, MarketingAssetStatus } from "./domain/marketing-campaign";
export { createReleaseGateReport, validateReleaseGateReport, RELEASE_GATE_FORMAT_VERSION } from "./domain/release-gate";
export type { ReleaseGateReport, ReleaseGateInput, ReleaseGateBlocker, ReleaseGateStatus, ReleaseBlockerKind } from "./domain/release-gate";
export { createWorkflowGateReport, canAdvanceWorkflow, validateWorkflowGateReport, FORGE_WORKFLOW_STAGES, WORKFLOW_GATE_FORMAT_VERSION } from "./domain/workflow-gate";
export type { WorkflowGateReport, WorkflowGateInput, WorkflowGateCheck, WorkflowStageGate, WorkflowGateStatus, ForgeWorkflowStage } from "./domain/workflow-gate";
export { advanceWorkflow, WORKFLOW_ADVANCE_FORMAT_VERSION } from "./application/workflow-advance";
export type { WorkflowAdvanceRequest, WorkflowAdvanceResult, WorkflowAdvanceDecision } from "./application/workflow-advance";
export { advanceProjectWorkflow } from "./application/project-workflow";
export type { ProjectWorkflowAdvanceRequest, ProjectWorkflowAdvanceResult } from "./application/project-workflow";
export { createProject, touchProject, withProjectMemories, withProjectCharacters, withProjectVisualIdentities, withProjectIllustrationAssetLibrary, withProjectBookCoverPlans, withProjectPublishingReadinessReports, withProjectKdpMarketIntelligenceReports, withProjectBookPositioningReports, withProjectBookVersionHistories, withProjectAuthorDecisions, withProjectSeries, withProjectVoiceProfiles, withProjectAiCollaborationPolicy, withProjectHealthReports, withProjectMemoryRelationships, withProjectDeliveryAudits, withProjectBookGenome, PROJECT_FORMAT_VERSION } from "./domain/project";
export type { ProjectMetadata, ProjectState, ProjectStatus } from "./domain/project";
export { FileProjectStore } from "./infrastructure/file-project-store";
export { FileVisualIdentityStore } from "./infrastructure/file-visual-identity-store";
export { LocalFileStorageProvider } from "./infrastructure/local-storage-provider";
export { MANUSCRIPT_FORMAT_VERSION, createManuscriptState, createBook, createChapter, createScene, addBook, addChapter, addScene, insertChapter, insertScene, validateManuscriptState } from "./domain/manuscript";
export type { BookLifecycle, ChapterLifecycle, SceneLifecycle, ManuscriptState } from "./domain/manuscript";
export { MANUSCRIPT_PLAN_FORMAT_VERSION, createManuscriptPlanningState, createManuscriptPlan, addManuscriptPlan, replaceManuscriptPlan, getCurrentManuscriptPlan, validateManuscriptPlanningState } from "./domain/manuscript-planning";
export type { ManuscriptPlan, ManuscriptPlanningState, PlanLifecycle, PlanTargetType } from "./domain/manuscript-planning";
export { ManuscriptPlanningService } from "./application/manuscript-planning";
export { EDITING_FORMAT_VERSION, EDITOR_ROLES, FINDING_KINDS, createEditingDocument, createEditorialFinding, createEditorialReport, validateEditorialReport } from "./domain/intelligent-editing";
export type { EditorRole, FindingSeverity, FindingKind, EditingTarget, EditingDocument, EditorialFinding, EditorialReport } from "./domain/intelligent-editing";
export { IntelligentEditingService } from "./application/intelligent-editing";
export type { EditingRequest } from "./application/intelligent-editing";
export { RESEARCH_FORMAT_VERSION, RESEARCH_DOMAINS, createResearchClaim, createResearchRecord } from "./domain/research";
export type { ResearchDomain, ResearchConfidence, ResearchRelevance, ResearchSource, ResearchClaim, ResearchRecord } from "./domain/research";
export { ResearchEngine, StaticResearchProvider } from "./application/research-engine";
export type { ResearchRequest, ResearchProvider, ResearchProviderRequest, ResearchProviderResult, ResearchSearchResult } from "./application/research-engine";
export { RESEARCH_HONESTY_FORMAT_VERSION, RESEARCH_HONESTY_CLASSES, createResearchHonestyRecord, isResearchHonest, assertResearchHonest } from "./domain/research-honesty";
export type { ResearchHonestyClass, EvidenceStrength, ResearchHonestyAssessment, ResearchHonestyRecord, ResearchHonestyInput } from "./domain/research-honesty";
export { ResearchHonestyService } from "./application/research-honesty";
export type { ResearchHonestyQuery, ResearchHonestySummary } from "./application/research-honesty";
export { CHARACTER_BIBLE_FORMAT_VERSION, CHARACTER_FIELDS, createCharacter, updateCharacter, getCharacterAt, getCharacterFieldHistory, getCharacterChanges, validateCharacterRecord } from "./domain/character-bible";
export type { CharacterField, CharacterRelationship, CharacterProfile, CharacterFieldValue, CharacterFieldVersion, CharacterChange, CharacterRecord, CharacterProfileUpdate, CharacterUpdateInput } from "./domain/character-bible";
export { CharacterBibleService } from "./application/character-bible";
export type { CharacterQuery, CharacterHistoryQuery } from "./application/character-bible";
export { VISUAL_IDENTITY_FORMAT_VERSION, VISUAL_REFERENCE_KINDS, createVisualCharacterIdentity, updateVisualCharacterIdentity, resolveVisualCharacterIdentity, generateVisualCharacterIdentityPackage, validateVisualCharacterIdentity } from "./domain/character-visual-continuity";
export type { VisualReferenceKind, VisualReference, VisualIdentityState, VisualIdentitySnapshot, VisualCharacterIdentity, VisualIdentityUpdateInput, VisualIdentityPackage } from "./domain/character-visual-continuity";
export { CharacterVisualContinuityService } from "./application/character-visual-continuity";
export type { VisualIdentityQuery } from "./application/character-visual-continuity";
export { ILLUSTRATION_ASSET_LIBRARY_FORMAT_VERSION, ILLUSTRATION_APPROVAL_STATUSES, createIllustrationAsset, updateIllustrationAsset, createCharacterDesignLock, resolveCharacterDesignLock, reuseIllustrationAsset, validateIllustrationAssetLibraryState } from "./domain/illustration-asset-library";
export type { IllustrationApprovalStatus, IllustrationAssetReference, IllustrationGenerationSettingValue, IllustrationAsset, CharacterDesignLock, IllustrationAssetLibraryState, CreateIllustrationAssetInput, UpdateIllustrationAssetInput, CreateCharacterDesignLockInput } from "./domain/illustration-asset-library";
export { IllustrationAssetLibraryService } from "./application/illustration-asset-library";
export type { IllustrationAssetQuery } from "./application/illustration-asset-library";
export { FileIllustrationAssetLibraryStore } from "./infrastructure/file-illustration-asset-library-store";
export { BOOK_COVER_STUDIO_FORMAT_VERSION, COVER_FORMATS, BINDINGS, INTERIOR_TYPES, PAPER_TYPES, COVER_APPROVAL_STATUSES, calculateKdpCoverLayout, validatePublishingConfiguration, validateBookCoverFile, createBookCoverPlan } from "./domain/book-cover-studio";
export type { CoverFormat, Binding, InteriorType, PaperType, CoverApprovalStatus, PublishingConfiguration, CoverDimensions, CoverZones, CoverValidationIssue, BookCoverPlan, CreateBookCoverPlanInput } from "./domain/book-cover-studio";
export { BookCoverStudioService } from "./application/book-cover-studio";
export { MANUSCRIPT_PRODUCTION_FORMAT_VERSION, PRODUCTION_FORMATS, FRONT_MATTER_KINDS, BACK_MATTER_KINDS, validateProductionManuscript, validateProductionOptions, normalizeProductionManuscript, validateProductionArtifact, mimeFor, extensionFor, requiredFrontMatter, requiredBackMatter } from "./domain/manuscript-production";
export type { ProductionFormat, FrontMatterKind, BackMatterKind, ProductionSection, ProductionChapter, ProductionScene, ProductionManuscript, ProductionOptions, ProductionArtifact, ProductionValidationIssue } from "./domain/manuscript-production";
export { ManuscriptProductionService } from "./application/manuscript-production";
export { PUBLISHING_READINESS_FORMAT_VERSION, createPublishingReadinessReport, validatePublishingReadinessReport } from "./domain/publishing-readiness";
export type { ReadinessStatus, ReadinessSeverity, ReadinessCategory, ReadinessCheck, PublishingReadinessInput, PublishingReadinessReport } from "./domain/publishing-readiness";
export { PublishingReadinessService } from "./application/publishing-readiness";
export type { PublishingReadinessStore } from "./application/publishing-readiness";
export { KDP_MARKET_INTELLIGENCE_FORMAT_VERSION, MARKET_INTELLIGENCE_TOPICS, createKdpMarketIntelligenceReport, validateKdpMarketIntelligenceReport, summarizeMarketIntelligence } from "./domain/kdp-market-intelligence";
export type { MarketIntelligenceTopic, SignalDirection, EvidenceStrength as MarketEvidenceStrength, OpportunityLevel, MarketEvidence, MarketSignal, ComparableTitle, MarketOpportunityAssessment, KdpMarketIntelligenceReport, CreateMarketIntelligenceReportInput } from "./domain/kdp-market-intelligence";
export { BOOK_POSITIONING_FORMAT_VERSION, BOOK_POSITIONING_DISCLAIMER, createBookPositioningReport, validateBookPositioningReport } from "./domain/book-positioning";
export type { PositioningComparable, PositioningAnswer, PositioningConcepts, BookPositioningReport, CreateBookPositioningReportInput } from "./domain/book-positioning";
export { BookPositioningService, StaticBookPositioningProvider } from "./application/book-positioning";
export type { BookPositioningRequest, BookPositioningProviderRequest, BookPositioningProviderResult, BookPositioningProvider } from "./application/book-positioning";
export { CONTENT_RANDOMIZER_FORMAT_VERSION, randomizeContent, validateRandomizerResult } from "./domain/content-randomizer";
export type { RandomizerItem, RandomizerSet, RandomizerRequest, RandomizerResult } from "./domain/content-randomizer";
export { ContentRandomizerService } from "./application/content-randomizer";
export { PROJECT_PACKAGE_FORMAT_VERSION, PROJECT_PACKAGE_NAME, createProjectPackage, validateProjectPackage, serializeProjectPackage, deserializeProjectPackage } from "./domain/project-package";
export type { ProjectPackageEncoding, ProjectPackageManifest, ForgeProjectPackage, ProjectPackageFile } from "./domain/project-package";
export { ProjectPackageService } from "./application/project-package";
export { EXTERNAL_STORAGE_FORMAT_VERSION, createProjectStorageBinding, validateProjectStorageBinding, createDownloadableProjectPackageFilename, MemoryStorageProvider } from "./domain/external-storage";
export type { StorageProviderId, StoredObject, StorageProvider, ProjectStorageBinding } from "./domain/external-storage";
export { ExternalStorageService } from "./application/external-storage";
export { BOOK_VERSION_CONTROL_FORMAT_VERSION, createBookSnapshot, validateBookSnapshot, compareBookVersions, rollbackVersion, branchVersion, mergeVersions } from "./domain/book-version-control";
export type { BookVersionLabel, BookSnapshot, VersionChange, BookVersionComparison, BookVersionBranch, BookVersionHistory } from "./domain/book-version-control";
export { AUTHOR_CONTROL_FORMAT_VERSION, createAuthorDecision, validateAuthorDecision, applyAuthorOverride, lockCanon, resolveAuthorControl, isCanonLocked } from "./domain/author-control";
export type { AuthorDecisionStatus, AuthorDecision } from "./domain/author-control";
export { AuthorControlService } from "./application/author-control";
export { SERIES_FORMAT_VERSION, createSeries, validateSeriesState, addBookToSeries, addSeriesTimelineEvent } from "./domain/series";
export type { SeriesState, SeriesTimelineEvent } from "./domain/series";
export { SeriesService } from "./application/series";
export { VOICE_PRESERVATION_FORMAT_VERSION, analyzeVoice, createVoiceProfile, compareVoiceToProfile, buildVoiceRewriteBrief } from "./domain/voice-preservation";
export type { VoiceFingerprint, VoiceProfile, VoiceAnalysis, VoiceRewriteRequest } from "./domain/voice-preservation";
export { VoicePreservationService } from "./application/voice-preservation";
export { AI_COLLABORATION_FORMAT_VERSION, AI_COLLABORATION_MODES, createAiCollaborationPolicy, validateAiCollaborationPolicy } from "./domain/ai-collaboration";
export type { AiCollaborationMode, AiCollaborationPolicy } from "./domain/ai-collaboration";
export { AiCollaborationService } from "./application/ai-collaboration";
export { PROJECT_HEALTH_FORMAT_VERSION, createProjectHealthReport, validateProjectHealthReport } from "./domain/project-health";
export type { ProjectHealthMetrics, ProjectHealthReport } from "./domain/project-health";
export { ProjectHealthService } from "./application/project-health";
export { RELATIONSHIP_MEMORY_FORMAT_VERSION, createMemoryRelationship, validateMemoryRelationship } from "./domain/relationship-memory";
export type { MemoryRelationship } from "./domain/relationship-memory";
export { RelationshipMemoryService } from "./application/relationship-memory";
export { DELIVERY_AUDIT_FORMAT_VERSION, DELIVERY_AUDIT_CATEGORIES, createDeliveryAuditReport, validateDeliveryAuditReport } from "./domain/delivery-audit";
export type { DeliveryAuditCategory, DeliveryAuditSeverity, DeliveryAuditCheck, DeliveryAuditReport } from "./domain/delivery-audit";
export { FINAL_PRODUCT_FORMAT_VERSION, BOOK_GENOME_COMPONENTS, DELIVERY_AUDIT_CATEGORIES as FINAL_DELIVERY_AUDIT_CATEGORIES, createCapabilityGap, advanceCapabilityGap, defaultOwnershipPolicy, defaultAccessibilityProfile, createVoiceCommand, createCreativeProvenance, createBookGenome, identifyGenomeImpact, createFinalProductAudit } from "./domain/final-product-systems";
export type { BookGenomeComponent, CapabilityGapStatus, CapabilityGap, OwnershipPolicy, AccessibilityProfile, VoiceCommand, ProvenanceKind, CreativeProvenance, BookGenomeNode, BookGenome, GenomeImpact, FinalDeliveryAuditCategory, FinalDeliveryCheck, FinalProductAudit } from "./domain/final-product-systems";
export { CapabilityEscalationService, GovernanceService, BookGenomeService, FinalProductAuditService } from "./application/final-product-systems";
