import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { randomUUID } from "node:crypto";
import { readFile, writeFile, mkdir, readdir } from "node:fs/promises";
import { extname, join, normalize } from "node:path";
import { FileProjectStore } from "./infrastructure/file-project-store";
import { createProject, withProjectBookGenome, withProjectCharacters, withProjectAiCollaborationPolicy, withProjectBookCoverPlans } from "./domain/project";
import { createMemoryRecord, type MemoryAuthority, type MemoryClass } from "./domain/memory";
import { assembleWritingContext, CONTEXT_INCLUSION_MODES, type ContextSectionPolicy } from "./domain/context-assembly";
import { BookGenomeService, FinalProductAuditService, GovernanceService } from "./application/final-product-systems";
import { DELIVERY_AUDIT_CATEGORIES as FINAL_AUDIT_CATEGORIES, type BookGenomeNode, type FinalDeliveryCheck } from "./domain/final-product-systems";
import { createCharacter, updateCharacter, type CharacterProfile } from "./domain/character-bible";
import { createStudioWorkspace, addWorkspaceBook, addWorkspaceChapter, addWorkspaceScene, getBook, getScene, saveSceneContent, setActiveBook, validateStudioWorkspace, createWorkspaceBook, type StudioWorkspaceState } from "./domain/studio-workspace";
import { generateText } from "./infrastructure/ai-provider";
import { ManuscriptProductionService } from "./application/manuscript-production";
import type { ProductionFormat } from "./domain/manuscript-production";
import { IntelligentEditingService } from "./application/intelligent-editing";
import { EDITOR_ROLES, type EditorRole } from "./domain/intelligent-editing";
import { createAiCollaborationPolicy, AI_COLLABORATION_MODES, type AiCollaborationMode } from "./domain/ai-collaboration";
import { BookCoverStudioService } from "./application/book-cover-studio";
import { BINDINGS, INTERIOR_TYPES, PAPER_TYPES, type Binding, type InteriorType, type PaperType } from "./domain/book-cover-studio";
import { IllustrationReferencePipeline } from "./application/illustration-reference-pipeline";
import { createIllustrationReferenceImage } from "./domain/illustration-reference-image";

const port = Number(process.env.PORT ?? 4173);
const host = process.env.HOST ?? "127.0.0.1";
const dataRoot = process.env.FORGE_DATA_DIR ?? join(process.cwd(), ".forge-data");
const publicRoot = join(process.cwd(), "public");
const store = new FileProjectStore(dataRoot);
const genome = new BookGenomeService();
const audit = new FinalProductAuditService();
const governance = new GovernanceService();
const production = new ManuscriptProductionService();
const editor = new IntelligentEditingService();
const coverStudio = new BookCoverStudioService();
const illustrationReferences = new IllustrationReferencePipeline();
const defaultProjectId = "forge-studio";
const MEMORY_CLASSES: readonly MemoryClass[] = ["author-memory", "project-memory", "story-canon", "character-memory", "relationship-memory", "location-memory", "timeline-memory", "style-memory", "research-memory", "creative-note", "working-draft", "hypothesis", "open-thread", "visual-identity", "production-memory", "publishing-memory", "marketing-memory", "generated-alternative", "decision-memory"];
const MEMORY_AUTHORITIES: readonly MemoryAuthority[] = ["proposed", "working", "verified", "authoritative", "superseded", "archived"];
const REFERENCE_MIME_TYPES = ["image/png", "image/jpeg", "image/webp"] as const;
const MAX_REFERENCE_BYTES = 5 * 1024 * 1024;

type ProjectWithWorkspace = Awaited<ReturnType<FileProjectStore["load"]>> & { studioWorkspace?: StudioWorkspaceState };
async function ensureDefaultProject(): Promise<void> { if (!(await store.exists(defaultProjectId))) await store.create(createProject({ id: defaultProjectId, title: "My First Forge Book" })); }
function json(res: ServerResponse,status:number,value:unknown):void{res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"});res.end(JSON.stringify(value));}
function text(res:ServerResponse,status:number,value:string,contentType:string):void{res.writeHead(status,{"content-type":contentType,"cache-control":"no-store","x-content-type-options":"nosniff"});res.end(value);}
async function body(req:IncomingMessage):Promise<Record<string,unknown>>{let raw="";for await(const chunk of req)raw+=String(chunk);if(raw.length>8*1024*1024)throw new Error("Request body exceeds 8 MiB limit.");if(!raw.trim())return{};const parsed=JSON.parse(raw);if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error("JSON object body required.");return parsed as Record<string,unknown>;}
function projectIdFrom(pathname:string):string|null{const match=pathname.match(/^\/api\/projects\/([A-Za-z0-9_-]+)(?:\/|$)/);return match?.[1]??null;}
function enumValue<T extends string>(value:unknown,allowed:readonly T[],label:string):T{if(typeof value!=="string"||!allowed.includes(value as T))throw new Error(`Invalid ${label}.`);return value as T;}
function workspaceOf(project:ProjectWithWorkspace):StudioWorkspaceState{return project?.studioWorkspace?validateStudioWorkspace(project.studioWorkspace):createStudioWorkspace();}
function saveWorkspace(project:ProjectWithWorkspace,workspace:StudioWorkspaceState):ProjectWithWorkspace{return{...project,studioWorkspace:validateStudioWorkspace(workspace),metadata:{...project.metadata,updatedAt:new Date().toISOString()}} as ProjectWithWorkspace;}
function parseJsonObject(textValue:string):Record<string,unknown>{const fenced=textValue.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1]??textValue;const start=fenced.indexOf("{");const end=fenced.lastIndexOf("}");if(start<0||end<=start)throw new Error("AI did not return a JSON object for the requested structured plan.");const parsed=JSON.parse(fenced.slice(start,end+1));if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error("AI structured plan was not an object.");return parsed as Record<string,unknown>;}
async function listProjects():Promise<Array<{id:string;title:string;updatedAt:string}>>{const root=join(dataRoot,"projects");try{const entries=await readdir(root,{withFileTypes:true});const projects:Array<{id:string;title:string;updatedAt:string}>=[];for(const entry of entries){if(!entry.isDirectory()||!/^[A-Za-z0-9_-]+$/.test(entry.name))continue;const project=await store.load(entry.name);if(project)projects.push({id:project.metadata.id,title:project.metadata.title,updatedAt:project.metadata.updatedAt});}return projects.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));}catch(error){if(error&&typeof error==="object"&&"code" in error&&(error as{code?:string}).code==="ENOENT")return[];throw error;}}
async function projectHealth(project:ProjectWithWorkspace){const workspace=workspaceOf(project);const books=workspace.books;const chapters=books.flatMap((b)=>b.chapters);const scenes=chapters.flatMap((c)=>c.scenes);const words=scenes.reduce((n,s)=>n+s.wordCount,0);return{projectId:project.metadata.id,status:project.metadata.status,metrics:{books:books.length,chapters:chapters.length,scenes:scenes.length,words,characters:(project.characters??[]).length,memories:project.memories.length,researchRecords:project.memories.filter((m)=>m.class==="research-memory").length,canonRecords:project.memories.filter((m)=>m.class==="story-canon").length,illustrations:project.illustrationAssetLibrary?.assets?.length??0,audits:project.deliveryAudits?.length??0},readiness:{hasStructure:books.length>0&&chapters.length>0&&scenes.length>0,hasWriting:words>0,hasCharacters:(project.characters??[]).length>0,hasResearch:project.memories.some((m)=>m.class==="research-memory"),hasCanon:project.memories.some((m)=>m.class==="story-canon"),hasGenome:Boolean(project.bookGenome?.nodes?.length)}};}
async function readBinaryBody(req:IncomingMessage):Promise<Buffer>{const chunks:Buffer[]=[];let total=0;for await(const chunk of req){const part=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);total+=part.byteLength;if(total>MAX_REFERENCE_BYTES)throw new Error("Reference image exceeds the 5 MiB limit.");chunks.push(part);}return Buffer.concat(chunks,total);}
async function handleApi(req:IncomingMessage,res:ServerResponse,url:URL):Promise<boolean>{
if(url.pathname==="/api/health"&&req.method==="GET"){json(res,200,{ok:true,service:"authors-forge-studio",projectId:defaultProjectId,port,ai:{openai:Boolean(process.env.OPENAI_API_KEY&&process.env.OPENAI_MODEL),ollama:Boolean(process.env.OLLAMA_BASE_URL&&process.env.OLLAMA_MODEL),image:Boolean(process.env.OPENAI_API_KEY)}});return true;}
if(url.pathname==="/api/governance"&&req.method==="GET"){json(res,200,{ownership:governance.ownershipPolicy(),accessibility:governance.accessibilityProfile()});return true;}
if(url.pathname==="/api/projects"&&req.method==="GET"){json(res,200,await listProjects());return true;}
if(url.pathname==="/api/projects"&&req.method==="POST"){const input=await body(req);const project=createProject({id:String(input.id??""),title:String(input.title??"")});await store.create(project);json(res,201,project);return true;}
const projectId=projectIdFrom(url.pathname);if(!projectId)return false;const loaded=await store.load(projectId);if(!loaded){json(res,404,{error:"Project not found."});return true;}const project=loaded as ProjectWithWorkspace;
if(url.pathname===`/api/projects/${projectId}`&&req.method==="GET"){json(res,200,project);return true;}
if(url.pathname===`/api/projects/${projectId}/collaboration`&&req.method==="GET"){json(res,200,project.aiCollaborationPolicy??createAiCollaborationPolicy("co-pilot"));return true;}
if(url.pathname===`/api/projects/${projectId}/collaboration`&&req.method==="POST"){const input=await body(req);const policy=createAiCollaborationPolicy(enumValue(input.mode,AI_COLLABORATION_MODES,"collaboration mode") as AiCollaborationMode);await store.save(withProjectAiCollaborationPolicy(project,policy) as never);json(res,200,policy);return true;}
if(url.pathname===`/api/projects/${projectId}/health`&&req.method==="GET"){json(res,200,await projectHealth(project));return true;}
if(url.pathname===`/api/projects/${projectId}/package`&&req.method==="GET"){json(res,200,{formatVersion:1,exportedAt:new Date().toISOString(),project,workspace:workspaceOf(project)});return true;}
if(url.pathname===`/api/projects/${projectId}/workspace`&&req.method==="GET"){json(res,200,workspaceOf(project));return true;}
if(url.pathname===`/api/projects/${projectId}/workspace/activate`&&req.method==="POST"){const input=await body(req);const workspace=setActiveBook(workspaceOf(project),String(input.bookId??""));await store.save(saveWorkspace(project,workspace) as never);json(res,200,workspace);return true;}
if(url.pathname===`/api/projects/${projectId}/workspace/books`&&req.method==="POST"){const input=await body(req);const workspace=addWorkspaceBook(workspaceOf(project),createWorkspaceBook({id:String(input.id??`book-${randomUUID()}`),title:String(input.title??""),kind:input.kind as never,description:String(input.description??"")}));await store.save(saveWorkspace(project,workspace) as never);json(res,201,workspace.books.find((b)=>b.id===workspace.activeBookId));return true;}
const bookMatch=url.pathname.match(new RegExp(`^/api/projects/${projectId}/workspace/books/([^/]+)/chapters$`));if(bookMatch&&req.method==="POST"){const input=await body(req);const workspace=addWorkspaceChapter(workspaceOf(project),bookMatch[1],{id:String(input.id??`chapter-${randomUUID()}`),number:Number(input.number),title:String(input.title??""),synopsis:String(input.synopsis??"")});await store.save(saveWorkspace(project,workspace) as never);json(res,201,getBook(workspace,bookMatch[1]).chapters.find((c)=>c.id===String(input.id)));return true;}
const chapterMatch=url.pathname.match(new RegExp(`^/api/projects/${projectId}/workspace/books/([^/]+)/chapters/([^/]+)/scenes$`));if(chapterMatch&&req.method==="POST"){const input=await body(req);const workspace=addWorkspaceScene(workspaceOf(project),chapterMatch[1],chapterMatch[2],{id:String(input.id??`scene-${randomUUID()}`),number:Number(input.number),title:String(input.title??""),synopsis:String(input.synopsis??"")});await store.save(saveWorkspace(project,workspace) as never);json(res,201,getBook(workspace,chapterMatch[1]).chapters.find((c)=>c.id===chapterMatch[2]));return true;}
const sceneContentMatch=url.pathname.match(new RegExp(`^/api/projects/${projectId}/workspace/books/([^/]+)/chapters/([^/]+)/scenes/([^/]+)/content$`));if(sceneContentMatch&&req.method==="PUT"){const input=await body(req);const workspace=saveSceneContent(workspaceOf(project),sceneContentMatch[1],sceneContentMatch[2],sceneContentMatch[3],String(input.content??""));await store.save(saveWorkspace(project,workspace) as never);const book=workspace.books.find((b)=>b.id===sceneContentMatch[1])!;json(res,200,getScene(book,sceneContentMatch[2],sceneContentMatch[3]));return true;}
if(url.pathname===`/api/projects/${projectId}/illustration/references`&&req.method==="POST"){const mime=enumValue(req.headers["content-type"]?.split(";",1)[0]??"",REFERENCE_MIME_TYPES,"reference image MIME type");const fileName=String(url.searchParams.get("fileName")??`reference-${randomUUID()}.${mime.split("/")[1]}`);const bytes=await readBinaryBody(req);if(bytes.byteLength===0)throw new Error("Reference image is empty.");const assetId=`reference-${randomUUID()}`;const assetDir=join(dataRoot,"projects",projectId,"illustrations","references");await mkdir(assetDir,{recursive:true});const extension=mime==="image/jpeg"?"jpg":mime.split("/")[1];const relativeUri=`/api/projects/${projectId}/illustration/references/${assetId}.${extension}`;await writeFile(join(assetDir,`${assetId}.${extension}`),bytes,{flag:"wx"});const reference=illustrationReferences.createReference({id:assetId,projectId,originalFileName:fileName,mimeType:mime,bytes:new Uint8Array(bytes),assetUri:relativeUri});json(res,201,reference);return true;}
const referenceMatch=url.pathname.match(new RegExp(`^/api/projects/${projectId}/illustration/references/([^/]+)\\.(png|jpg|jpeg|webp)$`));if(referenceMatch&&req.method==="GET"){const extension=referenceMatch[2]==="jpeg"?"jpg":referenceMatch[2];const path=join(dataRoot,"projects",projectId,"illustrations","references",`${referenceMatch[1]}.${extension}`);try{const bytes=await readFile(path);res.writeHead(200,{"content-type":extension==="jpg"?"image/jpeg":`image/${extension}`,"cache-control":"no-store","x-content-type-options":"nosniff"});res.end(bytes);}catch(error){if(error&&typeof error==="object"&&"code" in error&&(error as{code?:string}).code==="ENOENT"){json(res,404,{error:"Reference image not found."});return true;}throw error;}}
